/** JDScience original 11+ Verbal Reasoning Practice Paper 1 — 100% original content. */

export const verbalPaper1 = {
  id: "verbal-practice-paper-1",
  title: "JDScience 11+ Verbal Reasoning Practice Paper 1",
  answersTitle: "JDScience 11+ Verbal Reasoning Practice Paper 1 — Answers and Explanations",
  subject: "Verbal Reasoning",
  timeMinutes: 50,
  questions: [
    {
      id: "vr1-q01",
      kind: "synonym",
      stem: "Choose the word closest in meaning to ABUNDANT.",
      options: ["Scarce","Plentiful","Narrow","Fragile","Silent"],
      answer: "B",
      explanation: "Abundant means present in large quantities. Plentiful is the closest synonym. Scarce is an antonym.",
    },
    {
      id: "vr1-q02",
      kind: "synonym",
      stem: "Choose the word closest in meaning to COURAGEOUS.",
      options: ["Timid","Careful","Gentle","Brave","Quiet"],
      answer: "D",
      explanation: "Courageous means showing bravery. Brave is the matching synonym; timid means the opposite.",
    },
    {
      id: "vr1-q03",
      kind: "synonym",
      stem: "Choose the word closest in meaning to ANCIENT.",
      options: ["Old","Recent","Fresh","Modern","Bright"],
      answer: "A",
      explanation: "Ancient means very old. Old is the closest meaning among the options.",
    },
    {
      id: "vr1-q04",
      kind: "synonym",
      stem: "Choose the word closest in meaning to ENORMOUS.",
      options: ["Tiny","Soft","Huge","Swift","Pale"],
      answer: "C",
      explanation: "Enormous means very large. Huge is the synonym; tiny is an antonym.",
    },
    {
      id: "vr1-q05",
      kind: "synonym",
      stem: "Choose the word closest in meaning to DELIGHT.",
      options: ["Anger","Fear","Effort","Doubt","Joy"],
      answer: "E",
      explanation: "Delight means great pleasure or joy. Joy is the closest synonym.",
    },
    {
      id: "vr1-q06",
      kind: "antonym",
      stem: "Choose the word most nearly opposite in meaning to ARRIVE.",
      options: ["Reach","Enter","Depart","Visit","Appear"],
      answer: "C",
      explanation: "Arrive means to come to a place. Depart (to leave) is the clearest opposite.",
    },
    {
      id: "vr1-q07",
      kind: "antonym",
      stem: "Choose the word most nearly opposite in meaning to GENEROUS.",
      options: ["Selfish","Kind","Friendly","Honest","Cheerful"],
      answer: "A",
      explanation: "Generous means willing to give freely. Selfish (keeping things for oneself) is the opposite.",
    },
    {
      id: "vr1-q08",
      kind: "antonym",
      stem: "Choose the word most nearly opposite in meaning to EXPAND.",
      options: ["Grow","Widen","Lengthen","Spread","Shrink"],
      answer: "E",
      explanation: "Expand means to become larger. Shrink means to become smaller.",
    },
    {
      id: "vr1-q09",
      kind: "antonym",
      stem: "Choose the word most nearly opposite in meaning to VICTORY.",
      options: ["Success","Defeat","Prize","Triumph","Glory"],
      answer: "B",
      explanation: "Victory means winning. Defeat means losing and is the antonym.",
    },
    {
      id: "vr1-q10",
      kind: "antonym",
      stem: "Choose the word most nearly opposite in meaning to TRANSPARENT.",
      options: ["Clear","Glass","Bright","Opaque","Thin"],
      answer: "D",
      explanation: "Transparent means see-through. Opaque means not allowing light through.",
    },
    {
      id: "vr1-q11",
      kind: "analogy",
      stem: "Bird is to nest as bee is to ________.",
      options: ["Hive","Honey","Flower","Wing","Sting"],
      answer: "A",
      explanation: "A nest is where a bird lives; a hive is where a bee lives. The relationship is home/dwelling.",
    },
    {
      id: "vr1-q12",
      kind: "analogy",
      stem: "Author is to book as composer is to ________.",
      options: ["Piano","Orchestra","Audience","Stage","Song"],
      answer: "E",
      explanation: "An author creates a book; a composer creates a song (or piece of music). Creator → product.",
    },
    {
      id: "vr1-q13",
      kind: "analogy",
      stem: "Finger is to hand as toe is to ________.",
      options: ["Shoe","Leg","Foot","Ankle","Sock"],
      answer: "C",
      explanation: "Fingers are parts of a hand; toes are parts of a foot.",
    },
    {
      id: "vr1-q14",
      kind: "analogy",
      stem: "Hot is to cold as day is to ________.",
      options: ["Sun","Night","Week","Light","Morning"],
      answer: "B",
      explanation: "Hot and cold are opposites; day and night are opposites.",
    },
    {
      id: "vr1-q15",
      kind: "analogy",
      stem: "Teacher is to classroom as chef is to ________.",
      options: ["Menu","Plate","Recipe","Kitchen","Oven"],
      answer: "D",
      explanation: "A classroom is a teacher’s main workplace; a kitchen is a chef’s main workplace.",
    },
    {
      id: "vr1-q16",
      kind: "analogy",
      stem: "Kitten is to cat as puppy is to ________.",
      options: ["Dog","Bark","Bone","Lead","Kennel"],
      answer: "A",
      explanation: "A kitten is a young cat; a puppy is a young dog.",
    },
    {
      id: "vr1-q17",
      kind: "letter-sequence",
      stem: "Which letter comes next? B, D, F, H, ___",
      options: ["I","K","J","L","M"],
      answer: "C",
      explanation: "The sequence skips one letter each time (B→D→F→H). After H, skip I to get J.",
    },
    {
      id: "vr1-q18",
      kind: "letter-sequence",
      stem: "Which letter comes next? A, C, F, J, ___",
      options: ["M","N","Q","P","O"],
      answer: "E",
      explanation: "Gaps increase by 1: A→C (+2), C→F (+3), F→J (+4), so J→O (+5).",
    },
    {
      id: "vr1-q19",
      kind: "letter-sequence",
      stem: "Which letter comes next? Z, X, V, T, ___",
      options: ["S","R","Q","P","O"],
      answer: "B",
      explanation: "Working backwards through the alphabet, skipping one letter each time: Z→X→V→T→R.",
    },
    {
      id: "vr1-q20",
      kind: "letter-sequence",
      stem: "Which pair continues the pattern? AB, CD, EF, GH, ___",
      options: ["HI","KL","JK","IJ","LM"],
      answer: "D",
      explanation: "Each pair is two consecutive letters, then the next unused consecutive pair: IJ follows GH.",
    },
    {
      id: "vr1-q21",
      kind: "letter-sequence",
      stem: "Which letter comes next? C, F, I, L, ___",
      options: ["O","N","M","P","Q"],
      answer: "A",
      explanation: "Each letter is three places on: C→F→I→L→O.",
    },
    {
      id: "vr1-q22",
      kind: "letter-sequence",
      stem: "Which letter comes next? A, B, D, G, K, ___",
      options: ["N","O","R","Q","P"],
      answer: "E",
      explanation: "Gaps are +1, +2, +3, +4: A→B (+1), B→D (+2), D→G (+3), G→K (+4), K→P (+5).",
    },
    {
      id: "vr1-q23",
      kind: "word-relationship",
      stem: "Which word is most closely related to LIBRARY?",
      options: ["Garden","Books","Kitchen","Stadium","Harbour"],
      answer: "B",
      explanation: "A library is primarily associated with books and reading materials.",
    },
    {
      id: "vr1-q24",
      kind: "word-relationship",
      stem: "Which word completes the pair in the same way? Bread is to bakery as medicine is to ________.",
      options: ["Hospital","Doctor","Patient","Pharmacy","Illness"],
      answer: "D",
      explanation: "Bread is sold/made at a bakery; medicine is dispensed at a pharmacy.",
    },
    {
      id: "vr1-q25",
      kind: "word-relationship",
      stem: "Find the word that connects both pairs: CLOCK → TIME and THERMOMETER → ________.",
      options: ["Weather","Heat","Temperature","Mercury","Glass"],
      answer: "C",
      explanation: "A clock measures time; a thermometer measures temperature.",
    },
    {
      id: "vr1-q26",
      kind: "word-relationship",
      stem: "Which word best belongs with: violin, flute, trumpet?",
      options: ["Drum","Canvas","Brush","Stage","Curtain"],
      answer: "A",
      explanation: "Violin, flute and trumpet are musical instruments; a drum is also an instrument.",
    },
    {
      id: "vr1-q27",
      kind: "word-relationship",
      stem: "Car is to road as boat is to ________.",
      options: ["Sail","Harbour","Captain","Anchor","Water"],
      answer: "E",
      explanation: "A car travels on a road; a boat travels on water.",
    },
    {
      id: "vr1-q28",
      kind: "odd-one-out",
      stem: "Which word does not belong with the others?",
      options: ["Apple","Carrot","Banana","Orange","Pear"],
      answer: "B",
      explanation: "Apple, banana, orange and pear are fruits; carrot is a vegetable.",
    },
    {
      id: "vr1-q29",
      kind: "odd-one-out",
      stem: "Which word does not belong with the others?",
      options: ["Square","Circle","Triangle","Cube","Rectangle"],
      answer: "D",
      explanation: "Square, circle, triangle and rectangle are 2D shapes; a cube is 3D.",
    },
    {
      id: "vr1-q30",
      kind: "odd-one-out",
      stem: "Which word does not belong with the others?",
      options: ["Red","Blue","Loud","Green","Yellow"],
      answer: "C",
      explanation: "Red, blue, green and yellow are colours; loud describes volume/sound.",
    },
    {
      id: "vr1-q31",
      kind: "odd-one-out",
      stem: "Which word does not belong with the others?",
      options: ["Hammer","Saw","Spanner","Screwdriver","Nail"],
      answer: "E",
      explanation: "Hammer, saw, spanner and screwdriver are tools; a nail is a fastener used with tools.",
    },
    {
      id: "vr1-q32",
      kind: "odd-one-out",
      stem: "Which word does not belong with the others?",
      options: ["January","Friday","Sunday","Monday","Wednesday"],
      answer: "A",
      explanation: "Monday, Friday, Sunday and Wednesday are days of the week; January is a month.",
    },
    {
      id: "vr1-q33",
      kind: "code",
      stem: "If C=3, A=1, T=7 and CAT is written 317, how is ACT written?",
      options: ["317","137","731","173","371"],
      answer: "B",
      explanation: "A=1, C=3, T=7, so ACT → 137.",
    },
    {
      id: "vr1-q34",
      kind: "code",
      stem: "In a code, PEN = 16-5-14. What is the code for NAP?",
      options: ["15-1-14","13-1-15","14-1-15","14-1-16","14-2-16"],
      answer: "D",
      explanation: "Letters are coded by alphabet position: N=14, A=1, P=16 → 14-1-16.",
    },
    {
      id: "vr1-q35",
      kind: "code",
      stem: "If each letter is replaced by the next letter in the alphabet, how is COLD written?",
      options: ["DMPE","BNKC","DPME","DNME","CPME"],
      answer: "C",
      explanation: "C→D, O→P, L→M, D→E, giving DPME.",
    },
    {
      id: "vr1-q36",
      kind: "code",
      stem: "If FISH is written as GJTI, how would LAMP be written using the same rule?",
      options: ["MBNQ","KZOQ","MBNO","NZOQ","MBOP"],
      answer: "A",
      explanation: "Each letter advances by one: L→M, A→B, M→N, P→Q → MBNQ.",
    },
    {
      id: "vr1-q37",
      kind: "code",
      stem: "In a simple code, A=1, B=2, C=3, … If DOG = 4+15+7=26, what is the value of CAT?",
      options: ["22","30","26","28","24"],
      answer: "E",
      explanation: "C=3, A=1, T=20; 3+1+20=24.",
    },
    {
      id: "vr1-q38",
      kind: "missing-letters",
      stem: "Which letter completes the words meaning a feline and a type of headwear? C _ T and H _ T",
      options: ["E","A","I","O","U"],
      answer: "B",
      explanation: "Inserting A gives CAT (a feline) and HAT (headwear).",
    },
    {
      id: "vr1-q39",
      kind: "missing-letters",
      stem: "Which letter completes both words? S _ N and R _ N (a star and a short race).",
      options: ["A","E","I","U","O"],
      answer: "D",
      explanation: "Option D is the letter U, giving SUN and RUN — matching the clue (a star and a short race).",
    },
    {
      id: "vr1-q40",
      kind: "missing-letters",
      stem: "Which pair of letters completes the word meaning ‘opposite of north’? S _ _ T H",
      options: ["AI","EA","OU","OO","EE"],
      answer: "C",
      explanation: "Inserting OU gives SOUTH, the compass direction opposite north.",
    }
  ],
};
