"""GCSE Physics exam walkthrough pack content — original JDScience questions."""

from __future__ import annotations

from .content_helpers import DEFAULT_STEPS, calc_q, q, topic_pack

TOPIC_ENERGY = "Energy"
TOPIC_ELECTRICITY = "Electricity"
TOPIC_PARTICLE = "Particle model of matter"
TOPIC_ATOMIC = "Atomic structure and radioactivity"
TOPIC_FORCES = "Forces"
TOPIC_WAVES = "Waves"
TOPIC_MAGNETISM = "Magnetism and electromagnetism"
TOPIC_SPACE = "Space physics"
TOPIC_PRACTICAL = "Required practical skills"


def _energy_questions() -> list[dict]:
    return [
        q(
            "State the unit of energy.",
            TOPIC_ENERGY,
            "state",
            1,
            "Knowledge recall",
            "The question tests whether you know the SI unit used for energy.",
            DEFAULT_STEPS,
            "The unit of energy is the joule (J).",
            ["Correct unit named as joule or J."],
            ["Writing watts (W) instead of joules.", "Spelling 'joules' without the symbol when asked for the unit."],
            "Energy is measured in joules; power is measured in watts.",
        ),
        q(
            "Give one example of a renewable energy resource.",
            TOPIC_ENERGY,
            "give",
            1,
            "Knowledge recall",
            "You must name one energy resource that is naturally replenished.",
            DEFAULT_STEPS,
            "One example is solar energy.",
            ["Any valid renewable named, e.g. solar, wind, hydroelectric, tidal, geothermal, or biomass."],
            ["Naming a fossil fuel such as coal.", "Naming nuclear fuel without noting it is non-renewable."],
            "Learn a short list of renewables and one non-renewable for quick comparison questions.",
        ),
        q(
            "State what is meant by a closed system in energy transfers.",
            TOPIC_ENERGY,
            "state",
            1,
            "Knowledge recall",
            "Define the idea of a closed system in the context of energy.",
            DEFAULT_STEPS,
            "A closed system is one where no energy is transferred to or from the surroundings.",
            ["States that no energy enters or leaves the system."],
            ["Saying no matter can enter or leave (that describes a closed system in chemistry, not the energy definition needed here).", "Confusing closed with isolated systems at A-level."],
            "In GCSE physics, closed system usually means the total energy stays the same.",
        ),
        q(
            "Describe the energy transfer when a student lifts a book from the floor to a shelf.",
            TOPIC_ENERGY,
            "describe",
            2,
            "Energy transfers",
            "Describe what happens to energy during this transfer without explaining why in detail.",
            [
                "Identify the initial and final energy stores.",
                "Name the method of transfer (work done by a force).",
                "State energy gained by one store and supplied from another.",
                "Use correct energy store names.",
                "Check both stores are mentioned.",
            ],
            "Chemical energy in the student's muscles decreases and gravitational potential energy of the book increases. Energy is transferred mechanically by the upward force doing work on the book.",
            [
                "Chemical store of muscles identified as decreasing.",
                "Gravitational potential energy of book identified as increasing.",
            ],
            ["Saying energy is created.", "Using 'kinetic' only without mentioning the work done against gravity."],
            "Always name both the store that decreases and the store that increases.",
        ),
        q(
            "Explain why a car's brakes get hot when the car slows down.",
            TOPIC_ENERGY,
            "explain",
            2,
            "Energy dissipation",
            "Give the reason linked to energy transfer when braking.",
            [
                "Identify the kinetic energy store involved.",
                "State where energy is transferred to.",
                "Link heating to friction.",
                "Use the idea of wasted or dissipated energy.",
                "Check the explanation answers why, not just what happens.",
            ],
            "The brakes get hot because kinetic energy of the car is transferred to the thermal store of the brakes and surroundings through friction, which dissipates useful energy as heat.",
            [
                "Kinetic energy decreases or is transferred.",
                "Thermal energy increases in brakes due to friction / dissipation.",
            ],
            ["Saying energy is destroyed.", "Only stating brakes touch without mentioning energy stores."],
            "Use 'transferred to the thermal store' rather than 'lost'.",
        ),
        q(
            "Compare the energy changes in a pendulum at the highest point and at the bottom of its swing.",
            TOPIC_ENERGY,
            "compare",
            2,
            "Energy stores",
            "Identify similarities and differences in energy stores at two positions.",
            DEFAULT_STEPS,
            "At the highest point the pendulum has maximum gravitational potential energy and minimum kinetic energy. At the bottom, gravitational potential energy is minimum and kinetic energy is maximum. In both positions, if air resistance is ignored, total energy is conserved.",
            [
                "Correct stores compared at both positions (GPE high/low, KE low/high).",
                "Similarity or conservation comment, or clear contrast of both positions.",
            ],
            ["Only describing one position.", "Ignoring kinetic energy at the bottom."],
            "Compare command words need features of both situations.",
        ),
        q(
            "Explain why insulating a house reduces heating costs.",
            TOPIC_ENERGY,
            "explain",
            3,
            "Efficiency and insulation",
            "Link insulation to reduced energy transfer and cost.",
            [
                "State what insulation reduces (thermal transfer).",
                "Explain less energy leaves the home.",
                "Link to heater switching on less often.",
                "Connect to lower fuel/electrical use.",
                "Use correct terminology: thermal store, transfer, efficiency.",
            ],
            "Insulation reduces the rate of energy transfer by heating to the surroundings. Less energy must be supplied by the heating system to maintain the same temperature, so less fuel or electricity is used and heating costs fall.",
            [
                "Insulation reduces energy transfer to surroundings.",
                "Less energy input needed to maintain temperature.",
                "Lower energy use reduces cost.",
            ],
            ["Saying insulation creates energy.", "Only stating 'keeps heat in' without energy transfer language."],
            "Link every efficiency answer to reduced wasted energy transfer.",
        ),
        q(
            "A kettle transfers 180 kJ of energy to water in 3 minutes. Describe how you would calculate its power and state what extra information you already have.",
            TOPIC_ENERGY,
            "describe",
            3,
            "Power",
            "Outline the calculation method using given data.",
            DEFAULT_STEPS,
            "Power is calculated using P = E ÷ t. The energy transferred E is 180 kJ and the time t is 3 minutes, which must be converted to seconds (180 s) before substituting. Dividing energy by time gives power in watts if SI units are used.",
            [
                "States P = E ÷ t or equivalent.",
                "Identifies E and t from the question.",
                "Notes time must be converted to seconds for SI power in watts.",
            ],
            ["Using minutes directly without conversion.", "Confusing power with energy."],
            "Always convert minutes to seconds before calculating power in watts.",
        ),
        q(
            "Evaluate the use of wind turbines compared with gas-fired power stations for generating electricity.",
            TOPIC_ENERGY,
            "evaluate",
            4,
            "Energy resources",
            "Weigh advantages and disadvantages and reach a balanced judgement.",
            [
                "Give advantage(s) of wind.",
                "Give limitation(s) of wind.",
                "Give advantage(s) of gas.",
                "Give limitation(s) of gas.",
                "Reach an overall judgement.",
            ],
            "Wind turbines produce no direct carbon dioxide during operation and use a renewable resource, but output varies with weather and turbines need suitable locations. Gas-fired stations provide reliable, controllable output but burn fossil fuel, emit carbon dioxide, and contribute to climate change. Wind is better for lowering emissions long term, but gas currently helps meet demand when wind is low.",
            [
                "Valid advantage of wind.",
                "Valid limitation of wind.",
                "Valid advantage of gas.",
                "Valid limitation of gas or overall judgement.",
            ],
            ["One-sided answer.", "No reference to reliability or emissions."],
            "Evaluation needs points on both sides plus a conclusion.",
        ),
        q(
            "Describe, with examples, the difference between renewable and non-renewable energy resources.",
            TOPIC_ENERGY,
            "describe",
            4,
            "Energy resources",
            "Describe both categories and give an example of each.",
            DEFAULT_STEPS,
            "Renewable resources are replenished as they are used, such as wind or solar. Non-renewable resources exist in finite amounts and will run out, such as coal, oil, and natural gas. Nuclear fuel is also treated as non-renewable at GCSE because uranium reserves are limited.",
            [
                "Renewable definition with example.",
                "Non-renewable definition with example.",
                "Clear contrast between replenished and finite.",
                "Second valid point such as second example or time scale.",
            ],
            ["No examples.", "Calling nuclear renewable without qualification."],
            "Pair each definition with a named example.",
        ),
        q(
            "A motor lifts a 12 kg load through 2.5 m in 4.0 s. Calculate the power output of the motor. Use g = 9.8 N/kg. Show your working.",
            TOPIC_ENERGY,
            "calculate",
            6,
            "Extended calculation",
            "Calculate power from a lifting scenario using energy or work done.",
            [
                "Calculate weight or force needed: W = mg.",
                "Calculate work done or energy transferred: E = F × s.",
                "Convert time to seconds if needed.",
                "Use P = E ÷ t.",
                "Include units on the final answer.",
            ],
            "Weight = 12 × 9.8 = 117.6 N. Energy transferred = 117.6 × 2.5 = 294 J. Power = 294 ÷ 4.0 = 73.5 W. The power output is 73 W (2 s.f.) or 74 W.",
            [
                "Correct method for work/energy gained (294 J or equivalent).",
                "Correct use of P = E/t.",
                "Correct substitution.",
                "Correct final value with unit W.",
                "Working shown.",
                "Appropriate significant figures.",
            ],
            ["Using mass instead of weight in Ep = mgh without g.", "Forgetting units.", "Dividing by time in minutes."],
            "For lifting at constant speed, work done on load equals energy transferred.",
            extension="Alternatively, P = Fv if speed is known: v = 2.5/4.0 = 0.625 m/s, P = 117.6 × 0.625 = 73.5 W.",
        ),
        calc_q(
            "A 0.50 kg ball moving at 8.0 m/s is caught by a player. Calculate the kinetic energy of the ball.",
            TOPIC_ENERGY,
            3,
            "Calculate kinetic energy using mass and speed.",
            [
                "Write Ek = ½mv².",
                "Substitute m = 0.50 kg and v = 8.0 m/s.",
                "Square the speed before multiplying.",
                "Include unit J on the answer.",
            ],
            "Ek = ½ × 0.50 × 8.0² = 0.25 × 64 = 16 J.",
            [
                "Correct equation Ek = ½mv².",
                "Correct substitution.",
                "Correct answer 16 J with unit.",
            ],
            ["Forgetting to square velocity.", "Missing ½ factor.", "No unit."],
            "Always square the speed before multiplying by mass.",
        ),
        q(
            "Describe how you would investigate the specific heat capacity of a metal block using an immersion heater, thermometer, and balance.",
            TOPIC_ENERGY,
            "describe",
            4,
            "Required practical skills",
            "Describe the method for measuring energy input and temperature change.",
            [
                "Measure mass of block.",
                "Measure initial temperature.",
                "Supply known energy with heater for set time at known power.",
                "Measure final temperature and calculate ΔT.",
                "Reference E = Pt and E = mcΔT.",
            ],
            "Find the mass of the block on a balance. Measure initial temperature. Record the power of the immersion heater and time it is switched on so energy supplied E = Pt is known. Measure final temperature and calculate temperature change ΔT. Use c = E ÷ (mΔT) to find specific heat capacity. Repeat and calculate a mean.",
            [
                "Mass measured.",
                "Initial and final temperatures measured.",
                "Energy input determined using E = Pt.",
                "Link to c = E/mΔT or equivalent method steps.",
            ],
            ["Not explaining how energy input is found.", "Measuring only one temperature."],
            "Practical descriptions must include how key quantities are measured.",
        ),
    ]


def _electricity_questions() -> list[dict]:
    return [
        q(
            "State the relationship between current, charge, and time.",
            TOPIC_ELECTRICITY,
            "state",
            1,
            "Knowledge recall",
            "Recall the equation linking charge, current, and time.",
            DEFAULT_STEPS,
            "Charge flow Q = I × t.",
            ["Correct relationship Q = It stated."],
            ["Writing V = IR instead.", "Reversing the relationship to t = Q/I when only the relationship is asked."],
            "Say 'charge flow equals current times time'.",
        ),
        q(
            "Give the unit of electrical resistance.",
            TOPIC_ELECTRICITY,
            "give",
            1,
            "Knowledge recall",
            "Name the unit for resistance.",
            DEFAULT_STEPS,
            "The unit of resistance is the ohm (Ω).",
            ["Ohm or Ω."],
            ["Writing volts or amps.", "Spelling ohm incorrectly without symbol."],
            "Resistance uses Ω; current uses A; potential difference uses V.",
        ),
        q(
            "State what happens to the current in a series circuit if one lamp is removed and the circuit breaks.",
            TOPIC_ELECTRICITY,
            "state",
            1,
            "Series circuits",
            "State the effect on current when the circuit is open.",
            DEFAULT_STEPS,
            "The current stops flowing / becomes zero because the circuit is incomplete.",
            ["Current stops or becomes zero due to broken/open circuit."],
            ["Saying current increases.", "Saying other lamps get brighter in a broken circuit."],
            "Open circuit means no complete path for charge flow.",
        ),
        q(
            "Describe the difference between series and parallel circuits for lamp brightness when another lamp is added.",
            TOPIC_ELECTRICITY,
            "describe",
            2,
            "Circuit arrangements",
            "Compare how adding a lamp affects others in series and parallel.",
            DEFAULT_STEPS,
            "In series, adding another lamp increases total resistance so current decreases and all lamps become dimmer. In parallel, each lamp is across the full supply voltage so each stays equally bright when another branch is added.",
            [
                "Series: current/resistance effect makes lamps dimmer.",
                "Parallel: each lamp has full p.d. so brightness unchanged.",
            ],
            ["Only describing one type.", "Saying parallel lamps dim when another is added."],
            "Link brightness to current in series and p.d. in parallel.",
        ),
        q(
            "Explain why metals are good conductors of electricity.",
            TOPIC_ELECTRICITY,
            "explain",
            2,
            "Conduction",
            "Explain using charge carriers in metals.",
            DEFAULT_STEPS,
            "Metals contain delocalised electrons that are free to move through the structure. When a potential difference is applied, these electrons drift through the metal, carrying charge and creating an electric current.",
            [
                "Delocalised/free electrons mentioned.",
                "Electrons move when p.d. applied causing current.",
            ],
            ["Referring to protons moving.", "Saying atoms move through the wire."],
            "Conductors: free electrons. Insulators: electrons cannot move freely.",
        ),
        q(
            "A student connects a 6.0 V battery to a resistor of 12 Ω. Calculate the current in the resistor.",
            TOPIC_ELECTRICITY,
            "calculate",
            2,
            "Calculation",
            "Use V = IR to find current.",
            [
                "Rearrange to I = V ÷ R.",
                "Substitute values.",
                "Calculate and give unit A.",
            ],
            "I = V ÷ R = 6.0 ÷ 12 = 0.50 A.",
            [
                "Correct rearrangement I = V/R.",
                "Correct answer 0.50 A with unit.",
            ],
            ["Multiplying V and R.", "Unit mA without conversion shown."],
            "Show rearrangement before substituting.",
        ),
        q(
            "Explain why electrical appliances with metal cases must be earthed.",
            TOPIC_ELECTRICITY,
            "explain",
            3,
            "Mains safety",
            "Link earthing to safety if live wire touches the case.",
            [
                "State case could become live if fault occurs.",
                "Earth wire provides low-resistance path to ground.",
                "Large current flows, fuse blows or breaker trips.",
                "Prevents user receiving shock.",
            ],
            "If the live wire touches the metal case, the case becomes dangerous. The earth wire connects the case to the ground so a large current flows to earth, which melts the fuse or trips the circuit breaker, disconnecting the supply and preventing a person from receiving a fatal shock.",
            [
                "Fault makes case live.",
                "Earth provides path to ground causing large current.",
                "Fuse/breaker disconnects supply protecting user.",
            ],
            ["Saying earth prevents all current.", "No link to fuse or breaker."],
            "Earth wire works with fuse or RCD to protect users.",
        ),
        q(
            "Describe how the total resistance of two identical resistors changes when connected in series and when connected in parallel.",
            TOPIC_ELECTRICITY,
            "describe",
            3,
            "Combined resistance",
            "Describe both combinations for identical resistors.",
            DEFAULT_STEPS,
            "In series, total resistance is the sum of individual resistances, so two identical resistors double the total resistance. In parallel, total resistance is less than either resistor alone because there are more paths for current; for two identical resistors, total resistance is half of one resistor.",
            [
                "Series: resistances add, total doubles for identical pair.",
                "Parallel: total is less; half value for two identical.",
                "Both series and parallel described.",
            ],
            ["Saying parallel resistance is larger.", "Only one arrangement described."],
            "Series adds; parallel reduces total resistance.",
        ),
        q(
            "A filament lamp has a resistance of 120 Ω at normal brightness. Calculate the charge that flows through the lamp in 2 minutes when connected to 12 V. Show your working.",
            TOPIC_ELECTRICITY,
            "calculate",
            4,
            "Extended calculation",
            "Combine V = IR and Q = It.",
            [
                "Find current using I = V/R.",
                "Convert time to seconds.",
                "Use Q = It.",
                "Include unit C.",
            ],
            "I = 12 ÷ 120 = 0.10 A. t = 2 × 60 = 120 s. Q = 0.10 × 120 = 12 C.",
            [
                "Current calculated correctly.",
                "Time converted to seconds.",
                "Q = It used correctly.",
                "Answer 12 C with unit.",
            ],
            ["Using minutes in Q = It.", "Wrong current from V/R error."],
            "Multi-step electricity questions: solve one unknown at a time.",
        ),
        q(
            "Compare direct current (d.c.) and alternating current (a.c.).",
            TOPIC_ELECTRICITY,
            "compare",
            4,
            "Current types",
            "Identify differences between d.c. and a.c.",
            DEFAULT_STEPS,
            "Direct current flows in one direction only, such as from a cell. Alternating current repeatedly reverses direction, as supplied by the UK mains at about 50 Hz. Mains a.c. is also at much higher voltage than typical cells.",
            [
                "d.c. one direction.",
                "a.c. reverses direction.",
                "Example or frequency/mains context.",
                "Additional valid difference such as source or voltage.",
            ],
            ["Saying a.c. does not change direction.", "No comparison of both."],
            "UK mains: 230 V a.c. at 50 Hz.",
        ),
        q(
            "The National Grid uses step-up transformers at power stations and step-down transformers near homes. Explain why transformers are used in this way, including how they affect current in the transmission cables and energy loss.",
            TOPIC_ELECTRICITY,
            "explain",
            6,
            "Power transmission",
            "Explain step-up and step-down roles and link to reduced heating in cables.",
            [
                "Step-up increases voltage for transmission.",
                "For same power, higher voltage means lower current (P = VI).",
                "Lower current reduces energy loss by heating in cables (I²R).",
                "Step-down reduces voltage to safe 230 V for homes.",
                "Transformers only work with a.c.",
            ],
            "Power stations use step-up transformers to increase transmission voltage, which reduces current in the cables for the same power transferred. Lower current reduces wasted energy as heat in the cables because power loss depends on I²R. Near homes, step-down transformers reduce voltage to a safe 230 V. Transformers require alternating current to operate.",
            [
                "Step-up increases voltage for transmission.",
                "Lower current for same power.",
                "Reduced I²R energy loss in cables.",
                "Step-down for safe domestic voltage.",
                "Transformers and a.c. link.",
                "Clear logical explanation throughout.",
            ],
            ["Saying transformers increase power.", "No link to I²R losses."],
            "Higher transmission voltage → lower current → less wasted heat.",
        ),
        calc_q(
            "A charge of 450 C flows through a lamp in 3 minutes. Calculate the current in the lamp.",
            TOPIC_ELECTRICITY,
            3,
            "Calculate current from charge flow and time.",
            [
                "Use I = Q ÷ t.",
                "Convert 3 minutes to 180 s.",
                "Divide and give answer in amps.",
            ],
            "t = 3 × 60 = 180 s. I = 450 ÷ 180 = 2.5 A.",
            [
                "Time converted to seconds.",
                "Correct use of I = Q/t.",
                "Answer 2.5 A with unit.",
            ],
            ["Using minutes directly.", "Inverting equation incorrectly."],
            "Charge flow questions almost always need seconds.",
        ),
        q(
            "Describe how you would investigate how the resistance of a wire depends on its length using a circuit with an ammeter, voltmeter, and metre rule.",
            TOPIC_ELECTRICITY,
            "describe",
            4,
            "Required practical skills",
            "Describe controlling variables and taking repeat readings.",
            [
                "Set up wire, ammeter in series, voltmeter in parallel.",
                "Measure length with metre rule.",
                "Record current and p.d., calculate R = V/I.",
                "Keep material, diameter, and temperature constant.",
                "Repeat and plot R against length.",
            ],
            "Connect the wire in series with ammeter and power supply; connect voltmeter in parallel with the wire. Measure length with a metre rule. Record current and potential difference, then calculate R = V/I. Keep material, thickness, and temperature constant while changing only length. Take repeat readings for each length, remove anomalies, and plot a graph of resistance against length.",
            [
                "Correct circuit description.",
                "R = V/I used.",
                "Length measured.",
                "Control variables and repeats mentioned.",
            ],
            ["Ammeter in parallel.", "No control variables."],
            "Required practical answers should name equipment and control variables.",
        ),
    ]


def _particle_questions() -> list[dict]:
    return [
        q("State what is meant by density.", TOPIC_PARTICLE, "state", 1, "Knowledge recall",
          "Define density as a property of matter.", DEFAULT_STEPS,
          "Density is mass per unit volume.", ["Mass per unit volume stated."],
          ["Saying weight per volume.", "No reference to volume."], "Use 'mass per unit volume' exactly."),
        q("Give the state of matter in which particles are close together but can slide past each other.", TOPIC_PARTICLE, "give", 1, "Knowledge recall",
          "Name the state with fixed volume but changeable shape.", DEFAULT_STEPS,
          "Liquid.", ["Liquid identified."], ["Gas.", "Solid when sliding is mentioned."], "Solid fixed shape; liquid fixed volume; gas fills container."),
        q("State what happens to the pressure of a fixed mass of gas when its volume is decreased at constant temperature.", TOPIC_PARTICLE, "state", 1, "Gas pressure",
          "State the effect on pressure when volume decreases.", DEFAULT_STEPS,
          "Pressure increases.", ["Pressure increases."], ["Pressure decreases.", "Saying temperature must rise without question saying so."], "Boyle's law: smaller volume → higher pressure at constant temperature."),
        q("Describe the arrangement and movement of particles in a solid.", TOPIC_PARTICLE, "describe", 2, "Particle model",
          "Describe particle positions and motion in a solid.", DEFAULT_STEPS,
          "Particles in a solid are close together in a regular arrangement and vibrate about fixed positions.", ["Close together / regular arrangement.", "Vibrate about fixed positions."],
          ["Saying particles move freely.", "No mention of vibration."], "Solids: strong forces, fixed positions, vibrate."),
        q("Explain why a balloon expands when heated.", TOPIC_PARTICLE, "explain", 2, "Gas behaviour",
          "Link heating to particle speed and pressure.", DEFAULT_STEPS,
          "Heating increases the average kinetic energy of air particles so they move faster and hit the balloon walls more often and with greater force, increasing pressure and causing expansion.", ["Particles move faster / more kinetic energy.", "More frequent or harder collisions increase pressure causing expansion."],
          ["Saying particles get bigger.", "No link to collisions."], "Heating gases: faster particles → more pressure."),
        q("Compare the density of a solid block and the same material after it melts.", TOPIC_PARTICLE, "compare", 2, "Density",
          "Compare density before and after melting for same material.", DEFAULT_STEPS,
          "When the solid melts to a liquid, particles move slightly further apart so volume increases slightly while mass stays the same, meaning density decreases.", ["Volume increases when melted.", "Density decreases because mass unchanged."],
          ["Saying density increases.", "Only describing one state."], "Same mass, larger volume → lower density."),
        q("A block has mass 540 g and volume 200 cm³. Calculate its density in g/cm³.", TOPIC_PARTICLE, "calculate", 3, "Calculation",
          "Use density = mass ÷ volume.", ["Write ρ = m/V.", "Substitute 540 and 200.", "Divide and include unit.", "Check answer sensible."],
          "ρ = 540 ÷ 200 = 2.7 g/cm³.", ["Correct equation.", "Correct substitution.", "Answer 2.7 g/cm³."],
          ["Multiplying mass and volume.", "Unit kg/m³ without conversion."], "Always state unit g/cm³ or kg/m³ clearly."),
        q("Explain why steam burns can be more severe than boiling water burns at 100 °C.", TOPIC_PARTICLE, "explain", 3, "Internal energy",
          "Link latent heat of vaporisation to extra energy transfer.", DEFAULT_STEPS,
          "Steam at 100 °C condenses on skin and releases latent heat of vaporisation as well as cooling from 100 °C, transferring more energy than water at 100 °C alone.", ["Steam condenses releasing latent heat.", "Extra energy transferred beyond 100 °C water.", "More severe burn linked to extra energy."],
          ["Only stating steam is hotter than 100 °C.", "No latent heat idea."], "Condensation releases latent heat — a favourite exam point."),
        q("Describe how you would determine the density of an irregular stone using a balance, displacement can, and measuring cylinder.", TOPIC_PARTICLE, "describe", 4, "Required practical skills",
          "Describe measuring mass and volume by displacement.", DEFAULT_STEPS,
          "Find mass on a balance. Fill a displacement can to the spout, then submerge the stone and collect displaced water in a measuring cylinder to find volume. Calculate density using ρ = m/V. Repeat and mean.", ["Mass measured on balance.", "Volume by displacement.", "ρ = m/V used.", "Repeat/mean mentioned."],
          ["Measuring volume with a ruler.", "No displacement method."], "Irregular objects need displacement for volume."),
        q("Evaluate using the particle model to explain why liquids fill the bottom of a container but gases fill all available space.", TOPIC_PARTICLE, "evaluate", 4, "Particle model",
          "Use particle spacing and forces to evaluate the explanation.", DEFAULT_STEPS,
          "The model explains that liquid particles are close but mobile, so they stay together under gravity at the bottom, whereas gas particles are far apart with weak forces and move randomly in all directions, spreading throughout any volume. The model is useful but does not predict exact evaporation rates without more detail.", ["Liquid particles close, move but stay together.", "Gas particles far apart, random motion fills space.", "Evaluation of model usefulness or limitation.", "Balanced conclusion."],
          ["No comparison of both states.", "No evaluation judgement."], "Evaluate = explain plus judge how good the model is."),
        q("A 2.0 kg copper block is heated from 20 °C to 80 °C. The specific heat capacity of copper is 385 J/kg °C. Calculate the energy transferred to the block.", TOPIC_PARTICLE, "calculate", 6, "Extended calculation",
          "Use E = mcΔT.", ["Find ΔT = 80 − 20.", "Use E = mcΔT.", "Substitute all values.", "Calculate with unit J.", "Show working.", "Check sign and unit."],
          "ΔT = 60 °C. E = 2.0 × 385 × 60 = 46 200 J = 4.62 × 10⁴ J.", ["ΔT correct.", "E = mcΔT used.", "Substitution correct.", "Answer 46 200 J.", "Unit J.", "Working shown."],
          ["Using 80 instead of ΔT.", "Missing unit."], "Specific heat capacity needs temperature change not final temperature."),
        calc_q("Calculate the density of a material if a sample of mass 1.2 kg has a volume of 0.00040 m³. Give your answer in kg/m³.", TOPIC_PARTICLE, 3,
          "Calculate density in SI units.", ["Use ρ = m/V.", "Substitute values.", "Divide and give kg/m³."],
          "ρ = 1.2 ÷ 0.00040 = 3000 kg/m³.", ["Correct equation.", "Correct substitution.", "Answer 3000 kg/m³."],
          ["Incorrect power of ten.", "Unit g/cm³ only."], "Convert cm³ to m³ carefully in mixed unit questions."),
        q(
            "Describe how the particle model explains changes of state when ice melts to form water.",
            TOPIC_PARTICLE,
            "describe",
            4,
            "Changes of state",
            "Describe particle behaviour during melting without calculating energy values.",
            DEFAULT_STEPS,
            "In ice, particles vibrate in fixed positions in a regular lattice. When melting, energy increases until particles break free from fixed positions and move while staying close together, becoming liquid with greater disorder but similar spacing.",
            [
                "Solid particles vibrate in fixed positions.",
                "Energy input during melting.",
                "Particles move but remain close in liquid.",
                "Link to increased disorder without large spacing change.",
            ],
            ["Saying particles separate completely like a gas.", "No mention of energy input."],
            "Melting increases kinetic energy until bonds in the lattice break.",
        ),
    ]


def _atomic_questions() -> list[dict]:
    return [
        q("State the name of radiation consisting of helium nuclei.", TOPIC_ATOMIC, "state", 1, "Radioactivity",
          "Identify alpha radiation.", DEFAULT_STEPS, "Alpha (α) radiation.", ["Alpha or α."], ["Beta.", "Gamma."], "α = 2 protons + 2 neutrons."),
        q("Give one source of background radiation.", TOPIC_ATOMIC, "give", 1, "Background radiation",
          "Name a natural or man-made background source.", DEFAULT_STEPS,
          "Radon gas from rocks (or cosmic rays / medical sources / nuclear weapons fallout).", ["Any valid background source."], ["Microwave ovens (not ionising background).", "Visible light."], "Radon from rocks is a common UK example."),
        q("State what is meant by the half-life of a radioactive isotope.", TOPIC_ATOMIC, "state", 1, "Half-life",
          "Define half-life.", DEFAULT_STEPS,
          "Half-life is the time taken for the activity (or number of undecayed nuclei) to halve.", ["Time for activity or undecayed nuclei to halve."], ["Half the life of atom.", "Time for all nuclei to decay."], "Half-life is statistical — not when all nuclei are gone."),
        q("Describe what happens to the nucleus during beta-minus decay.", TOPIC_ATOMIC, "describe", 2, "Nuclear decay",
          "Describe the change in the nucleus when beta is emitted.", DEFAULT_STEPS,
          "A neutron changes into a proton and an electron; the electron is emitted as beta radiation and the nucleus has one more proton so atomic number increases by one.", ["Neutron becomes proton and electron.", "Beta particle emitted; atomic number increases."],
          ["Proton becomes neutron without specifying beta-minus.", "Nucleus unchanged."], "Beta-minus: neutron → proton + electron."),
        q("Explain why alpha radiation is more ionising than gamma radiation.", TOPIC_ATOMIC, "explain", 2, "Radiation properties",
          "Link particle size/charge to ionisation.", DEFAULT_STEPS,
          "Alpha particles are large and doubly charged so they strongly interact with atoms, removing electrons over a short distance. Gamma photons have less charge interaction per collision and are less ionising.", ["Alpha large/charged, strong interactions.", "More ionisation per alpha particle than gamma."],
          ["Saying gamma has more energy so more ionising.", "No interaction argument."], "Ionising power ≠ penetrating power."),
        q("Compare how alpha, beta, and gamma radiation are stopped.", TOPIC_ATOMIC, "compare", 2, "Penetration",
          "Compare stopping materials for three types.", DEFAULT_STEPS,
          "Alpha is stopped by paper or a few centimetres of air. Beta is stopped by thin aluminium. Gamma requires thick lead or thick concrete to be significantly reduced.", ["Alpha stopped by paper/air.", "Beta stopped by aluminium.", "Gamma reduced by thick lead/concrete."],
          ["All stopped by paper.", "Only one type described."], "Penetration increases α < β < γ."),
        q("Explain why radioactive sources used in medical tracers must have a short half-life.", TOPIC_ATOMIC, "explain", 3, "Uses of radiation",
          "Link half-life to dose and safety.", DEFAULT_STEPS,
          "A short half-life means activity falls quickly so the patient receives a lower total dose of radiation. The tracer remains detectable long enough for diagnosis then decays rapidly.", ["Short half-life reduces dose.", "Still detectable for scan.", "Decays quickly after use."],
          ["Long half-life preferred.", "No dose argument."], "Medical tracers: short half-life, gamma emitter."),
        q("A radioactive sample has activity 800 counts/min. After 2 half-lives, what is the activity?", TOPIC_ATOMIC, "calculate", 3, "Half-life calculation",
          "Apply halving twice.", ["Activity halves each half-life.", "Apply twice.", "State final value with unit."],
          "After 1 half-life: 400 counts/min. After 2 half-lives: 200 counts/min.", ["First halving to 400.", "Second halving to 200.", "Correct final value."],
          ["Dividing by 4 without showing steps.", "Adding instead of halving."], "Each half-life multiplies activity by ½."),
        q("Describe the plum pudding model and how the alpha scattering experiment led to the nuclear model.", TOPIC_ATOMIC, "describe", 4, "Atomic models",
          "Describe both models and evidence from Rutherford.", DEFAULT_STEPS,
          "Plum pudding: positive charge spread throughout with electrons embedded. Rutherford fired alpha particles at thin gold foil; most passed through but some deflected through large angles. This showed most of the atom is empty space with a small, dense, positively charged nucleus.", ["Plum pudding described.", "Most alphas passed through.", "Large deflections showed small dense nucleus.", "Nuclear model conclusion."],
          ["Electrons in nucleus.", "No link to deflection evidence."], "Large angle scattering → small massive nucleus."),
        q("Evaluate the use of nuclear fission for generating electricity.", TOPIC_ATOMIC, "evaluate", 4, "Nuclear power",
          "Weigh benefits and risks.", DEFAULT_STEPS,
          "Fission produces large energy from small fuel and no direct CO₂ during operation, giving reliable baseload power. However, radioactive waste must be stored safely, accidents can release contamination, and plant decommissioning is costly. Useful low-carbon source if waste and safety are managed.", ["High energy output/low CO₂.", "Waste or accident risk.", "Reliability advantage.", "Overall judgement."],
          ["Only advantages.", "Confusing fission with fusion."], "Fission = large nuclei split; fusion = small nuclei join."),
        q("An isotope has a half-life of 6 hours. A sample has initial activity 320 Bq. Calculate the activity after 18 hours.", TOPIC_ATOMIC, "calculate", 6, "Extended calculation",
          "Determine number of half-lives and apply repeatedly.", ["18 ÷ 6 = 3 half-lives.", "Halve three times or multiply by (½)³.", "Calculate final activity.", "Include unit Bq.", "Show working.", "Check answer."],
          "18 hours = 3 half-lives. Activity = 320 × (½)³ = 320 × 0.125 = 40 Bq.", ["3 half-lives identified.", "Correct multiplier (½)³.", "Answer 40 Bq.", "Unit Bq.", "Working.", "Logical method."],
          ["Dividing by 3 instead of halving.", "Wrong number of half-lives."], "Always find number of half-lives first."),
        calc_q("Radon-222 has a half-life of 3.8 days. A sample contains 1200 undecayed nuclei. Estimate how many remain after 7.6 days.", TOPIC_ATOMIC, 3,
          "Apply two half-lives.", ["7.6 ÷ 3.8 = 2 half-lives.", "Halve twice.", "State integer nuclei."],
          "2 half-lives: 1200 → 600 → 300 nuclei remain.", ["2 half-lives.", "First halving.", "Answer 300 nuclei."],
          ["Linear subtraction.", "Wrong half-life count."], "Half-life questions rarely need exact exponentials at GCSE."),
        q("Describe how you would investigate the thickness of paper required to absorb beta radiation from a source, safely.", TOPIC_ATOMIC, "describe", 4, "Required practical skills",
          "Describe safe method with detector and absorbers.", DEFAULT_STEPS,
          "Set source in lead collimator at fixed distance from G-M tube. Measure count rate with no absorber using timer. Place increasing sheets of paper, record count rate each time. Use tongs, keep distance, minimise time, plot count rate against number of sheets.", ["Fixed distance and timing.", "Variable absorber thickness.", "Safety: distance, tongs, minimise time.", "Repeat readings."],
          ["Handling source with bare hands.", "No control of distance."], "Radiation practicals must include safety precautions."),
    ]


def _forces_questions() -> list[dict]:
    return [
        q("State the unit of force.", TOPIC_FORCES, "state", 1, "Knowledge recall", "Name SI unit of force.", DEFAULT_STEPS, "The newton (N).", ["Newton or N."], ["Joule.", "Kg."], "Force N; mass kg; weight N."),
        q("Give the equation linking force, mass, and acceleration.", TOPIC_FORCES, "give", 1, "Equations", "Recall Newton's second law equation.", DEFAULT_STEPS, "F = ma.", ["F = ma."], ["F = mv.", "a = F/m reversed incorrectly as the equation."], "F = ma is in the physics equation sheet."),
        q("State what is meant by the resultant force on an object.", TOPIC_FORCES, "state", 1, "Resultant forces", "Define resultant force.", DEFAULT_STEPS, "The resultant force is the single force that has the same effect as all forces acting on the object combined.", ["Single force equivalent to combined forces."], ["Largest force only.", "Weight only."], "Resultant decides acceleration direction."),
        q("Describe the motion of an object when the resultant force is zero.", TOPIC_FORCES, "describe", 2, "Newton's first law",
          "Describe velocity when resultant force zero.", DEFAULT_STEPS,
          "If the object is stationary it remains at rest. If it is moving it continues at constant velocity in a straight line.", ["Stationary stays at rest.", "Moving continues at constant velocity."],
          ["Object always stops.", "Speed always zero."], "Zero resultant → no change in velocity."),
        q("Explain why a seat belt reduces injury in a car crash.", TOPIC_FORCES, "explain", 2, "Safety",
          "Link increased stopping time to reduced force.", DEFAULT_STEPS,
          "The seat belt increases the time taken for the passenger to stop. For the same change in momentum, a longer time reduces the rate of change of momentum, so the force on the passenger is smaller.", ["Increases stopping time.", "Reduces force for same momentum change."],
          ["Saying belt reduces momentum.", "No time or force link."], "F = Δp/Δt — longer time → smaller force."),
        q("A car of mass 1200 kg accelerates at 2.5 m/s². Calculate the resultant force.", TOPIC_FORCES, "calculate", 2, "Calculation",
          "Use F = ma.", ["Write F = ma.", "Substitute.", "Answer in N."],
          "F = 1200 × 2.5 = 3000 N.", ["F = ma.", "Answer 3000 N."],
          ["Dividing mass by acceleration.", "Unit kg."], "Show F = ma before numbers."),
        q("Explain why a skydiver reaches terminal velocity.", TOPIC_FORCES, "explain", 3, "Terminal velocity",
          "Link drag to increasing speed until forces balance.", DEFAULT_STEPS,
          "As speed increases, air resistance increases until it equals weight. Resultant force becomes zero so acceleration is zero and the skydiver falls at constant terminal velocity.", ["Drag increases with speed.", "Forces balance at terminal velocity.", "Zero acceleration at constant speed."],
          ["Weight disappears.", "No mention of air resistance."], "Terminal velocity when drag = weight."),
        q("Describe how force–extension data from a spring experiment can be used to find the spring constant.", TOPIC_FORCES, "describe", 3, "Hooke's law",
          "Describe graph and gradient.", DEFAULT_STEPS,
          "Measure force and extension for increasing loads within elastic limit. Plot force against extension. The spring constant k is the gradient of the linear region because F = kx.", ["Measure F and x.", "Plot F against x.", "k is gradient of linear region."],
          ["Plotting x against F without noting reciprocal.", "Using region beyond limit of proportionality."], "Gradient of F–x graph gives k."),
        q("Compare elastic and inelastic deformation.", TOPIC_FORCES, "compare", 4, "Materials",
          "Compare whether object returns to original shape.", DEFAULT_STEPS,
          "Elastic deformation returns to original shape when force is removed, such as a spring within its limit. Inelastic deformation does not fully return, such as stretching a plastic ruler permanently.", ["Elastic returns to original shape.", "Inelastic permanent change.", "Valid examples.", "Clear contrast."],
          ["Only one type described.", "Confusing with elastic potential energy only."], "Elastic limit marks boundary on spring graphs."),
        q("A 0.40 kg ball travelling at 12 m/s hits a wall and rebounds at 8.0 m/s. The contact time is 0.020 s. Calculate the average force on the ball during the collision.", TOPIC_FORCES, "calculate", 4, "Momentum",
          "Use F = Δp/Δt with direction.", ["Choose positive direction.", "Calculate Δp including rebound.", "Use F = Δp/Δt.", "State unit N."],
          "Take initial direction positive: u = +12, v = −8. Δp = m(v−u) = 0.40×(−8−12) = −8.0 kg m/s. F = Δp/Δt = −8.0/0.020 = −400 N. Magnitude 400 N (opposite to initial motion).", ["Momentum change includes direction.", "Δp = −8.0 kg m/s.", "F = Δp/Δt used.", "Answer 400 N."],
          ["Ignoring rebound direction.", "Using speed only."], "Rebound problems need signed velocities."),
        q("A lorry of mass 8000 kg slows from 25 m/s to 10 m/s in 5.0 s. Calculate the resultant force acting on the lorry.", TOPIC_FORCES, "calculate", 6, "Extended calculation",
          "Use F = ma after finding a, or F = Δp/Δt.", ["Find acceleration a = Δv/t.", "Use F = ma.", "Substitute mass.", "Include unit N.", "Show working.", "Correct sign/decision."],
          "a = (10 − 25)/5.0 = −3.0 m/s². F = 8000 × (−3.0) = −24 000 N. Retarding force 24 000 N.", ["a = −3.0 m/s².", "F = ma used.", "m = 8000 kg.", "Answer 24 000 N.", "Unit N.", "Working shown."],
          ["Using speed magnitudes only without deceleration sign.", "Dividing wrong way for a."], "Deceleration: final minus initial over time."),
        calc_q("Calculate the momentum of a 1500 kg car travelling at 20 m/s.", TOPIC_FORCES, 3,
          "Use p = mv.", ["Write p = mv.", "Multiply 1500 × 20.", "Unit kg m/s."],
          "p = 1500 × 20 = 30 000 kg m/s.", ["p = mv.", "Substitution.", "30 000 kg m/s."],
          ["Adding mass and velocity.", "Unit N s only without equivalence note."], "Momentum = mass × velocity."),
        q("Describe how you would investigate the relationship between force and extension for a spring up to its limit of proportionality.", TOPIC_FORCES, "describe", 4, "Required practical skills",
          "Describe apparatus and measurements.", DEFAULT_STEPS,
          "Clamp spring vertically, attach known masses to find weight as force, measure extension with ruler from original length. Record force and extension, add masses incrementally, plot F against x, identify linear region.", ["Force from known weights.", "Extension measured.", "F–x graph.", "Stay within limit of proportionality."],
          ["Measuring length not extension.", "No graph mention."], "Extension = stretched length minus original length."),
    ]


def _waves_questions() -> list[dict]:
    return [
        q("State the equation linking wave speed, frequency, and wavelength.", TOPIC_WAVES, "state", 1, "Wave equation",
          "Recall v = fλ.", DEFAULT_STEPS, "Wave speed v = frequency × wavelength (v = fλ).", ["v = fλ stated."],
          ["v = f/λ.", "Missing any quantity."], "Say 'wave speed equals frequency times wavelength'."),
        q("Give the unit of frequency.", TOPIC_WAVES, "give", 1, "Knowledge recall", "Name unit of frequency.", DEFAULT_STEPS, "Hertz (Hz).", ["Hertz or Hz."], ["Metres per second.", "Seconds."], "Hz = per second."),
        q("State what is meant by the amplitude of a wave.", TOPIC_WAVES, "state", 1, "Wave properties",
          "Define amplitude.", DEFAULT_STEPS, "Amplitude is the maximum displacement of a point on the wave from its rest position.", ["Maximum displacement from rest."],
          ["Whole wave length.", "Distance between peaks only without displacement."], "Amplitude on graph is height from middle to peak."),
        q("Describe the difference between transverse and longitudinal waves.", TOPIC_WAVES, "describe", 2, "Wave types",
          "Compare vibration direction to wave direction.", DEFAULT_STEPS,
          "In transverse waves, vibrations are perpendicular to wave direction, e.g. water waves. In longitudinal waves, vibrations are parallel to wave direction, e.g. sound.", ["Transverse: perpendicular vibrations with example.", "Longitudinal: parallel vibrations with example."],
          ["Only one type.", "Wrong examples."], "Light and water: transverse. Sound: longitudinal."),
        q("Explain why sound cannot travel through a vacuum.", TOPIC_WAVES, "explain", 2, "Sound",
          "Link sound to particle vibrations.", DEFAULT_STEPS,
          "Sound is a longitudinal wave that needs particles to vibrate and pass energy along. In a vacuum there are no particles to vibrate, so sound cannot propagate.", ["Sound needs medium/particles.", "Vacuum has no particles."],
          ["Sound is blocked by vacuum 'walls'.", "Confusing with light."], "Sound needs a medium; light does not."),
        q("A wave has frequency 500 Hz and wavelength 0.68 m. Calculate the wave speed.", TOPIC_WAVES, "calculate", 2, "Calculation",
          "Use v = fλ.", ["Write v = fλ.", "Multiply.", "Unit m/s."],
          "v = 500 × 0.68 = 340 m/s.", ["v = fλ.", "340 m/s."],
          ["Dividing.", "Unit Hz."], "Show substitution before answer."),
        q("Explain how refraction occurs when light enters glass from air.", TOPIC_WAVES, "explain", 3, "Refraction",
          "Link speed change to direction change.", DEFAULT_STEPS,
          "Light slows down when entering denser glass so one part of the wavefront slows before the rest, causing the wave to change direction. The ray bends towards the normal.", ["Speed decreases in glass.", "Wavefront change causes bending.", "Towards normal on entering denser medium."],
          ["Light speeds up entering glass.", "No wavefront explanation."], "Refraction: speed change → direction change."),
        q("Describe how a ripple tank can be used to investigate reflection of water waves.", TOPIC_WAVES, "describe", 3, "Investigations",
          "Describe apparatus and observations.", DEFAULT_STEPS,
          "Generate straight ripples with a bar dipper toward a barrier at an angle. Observe incident and reflected wavefronts. Measure angles to normal for incident and reflected waves; they should be equal.", ["Straight ripples toward barrier.", "Observe reflected wavefronts.", "Angle of incidence equals angle of reflection."],
          ["No barrier.", "Confusing with refraction."], "Ripple tanks show reflection and refraction visually."),
        q("Compare uses of ultraviolet and infrared radiation.", TOPIC_WAVES, "compare", 4, "EM spectrum",
          "Compare applications of two EM regions.", DEFAULT_STEPS,
          "Ultraviolet is used in sterilisation and security marking because it causes fluorescence and kills microbes. Infrared is used in heating, thermal imaging, and remote controls because it transfers thermal energy and is detected by electronic sensors.", ["Valid UV use.", "Valid IR use.", "Linked to properties.", "Contrast between uses."],
          ["Same use for both.", "Only one region."], "Link use to property: UV ionisation/fluorescence; IR heating."),
        q("A student stands 680 m from a cliff and hears an echo after 4.0 s. Calculate the speed of sound.", TOPIC_WAVES, "calculate", 4, "Echo calculation",
          "Account for double distance.", ["Distance travelled = 2 × 680 m.", "Use v = d/t.", "Unit m/s."],
          "d = 2 × 680 = 1360 m. v = 1360 ÷ 4.0 = 340 m/s.", ["Double distance used.", "v = d/t.", "340 m/s.", "Unit m/s."],
          ["Using 680 m only.", "Wrong time."], "Echo: sound travels to cliff and back."),
        q(
            "A television station sends the same programme through a cable and by radio wave at the same instant. Both signals travel 60 km to a house. Explain why the arrival times are almost identical, and suggest why the cable picture might appear slightly earlier on screen.",
            TOPIC_WAVES,
            "explain",
            6,
            "EM waves",
            "Compare travel times over the same distance and consider processing delays.",
            [
                "Both signals are electromagnetic and travel at about the same speed over the same distance.",
                "Use t = d/v to show times are nearly equal for 60 km.",
                "Cable feed may have less broadcasting/retransmission delay than the radio chain.",
                "State that path length is the same for both in this scenario.",
                "Use correct physics vocabulary.",
                "Answer both parts clearly.",
            ],
            "Both signals travel 60 km at approximately 3 × 10⁸ m/s, so t = 60 000 ÷ (3 × 10⁸) ≈ 0.0002 s for each — arrival times are almost identical. The cable picture may appear slightly earlier because the radio broadcast can include extra encoding and retransmission steps that add a small delay compared with the direct cable feed.",
            [
                "Same distance and similar EM wave speed stated.",
                "Travel times nearly equal.",
                "Processing/retransmission delay for radio suggested.",
                "Clear logical structure.",
                "Correct terminology.",
                "Both parts addressed.",
            ],
            ["Saying lower frequency radio is slower over the same distance.", "Ignoring equal path length."],
            "Same distance and speed → same travel time unless equipment adds delay.",
        ),
        calc_q("Calculate the wavelength of a 2.4 MHz radio wave. Wave speed c = 3.0 × 10⁸ m/s.", TOPIC_WAVES, 3,
          "Rearrange v = fλ.", ["Convert MHz to Hz.", "Rearrange λ = v/f.", "Calculate with unit m."],
          "f = 2.4 × 10⁶ Hz. λ = 3.0×10⁸ ÷ 2.4×10⁶ = 125 m.", ["Frequency converted.", "λ = v/f.", "125 m."],
          ["Not converting MHz.", "Wrong power of ten."], "Always convert prefix to base unit."),
        q("Describe how you would measure the speed of sound in air using two microphones connected to a data logger.", TOPIC_WAVES, "describe", 4, "Required practical skills",
          "Describe timing across known distance.", DEFAULT_STEPS,
          "Place two microphones a measured distance apart facing a loud sharp sound source. Data logger records time difference between peaks. Speed = distance ÷ time difference. Repeat and mean.", ["Known separation measured.", "Time difference recorded.", "v = d/t.", "Repeat readings."],
          ["Single microphone.", "No distance measurement."], "Sharp sound gives clear peak on trace."),
    ]


def _magnetism_questions() -> list[dict]:
    return [
        q("State what is meant by a magnetic field.", TOPIC_MAGNETISM, "state", 1, "Magnetism",
          "Define magnetic field.", DEFAULT_STEPS, "A magnetic field is a region where a magnetic material or moving charge experiences a force.", ["Region where magnetic force acts."],
          ["Region with electric charge only.", "Area with gravity."], "Field shown by iron filings or plotting compass."),
        q("Give the rule that links the direction of force on a current-carrying wire in a magnetic field.", TOPIC_MAGNETISM, "give", 1, "Motor effect",
          "Name Fleming's left-hand rule.", DEFAULT_STEPS, "Fleming's left-hand rule.", ["Fleming's left-hand rule."],
          ["Right-hand rule for generators only without naming left for force.", "Ohm's law."], "Left hand: force; right hand: induced current."),
        q("State what happens to the force on a wire in a magnetic field when the current is reversed.", TOPIC_MAGNETISM, "state", 1, "Motor effect",
          "State effect of reversing current.", DEFAULT_STEPS, "The direction of the force reverses.", ["Force direction reverses."],
          ["Force doubles.", "No change."], "Reverse current or field → force reverses."),
        q("Describe the pattern and direction of magnetic field lines around a bar magnet.", TOPIC_MAGNETISM, "describe", 2, "Magnetic fields",
          "Describe shape and direction.", DEFAULT_STEPS,
          "Field lines leave the north pole and enter the south pole outside the magnet. Lines are closest where the field is strongest.", ["North to south outside magnet.", "Density shows strength."],
          ["South to north outside.", "Lines cross."], "Field lines never cross."),
        q("Explain how a simple electric motor produces rotation.", TOPIC_MAGNETISM, "explain", 2, "Motors",
          "Link force on coil to split-ring commutator.", DEFAULT_STEPS,
          "Current in the coil experiences forces due to the motor effect on opposite sides in opposite directions, producing a turning effect. The split-ring commutator reverses current every half turn so rotation continues in the same direction.", ["Forces on coil create couple.", "Commutator reverses current each half turn.", "Continuous rotation."],
          ["No commutator role.", "Forces same direction on both sides."], "Commutator keeps torque direction consistent."),
        q("Compare the function of a step-up transformer and a step-down transformer.", TOPIC_MAGNETISM, "compare", 2, "Transformers",
          "Compare voltage changes.", DEFAULT_STEPS,
          "A step-up transformer increases potential difference from primary to secondary; a step-down transformer decreases potential difference.", ["Step-up increases voltage.", "Step-down decreases voltage."],
          ["Both increase voltage.", "Transformers work on d.c."], "Transformers need alternating current."),
        q("Explain electromagnetic induction in a wire moving through a magnetic field.", TOPIC_MAGNETISM, "explain", 3, "Induction",
          "Explain how potential difference is induced.", DEFAULT_STEPS,
          "When a conductor cuts through magnetic field lines, a potential difference is induced across it. If the circuit is complete, an induced current flows. Faster cutting or stronger field increases induced p.d.", ["Conductor cuts field lines.", "Induced p.d. across conductor.", "Current if complete circuit."],
          ["Magnetic field created by movement without cutting lines.", "Constant field linkage only at GCSE basic level confused."], "Induction needs relative motion between conductor and field."),
        q("A transformer has 500 turns on the primary coil and 50 turns on the secondary. The primary p.d. is 230 V. Calculate the secondary p.d.", TOPIC_MAGNETISM, "calculate", 3, "Transformers",
          "Use Vp/Vs = Np/Ns.", ["Write ratio equation.", "Substitute.", "Calculate Vs."],
          "Vs = Vp × Ns/Np = 230 × 50/500 = 23 V.", ["Correct ratio.", "Substitution.", "23 V."],
          ["Inverted ratio.", "Adding turns."], "Step-down here: fewer secondary turns → lower voltage."),
        q("Describe how a generator produces an alternating potential difference.", TOPIC_MAGNETISM, "describe", 4, "Generators",
          "Describe coil rotation in magnetic field.", DEFAULT_STEPS,
          "Coil rotates in magnetic field so sides cut field lines. Induced p.d. reverses every half turn as direction of cutting reverses, producing a.c. Output voltage depends on speed of rotation and field strength.", ["Coil rotates cutting field lines.", "Induced p.d. reverses each half turn.", "a.c. output.", "Factors affecting output."],
          ["Direct current from basic generator without split ring difference.", "No rotation."], "Dynamos use slip rings for a.c."),
        q("Evaluate using renewable energy with wind turbines that contain electromagnets in their generators.", TOPIC_MAGNETISM, "evaluate", 4, "Applications",
          "Weigh environmental and technical points.", DEFAULT_STEPS,
          "Wind turbines generate a.c. using electromagnetic induction with low operating emissions, supporting low-carbon electricity. However, output is variable, turbines require maintenance, and grid infrastructure must handle fluctuating supply. Overall they reduce fossil fuel use where wind resource is good.", ["Induction used to generate electricity.", "Low carbon advantage.", "Variability or maintenance limitation.", "Judgement."],
          ["No link to electromagnetism.", "One-sided."], "Link physics principle to real energy debate."),
        q("A wire of length 0.35 m carries a current of 2.0 A at right angles to a magnetic field of flux density 0.40 T. Calculate the force on the wire.", TOPIC_MAGNETISM, "calculate", 6, "Motor effect calculation",
          "Use F = BIl.", ["Write F = BIl.", "All quantities at right angles.", "Multiply.", "Unit N.", "Show working.", "State answer."],
          "F = 0.40 × 2.0 × 0.35 = 0.28 N.", ["F = BIl.", "Substitution.", "0.28 N.", "Unit N.", "Working.", "Right-angle condition noted."],
          ["Missing length.", "Wrong unit T only."], "Force zero if wire parallel to field."),
        calc_q("The primary coil of a transformer has 800 turns and the secondary has 40 turns. If the primary voltage is 240 V, calculate the secondary voltage.", TOPIC_MAGNETISM, 3,
          "Use turns ratio.", ["Vs/Vp = Ns/Np.", "Substitute.", "Answer in V."],
          "Vs = 240 × 40/800 = 12 V.", ["Correct ratio.", "Substitution.", "12 V."],
          ["Multiplying by 800/40 incorrectly inverted."], "Fewer secondary turns → step-down."),
        q("Describe how you would investigate the force on a current-carrying wire in a magnetic field using a top pan balance and wire on a pivot.", TOPIC_MAGNETISM, "describe", 4, "Required practical skills",
          "Describe measuring force change when current switched on.", DEFAULT_STEPS,
          "Place magnet on balance with wire between poles horizontal at right angles. Zero balance with current off. Switch on current, record balance reading change equal to force on wire. Repeat for different currents, plot force against current.", ["Wire perpendicular to field.", "Balance measures force change.", "Vary current.", "Repeat and graph."],
          ["Wire parallel to field.", "No repeat readings."], "Motor effect practical: F increases with current."),
    ]


def _space_questions() -> list[dict]:
    return [
        q("State what provides the centripetal force on a planet orbiting the Sun.", TOPIC_SPACE, "state", 1, "Orbits",
          "Identify force keeping planet in orbit.", DEFAULT_STEPS, "Gravitational force (gravity) from the Sun.", ["Gravitational force / gravity."],
          ["Magnetic force.", "Air resistance."], "Orbits: gravity provides centripetal force."),
        q("Give the name of our galaxy.", TOPIC_SPACE, "give", 1, "Astronomy", "Name the Milky Way.", DEFAULT_STEPS, "The Milky Way.", ["Milky Way."], ["Andromeda.", "Solar System."], "Solar System is within the Milky Way."),
        q("State what is meant by a light-year.", TOPIC_SPACE, "state", 1, "Distances",
          "Define light-year.", DEFAULT_STEPS, "A light-year is the distance light travels in one year in a vacuum.", ["Distance light travels in one year."],
          ["Time light takes to travel.", "Unit of speed."], "Light-year is distance, not time."),
        q("Describe the life cycle of a star similar in mass to the Sun.", TOPIC_SPACE, "describe", 2, "Stellar life cycle",
          "Outline main stages.", DEFAULT_STEPS,
          "Nebula collapses to form a main sequence star where hydrogen fuses to helium. Later it becomes a red giant, then sheds outer layers forming a planetary nebula, leaving a white dwarf.", ["Nebula to main sequence.", "Red giant stage.", "White dwarf end point."],
          ["Supernova for Sun-like star.", "Black hole ending."], "Sun-like stars do not become supernovae."),
        q("Explain why fusion in stars releases energy.", TOPIC_SPACE, "explain", 2, "Fusion",
          "Link mass defect to energy release.", DEFAULT_STEPS,
          "Fusion combines light nuclei; the mass of the product nucleus is slightly less than the sum of original nuclei. The mass difference is converted to energy according to E = mc².", ["Light nuclei fuse.", "Mass decreases.", "Energy released via E = mc²."],
          ["Energy created without mass change.", "Fission described instead."], "Fusion needs very high temperature and pressure."),
        q("Compare geostationary and low Earth orbit satellites.", TOPIC_SPACE, "compare", 2, "Satellites",
          "Compare orbit height and period uses.", DEFAULT_STEPS,
          "Geostationary orbit is at about 36 000 km above the equator with orbital period 24 hours, used for communications. Low Earth orbit is much closer (hundreds of km) with shorter period, used for imaging and ISS.", ["Geostationary period 24 h / comms.", "LEO closer / shorter period / imaging.", "Both valid differences."],
          ["Same height.", "Only one orbit described."], "Geostationary: fixed above equator."),
        q("Explain why the Universe is expanding using evidence from distant galaxies.", TOPIC_SPACE, "explain", 3, "Red-shift",
          "Link red-shift to recession.", DEFAULT_STEPS,
          "Light from distant galaxies shows red-shift, meaning wavelengths are stretched as galaxies move away from us. More distant galaxies have greater red-shift, showing faster recession and supporting expansion of the Universe.", ["Red-shift observed.", "Galaxies moving away.", "More distant → greater red-shift → faster recession."],
          ["Blue-shift for all.", "Stars not galaxies."], "Hubble's law: recession speed increases with distance."),
        q("Describe how the change in wavelength of light from a galaxy can be measured.", TOPIC_SPACE, "describe", 3, "Red-shift measurement",
          "Describe spectrum comparison.", DEFAULT_STEPS,
          "Split galaxy light into a spectrum using a diffraction grating or prism. Compare observed absorption lines with known laboratory wavelengths. The shift toward longer wavelength (red end) indicates red-shift.", ["Spectrum obtained.", "Known line positions compared.", "Shift to longer wavelength measured."],
          ["Measuring brightness only.", "No reference to spectral lines."], "Spectral line patterns act as fingerprints."),
        q("Evaluate using space telescopes compared with ground-based telescopes.", TOPIC_SPACE, "evaluate", 4, "Observing universe",
          "Weigh advantages and limitations.", DEFAULT_STEPS,
          "Space telescopes avoid atmospheric absorption and turbulence, observing clearer infrared/UV that does not reach ground. They are expensive, hard to maintain, and have limited lifetime. Ground telescopes are cheaper and easier to upgrade but affected by weather and atmosphere.", ["Space: no atmosphere distortion.", "Space: broader EM range.", "Ground: cheaper/easier access.", "Overall judgement."],
          ["Space telescopes always cheaper.", "No atmospheric issue mentioned."], "Hubble and JWST examples of space advantage."),
        q("A galaxy recedes at 2.4 × 10⁶ m/s. The speed of light is 3.0 × 10⁸ m/s. Calculate the red-shift z if defined as Δλ/λ = v/c for non-relativistic speeds.", TOPIC_SPACE, "calculate", 4, "Red-shift calculation",
          "Use z = v/c.", ["Write z = v/c.", "Substitute.", "No unit for z."],
          "z = 2.4×10⁶ ÷ 3.0×10⁸ = 0.008.", ["z = v/c.", "Substitution.", "0.008.", "Correct decimal."],
          ["Multiplying v and c.", "Unit m/s on z."], "Red-shift z is a ratio — no unit."),
        q("Describe how observations of supernovae in distant galaxies provide evidence for the accelerating expansion of the Universe.", TOPIC_SPACE, "describe", 6, "Cosmology",
          "Link brightness distance to expansion rate change.", DEFAULT_STEPS,
          "Type Ia supernovae have known intrinsic brightness so distance can be estimated. Observed brightness compared to red-shift distance shows galaxies farther than expected for a given red-shift, implying expansion is accelerating. Dark energy is suggested to explain this.", ["Supernova standard candle idea.", "Distance from brightness.", "Compared with red-shift.", "Expansion accelerating conclusion.", "Dark energy mention optional extension.", "Coherent account."],
          ["Supernova causes expansion.", "No link to brightness and distance."], "Standard candles allow distance comparison."),
        calc_q("Light from the Sun takes 8.3 minutes to reach Earth. Speed of light is 3.0 × 10⁸ m/s. Calculate the distance from the Sun to Earth.", TOPIC_SPACE, 3,
          "Use d = vt with time in seconds.", ["Convert 8.3 min to seconds.", "d = vt.", "Answer in m or km."],
          "t = 8.3 × 60 = 498 s. d = 3.0×10⁸ × 498 = 1.49×10¹¹ m (about 150 million km).", ["Time in seconds.", "d = vt.", "Correct order of magnitude."],
          ["Using minutes directly.", "Wrong speed."], "Astronomy distances often given in metres or km."),
        q(
            "Describe how you would use published orbital data and the equation speed = distance ÷ time to estimate the radius of a geostationary satellite orbit.",
            TOPIC_SPACE,
            "describe",
            4,
            "Required practical skills",
            "Describe data sources and calculation steps for an orbital estimate.",
            DEFAULT_STEPS,
            "Look up the orbital period of a geostationary satellite (24 hours) and its orbital speed from a reliable data source. Convert period to seconds, calculate orbital circumference using speed × time, then radius using circumference = 2πr. Compare with textbook value to assess accuracy.",
            [
                "Orbital period and speed obtained from data.",
                "Circumference calculated from speed × time.",
                "Radius found from C = 2πr.",
                "Comparison or repeat/check mentioned.",
            ],
            ["Using period in hours without conversion.", "Confusing radius with diameter."],
            "Geostationary orbit period matches Earth's rotation: about 24 hours.",
        ),
    ]


def _practical_skills_questions() -> list[dict]:
    return [
        q("State what is meant by an independent variable.", TOPIC_PRACTICAL, "state", 1, "Working scientifically",
          "Define independent variable.", DEFAULT_STEPS, "The independent variable is the one deliberately changed by the experimenter.", ["Variable changed deliberately."],
          ["Variable measured.", "Variable kept constant."], "Independent = you change it."),
        q("Give one hazard associated with using a mains immersion heater in a density or SHC practical.", TOPIC_PRACTICAL, "give", 1, "Safety",
          "Name a hazard.", DEFAULT_STEPS, "Risk of electric shock or burns from hot water/heater.", ["Electric shock or burns/scalds."],
          ["Paper cut.", "Radiation poisoning from heater."], "Link hazard to control: RCD, keep dry."),
        q("State why repeat readings are taken in physics investigations.", TOPIC_PRACTICAL, "state", 1, "Data quality",
          "State purpose of repeats.", DEFAULT_STEPS, "To identify anomalies and calculate a mean, improving reliability.", ["Identify anomalies and/or calculate mean.", "Improve reliability."],
          ["To change independent variable.", "To make results bigger."], "Reliability improves with repeats and means."),
        q("Describe how to identify an anomalous result in a set of repeat measurements.", TOPIC_PRACTICAL, "describe", 2, "Data analysis",
          "Describe comparison with other repeats.", DEFAULT_STEPS,
          "Compare each repeat to others. A result that is very different from the others at the same conditions is anomalous and should be excluded before calculating the mean.", ["Compare repeats.", "Very different value identified as anomaly.", "Exclude before mean."],
          ["Remove highest value always.", "Never exclude data."], "Do not delete without justification."),
        q("Explain why a line of best fit is drawn for linear relationships.", TOPIC_PRACTICAL, "explain", 2, "Graphs",
          "Explain averaging scatter.", DEFAULT_STEPS,
          "Experimental points include random error scatter. A line of best fit shows the overall trend by balancing points above and below the line, giving a more reliable relationship than joining dot-to-dot.", ["Shows overall trend.", "Accounts for scatter/random error.", "More reliable than dot-to-dot."],
          ["Joins every point exactly.", "Removes systematic error automatically."], "Line of best fit: roughly equal points above/below."),
        q("Compare systematic errors and random errors.", TOPIC_PRACTICAL, "compare", 2, "Errors",
          "Compare causes and effects.", DEFAULT_STEPS,
          "Random errors cause scatter around the true value and are reduced by repeats and mean. Systematic errors shift all readings consistently, such as zero error on a balance, and are not removed by averaging.", ["Random: scatter, reduced by repeats.", "Systematic: consistent shift, e.g. zero error.", "Contrast clear."],
          ["Same definition for both.", "Only random described."], "Systematic affects accuracy; random affects precision."),
        q("Describe how to calculate a mean value from five repeat readings.", TOPIC_PRACTICAL, "describe", 3, "Processing data",
          "Describe summing and dividing.", DEFAULT_STEPS,
          "Add the five values together and divide by five. If an anomaly was identified, exclude it first, note reduced number of readings, and divide by the number remaining.", ["Sum values.", "Divide by number of readings.", "Anomaly exclusion if appropriate."],
          ["Multiply readings.", "Divide by highest."], "Mean = total ÷ number."),
        q("Explain why calibration improves measurement accuracy.", TOPIC_PRACTICAL, "explain", 3, "Equipment",
          "Link calibration to true values.", DEFAULT_STEPS,
          "Calibration compares instrument readings to known standards and adjusts for systematic error so readings match true values more closely, improving accuracy.", ["Compares to known standard.", "Corrects systematic error.", "Improves accuracy."],
          ["Increases random scatter.", "Removes need for repeats."], "Accuracy = closeness to true value."),
        q("Evaluate using digital data loggers instead of manual stopwatches for timing oscillations.", TOPIC_PRACTICAL, "evaluate", 4, "Equipment choice",
          "Weigh precision and practical issues.", DEFAULT_STEPS,
            "Data loggers record at high frequency with less reaction time error, improving precision for fast events. However, they cost more, need setup, and may introduce software delays if poorly configured. Overall better for short or rapid events.", ["Logger reduces reaction time error.", "Higher sampling rate.", "Cost/setup limitation.", "Judgement for oscillations."],
          ["Stopwatch always better.", "No reaction time issue mentioned."], "Reaction time ~0.2 s limits stopwatches."),
        q("Describe how to estimate uncertainty when measuring the length of a wire with a metre rule to the nearest millimetre.", TOPIC_PRACTICAL, "describe", 4, "Uncertainty",
          "Describe half smallest division.", DEFAULT_STEPS,
            "The smallest division is 1 mm so each reading has uncertainty of ±0.5 mm. For a single measurement report length ±0.5 mm; for a mean from repeats, uncertainty can be reduced but instrument uncertainty remains at least ±0.5 mm unless finer instrument used.", ["± half smallest division.", "1 mm scale → ±0.5 mm.", "Apply to wire length.", "Link to reporting."],
          ["±1 mm always without justification.", "No reference to scale."], "Resolution determines minimum uncertainty."),
        q("Plan an investigation to test whether the period of a pendulum depends on its mass. Describe independent variable, dependent variable, controls, equipment, and expected graph.", TOPIC_PRACTICAL, "describe", 6, "Planning investigations",
          "Full plan with variables and method.", DEFAULT_STEPS,
          "Independent variable: mass of bob. Dependent variable: period T measured for 10 oscillations divided by 10. Control: length, amplitude (<10°), same gravitational field. Equipment: clamp stand, string, masses, stopwatch/ruler. Expect period independent of mass — horizontal trend on T vs mass graph within scatter.", ["IV mass, DV period.", "Controls: length, amplitude.", "Method for measuring T.", "Equipment listed.", "Expected graph/trend.", "Coherent plan."],
          ["Length as IV when question asks mass.", "No controls."], "Period formula T = 2π√(l/g) — no mass term."),
        calc_q("A student measures wire length five times (cm): 98.2, 98.5, 98.4, 98.3, 98.4. Calculate the mean length.", TOPIC_PRACTICAL, 3,
          "Sum and divide.", ["Add five values.", "Divide by 5.", "Unit cm."],
          "Mean = (98.2+98.5+98.4+98.3+98.4)/5 = 491.8/5 = 98.4 cm.", ["Sum correct.", "Divide by 5.", "98.4 cm."],
          ["Using median without instruction.", "Wrong denominator."], "Show addition then division in working."),
        q("Describe how you would safely investigate the resistance of a thermistor at different temperatures using a water bath, thermometer, and circuit.", TOPIC_PRACTICAL, "describe", 4, "Required practical skills",
          "Describe varying temperature and measuring R.", DEFAULT_STEPS,
          "Connect thermistor in series with ammeter and supply, voltmeter in parallel. Place in water bath with thermometer. Heat bath, record temperature, current, and p.d. at intervals, calculate R = V/I each time. Keep other variables constant, plot R against temperature.", ["R = V/I at each temperature.", "Water bath and thermometer.", "Safety: dry hands, low voltage, support beaker.", "Graph R vs T."],
          ["No thermometer.", "Measuring resistance without V and I."], "Thermistor R decreases with temperature for NTC type — note in conclusion."),
    ]


def _calculations() -> list[dict]:
    return [
        {
            "title": "Gravitational potential energy",
            "question": "A 3.5 kg mass is lifted through 2.0 m. Calculate the change in gravitational potential energy. Use g = 9.8 N/kg.",
            "formula": "Ep = mgh",
            "rearrange": "Ep is already subject of formula",
            "substitution": "Ep = 3.5 × 9.8 × 2.0",
            "working": "Ep = 68.6 J",
            "answer": "69 J (2 s.f.) or 68.6 J",
            "note": "Use mass in kg, height in m, g in N/kg.",
        },
        {
            "title": "Kinetic energy",
            "question": "Calculate the kinetic energy of a 1200 kg car travelling at 15 m/s.",
            "formula": "Ek = ½mv²",
            "rearrange": "Ek is subject",
            "substitution": "Ek = 0.5 × 1200 × 15²",
            "working": "Ek = 0.5 × 1200 × 225 = 135 000 J",
            "answer": "135 000 J or 1.35 × 10⁵ J",
            "note": "Remember to square the speed only.",
        },
        {
            "title": "Power",
            "question": "A kettle transfers 180 000 J in 60 s. Calculate its power.",
            "formula": "P = E/t",
            "rearrange": "P is subject",
            "substitution": "P = 180 000 ÷ 60",
            "working": "P = 3000 W",
            "answer": "3000 W or 3.0 kW",
            "note": "Power in watts when energy is in joules and time in seconds.",
        },
        {
            "title": "Charge flow",
            "question": "A current of 0.25 A flows for 4 minutes. Calculate the charge flow.",
            "formula": "Q = It",
            "rearrange": "Q is subject",
            "substitution": "t = 240 s; Q = 0.25 × 240",
            "working": "Q = 60 C",
            "answer": "60 C",
            "note": "Convert minutes to seconds before substituting.",
        },
        {
            "title": "Potential difference and resistance",
            "question": "A resistor of 25 Ω has a current of 0.40 A. Calculate the potential difference across it.",
            "formula": "V = IR",
            "rearrange": "V is subject",
            "substitution": "V = 0.40 × 25",
            "working": "V = 10 V",
            "answer": "10 V",
            "note": "Ohm's law: V, I, R must be in volts, amps, ohms.",
        },
        {
            "title": "Density",
            "question": "An object has mass 2.4 kg and volume 0.0030 m³. Calculate its density.",
            "formula": "ρ = m/V",
            "rearrange": "ρ is subject",
            "substitution": "ρ = 2.4 ÷ 0.0030",
            "working": "ρ = 800 kg/m³",
            "answer": "800 kg/m³",
            "note": "Density connects mass and volume — check units match.",
        },
        {
            "title": "Specific heat capacity",
            "question": "How much energy is needed to heat 0.50 kg of water from 20 °C to 50 °C? Specific heat capacity of water = 4200 J/kg °C.",
            "formula": "E = mcΔT",
            "rearrange": "E is subject; ΔT = 30 °C",
            "substitution": "E = 0.50 × 4200 × 30",
            "working": "E = 63 000 J",
            "answer": "63 000 J or 6.3 × 10⁴ J",
            "note": "Use temperature change, not final temperature alone.",
        },
        {
            "title": "Resultant force and acceleration",
            "question": "Calculate the acceleration of a 950 kg car when the resultant force is 1900 N.",
            "formula": "F = ma",
            "rearrange": "a = F/m",
            "substitution": "a = 1900 ÷ 950",
            "working": "a = 2.0 m/s²",
            "answer": "2.0 m/s²",
            "note": "Resultant force determines acceleration.",
        },
        {
            "title": "Momentum",
            "question": "Calculate the momentum of a 0.20 kg ball moving at 25 m/s.",
            "formula": "p = mv",
            "rearrange": "p is subject",
            "substitution": "p = 0.20 × 25",
            "working": "p = 5.0 kg m/s",
            "answer": "5.0 kg m/s",
            "note": "Momentum is a vector; include direction in full problems.",
        },
        {
            "title": "Wave speed",
            "question": "A wave has frequency 50 Hz and wavelength 6.0 m. Calculate wave speed.",
            "formula": "v = fλ",
            "rearrange": "v is subject",
            "substitution": "v = 50 × 6.0",
            "working": "v = 300 m/s",
            "answer": "300 m/s",
            "note": "Applies to all waves including electromagnetic waves.",
        },
        {
            "title": "Transformer turns ratio",
            "question": "A transformer has 1200 primary turns and 120 secondary turns. The primary p.d. is 240 V. Calculate the secondary p.d.",
            "formula": "Vs/Vp = Ns/Np",
            "rearrange": "Vs = Vp × Ns/Np",
            "substitution": "Vs = 240 × 120/1200",
            "working": "Vs = 24 V",
            "answer": "24 V",
            "note": "Step-down transformer: fewer secondary turns → lower voltage.",
        },
    ]


def _practicals() -> list[dict]:
    return [
        {
            "title": "Investigating the resistance of a wire",
            "aim": "To determine how the resistance of a wire depends on its length.",
            "variables": "Independent: length of wire. Dependent: resistance (calculated from V and I). Control: material, diameter, temperature.",
            "method": "Connect a length of constantan wire in series with ammeter, switch, and low-voltage supply. Connect voltmeter in parallel with the wire. Measure length with metre rule. Record I and V, calculate R = V/I. Repeat for different lengths with same thickness and material.",
            "risk": "Wire may become hot if current too high — use low voltage and short bursts. Ensure connections secure to prevent short circuit. Eye protection if tensioned wire could snap.",
            "results": "Table columns: length/m, current/A, potential difference/V, resistance/Ω. Take repeat R for each length and calculate mean.",
            "graph": "Plot mean resistance (y) against length (x). Expect straight line through origin if R proportional to length.",
            "conclusion": "Resistance increases proportionally with length because longer wire provides more resistance to charge flow.",
            "evaluation": "Random error from reading metres and meters — use repeats. Systematic error if contact resistance at crocodile clips — minimise by same clip positions. Improve by using thicker wire to reduce heating or use data logger.",
            "exam_questions": [
                "Why must only length be changed?",
                "How is resistance calculated from measurements?",
                "What graph shape shows R ∝ L?",
            ],
            "model_answers": [
                "So the relationship between length and resistance is isolated; other factors affect R.",
                "Measure V and I, then R = V/I for each length.",
                "Straight line through origin on R vs length graph.",
            ],
        },
        {
            "title": "Measuring the density of a regular solid",
            "aim": "To measure the density of a regular wooden block using a balance and ruler.",
            "variables": "Independent: object (block). Dependent: density ρ = m/V. Measure mass and dimensions.",
            "method": "Measure mass on balance. Measure length, width, height with ruler at several points, calculate mean dimensions. Volume V = lwh. Calculate ρ = m/V. Repeat entire procedure.",
            "risk": "Ruler edges may slip — clamp block if needed. Balance is precision equipment — avoid spills.",
            "results": "Record mass/kg, length/m, width/m, height/m, volume/m³, density/kg m⁻³. Include repeats and mean.",
            "graph": "Optional bar chart comparing mean density to textbook value for material.",
            "conclusion": "Compare calculated density to known value for wood (~500–800 kg/m³ depending on type). Percentage difference estimates accuracy.",
            "evaluation": "Uncertainty in ruler ±0.5 mm affects volume. Improve using vernier calipers/micrometer. Irregular objects need displacement can method.",
            "exam_questions": [
                "Why measure dimensions at several places?",
                "How would you find density of an irregular stone?",
                "Why include units in the density answer?",
            ],
            "model_answers": [
                "Block may not be perfectly uniform; mean dimensions improve reliability.",
                "Use displacement can/eureka can to find volume, mass on balance, ρ = m/V.",
                "Density has units (kg/m³) — values meaningless without them.",
            ],
        },
    ]


def _mini_mock() -> dict:
    questions = [
        {"text": "State the unit of power.", "marks": 1},
        {"text": "Give one non-renewable energy resource.", "marks": 1},
        {"text": "Describe the difference between series and parallel circuits.", "marks": 4},
        {"text": "Explain why metals conduct electricity.", "marks": 2},
        {"text": "A 5.0 Ω resistor is connected to 10 V. Calculate the current.", "marks": 2},
        {"text": "Explain why insulating a loft reduces energy wasted from a house.", "marks": 3},
        {"text": "Describe the particle arrangement in a gas.", "marks": 3},
        {"text": "Compare alpha and gamma radiation in terms of ionisation and penetration.", "marks": 4},
        {"text": "A 2.0 kg object falls at terminal velocity. Explain the forces acting.", "marks": 4},
        {"text": "Calculate the wave speed of a 40 Hz wave with wavelength 8.5 m.", "marks": 3},
        {"text": "Describe how a step-up transformer helps reduce energy loss in National Grid cables.", "marks": 4},
        {"text": "Evaluate the use of nuclear power for generating electricity.", "marks": 6},
        {"text": "A 800 W kettle is used for 3 minutes. Calculate energy transferred.", "marks": 3},
        {"text": "Describe how you would measure the density of an irregular object.", "marks": 4},
        {"text": "A car of mass 1000 kg changes velocity from 10 m/s to 25 m/s in 5.0 s. Calculate resultant force.", "marks": 6},
    ]
    answers = [
        {"walkthrough": "Power is measured in watts (W).", "marks_breakdown": ["Watt or W."]},
        {"walkthrough": "Any fossil fuel or nuclear, e.g. natural gas or uranium fuel.", "marks_breakdown": ["Valid non-renewable named."]},
        {"walkthrough": "In series, components share one path so current is the same everywhere and potential differences add up. In parallel, each branch has the same p.d. across it and the total current splits between branches.", "marks_breakdown": ["Series: one path / same current.", "Series: p.d.s shared/add.", "Parallel: same p.d. per branch.", "Parallel: current splits."]},
        {"walkthrough": "Metals contain delocalised electrons that move when a p.d. is applied, carrying charge as electric current.", "marks_breakdown": ["Delocalised electrons.", "Move to carry charge/current."]},
        {"walkthrough": "I = V/R = 10/5.0 = 2.0 A.", "marks_breakdown": ["V = IR rearranged.", "2.0 A with unit."]},
        {"walkthrough": "Insulation reduces thermal energy transfer through the roof by conduction/convection/radiation. Less energy leaves so less fuel/electricity is needed to replace it.", "marks_breakdown": ["Reduces energy transfer out.", "Less energy input needed.", "Lower waste/cost linked."]},
        {"walkthrough": "Gas particles are far apart, move randomly at high speed, and collide with container walls.", "marks_breakdown": ["Far apart.", "Random motion.", "Collisions with walls."]},
        {"walkthrough": "Alpha is highly ionising but stopped by paper/skin; gamma is weakly ionising but penetrates thick lead. Alpha dangerous if ingested; gamma external hazard.", "marks_breakdown": ["Alpha ionisation high.", "Alpha penetration low.", "Gamma ionisation lower.", "Gamma penetration high."]},
        {"walkthrough": "Weight acts downward. Air resistance increases with speed until equals weight. Resultant force zero so velocity constant.", "marks_breakdown": ["Weight downward.", "Drag increases.", "Forces balance.", "Constant velocity."]},
        {"walkthrough": "v = fλ = 40 × 8.5 = 340 m/s.", "marks_breakdown": ["v = fλ.", "Substitution.", "340 m/s."]},
        {"walkthrough": "Step-up increases voltage so current is lower for same power. Lower current reduces I²R heating losses in cables.", "marks_breakdown": ["Increases voltage.", "Lower current.", "Less I²R loss.", "Clear link."]},
        {"walkthrough": "Fission gives large energy and low CO₂ in operation but produces radioactive waste and accident risk. Reliable baseload. Overall low-carbon if waste managed.", "marks_breakdown": ["Advantage: energy/low CO₂.", "Disadvantage: waste/risk.", "Reliability.", "Further balanced point.", "Judgement.", "Coherent evaluation."]},
        {"walkthrough": "t = 180 s. E = Pt = 800 × 180 = 144 000 J.", "marks_breakdown": ["Time in seconds.", "E = Pt.", "144 000 J."]},
        {"walkthrough": "Mass on balance. Volume by measuring cylinder/displacement can. ρ = m/V with repeats and mean.", "marks_breakdown": ["Mass measured.", "Volume by displacement.", "ρ = m/V.", "Repeats/mean."]},
        {"walkthrough": "a = (25−10)/5.0 = 3.0 m/s². F = ma = 1000 × 3.0 = 3000 N.", "marks_breakdown": ["a = 3.0 m/s².", "F = ma.", "m correct.", "3000 N.", "Unit N.", "Working shown."]},
    ]
    total = sum(q["marks"] for q in questions)
    return {"total_marks": total, "questions": questions, "answers": answers}


def build_pack() -> dict:
    """Return the complete GCSE Physics walkthrough pack content."""
    return {
        "subject": "Physics",
        "slug": "physics",
        "topics": [
            topic_pack(TOPIC_ENERGY, _energy_questions()),
            topic_pack(TOPIC_ELECTRICITY, _electricity_questions()),
            topic_pack(TOPIC_PARTICLE, _particle_questions()),
            topic_pack(TOPIC_ATOMIC, _atomic_questions()),
            topic_pack(TOPIC_FORCES, _forces_questions()),
            topic_pack(TOPIC_WAVES, _waves_questions()),
            topic_pack(TOPIC_MAGNETISM, _magnetism_questions()),
            topic_pack(TOPIC_SPACE, _space_questions()),
            topic_pack(TOPIC_PRACTICAL, _practical_skills_questions()),
        ],
        "calculations": _calculations(),
        "practicals": _practicals(),
        "mini_mock": _mini_mock(),
    }
