"""GCSE Biology exam walkthrough pack content — original JDScience exam-style questions."""

from __future__ import annotations

from .content_helpers import DEFAULT_STEPS, calc_q, q, topic_pack

T_CELL = "Cell biology"
T_ORG = "Organisation"
T_INFECTION = "Infection and response"
T_BIOENER = "Bioenergetics"
T_HOME = "Homeostasis and response"
T_INHERIT = "Inheritance, variation and evolution"
T_ECOLOGY = "Ecology"
T_PRACTICAL = "Required practical skills"


def _q1(text, topic, command, skill, asking, model, mistakes, tip, extension=None):
    return q(text, topic, command, 1, skill, asking, DEFAULT_STEPS, model, [model], mistakes, tip, extension)


def _q2(text, topic, command, skill, asking, model, marks_breakdown, mistakes, tip, extension=None):
    return q(text, topic, command, 2, skill, asking, DEFAULT_STEPS, model, marks_breakdown, mistakes, tip, extension)


def _q3(text, topic, command, skill, asking, model, marks_breakdown, mistakes, tip, extension=None):
    return q(text, topic, command, 3, skill, asking, DEFAULT_STEPS, model, marks_breakdown, mistakes, tip, extension)


def _q4(text, topic, command, skill, asking, model, marks_breakdown, mistakes, tip, extension=None):
    return q(text, topic, command, 4, skill, asking, DEFAULT_STEPS, model, marks_breakdown, mistakes, tip, extension)


def _q6(text, topic, command, skill, asking, model, marks_breakdown, mistakes, tip, extension=None):
    return q(text, topic, command, 6, skill, asking, DEFAULT_STEPS, model, marks_breakdown, mistakes, tip, extension)


def _cell_biology() -> list[dict]:
    return [
        _q1(
            "Name the organelle that controls the activities of the cell.",
            T_CELL, "state", "Cell structure",
            "Identify the control centre of the cell.",
            "The nucleus.",
            ["Writing mitochondrion.", "Giving a description instead of a name."],
            "For one-mark recall, give a single precise term.",
        ),
        _q1(
            "State the function of ribosomes.",
            T_CELL, "state", "Cell structure",
            "State what ribosomes do.",
            "Protein synthesis.",
            ["Saying respiration.", "Saying they make DNA."],
            "Link ribosomes to proteins, not energy.",
        ),
        _q1(
            "Give the name of the structure that makes a plant cell rigid.",
            T_CELL, "give", "Plant cells",
            "Name the plant cell wall component.",
            "Cell wall (made of cellulose).",
            ["Saying membrane.", "Saying vacuole."],
            "Cell wall is outside the membrane in plant cells.",
        ),
        _q2(
            "Describe two differences between a prokaryotic cell and a eukaryotic cell.",
            T_CELL, "describe", "Cell types",
            "Compare prokaryotes and eukaryotes structurally.",
            "Prokaryotic cells have no nucleus — DNA is free in the cytoplasm — and are smaller. Eukaryotic cells have a membrane-bound nucleus and membrane-bound organelles.",
            ["One valid structural difference.", "Second valid structural difference."],
            ["Only describing one type.", "Stating functions without structural differences."],
            "Nucleus presence and size are reliable two-mark pairs.",
        ),
        _q2(
            "Explain why root hair cells have many mitochondria.",
            T_CELL, "explain", "Specialised cells",
            "Link structure to function for active transport.",
            "Root hair cells absorb mineral ions by active transport, which requires ATP from aerobic respiration in mitochondria.",
            ["Active transport or ion uptake mentioned.", "Link to ATP or respiration in mitochondria."],
            ["Saying photosynthesis.", "Not linking mitochondria to energy need."],
            "Always connect organelle to the process that needs energy.",
        ),
        _q2(
            "Compare diffusion and osmosis.",
            T_CELL, "compare", "Transport",
            "State a similarity and a difference.",
            "Both involve passive movement down a concentration gradient without energy. Diffusion can involve any particle; osmosis is the movement of water only across a partially permeable membrane.",
            ["Valid similarity.", "Valid difference about water or membrane."],
            ["Saying osmosis needs energy.", "Not mentioning water specifically."],
            "Use 'both … however …' structure.",
        ),
        _q3(
            "Explain how the structure of the cell-surface membrane helps it control what enters and leaves the cell.",
            T_CELL, "explain", "Membranes",
            "Link phospholipid bilayer and proteins to selective permeability.",
            "The membrane is a phospholipid bilayer forming a barrier to many polar molecules. Embedded proteins act as channels or carriers for specific substances, so only selected ions and molecules can cross.",
            ["Phospholipid bilayer or barrier idea.", "Proteins as channels or carriers.", "Selective control of substances."],
            ["Calling the membrane fully permeable.", "Ignoring protein role."],
            "Mention both the lipid barrier and protein channels.",
        ),
        _q3(
            "Describe the stages of mitosis in order.",
            T_CELL, "describe", "Cell division",
            "Outline the sequence of mitosis.",
            "Chromosomes condense and become visible. They line up at the equator of the cell. Sister chromatids are pulled to opposite poles. Two genetically identical nuclei form before cytokinesis.",
            ["Condensation or visibility.", "Alignment at equator.", "Separation to poles and two nuclei."],
            ["Mixing mitosis with meiosis.", "Missing the order."],
            "Learn PMAT: prophase, metaphase, anaphase, telophase.",
        ),
        _q4(
            "A student claims plant cells cannot respire because they contain chloroplasts. Evaluate this statement.",
            T_CELL, "evaluate", "Metabolism",
            "Judge the claim using plant cell metabolism.",
            "The statement is incorrect. Chloroplasts carry out photosynthesis, but mitochondria in plant cells carry out aerobic respiration at all times, releasing ATP for growth and active transport. At night, when photosynthesis stops, respiration continues. Both processes occur in plant cells.",
            ["Statement judged incorrect.", "Photosynthesis in chloroplasts stated.", "Respiration in mitochondria stated.", "Balanced conclusion with day/night or both organelles."],
            ["Agreeing with the student.", "Saying plants only photosynthesise."],
            "Plants respire continuously; they photosynthesise only in light.",
        ),
        _q4(
            "Explain why multicellular organisms need specialised cells and differentiation.",
            T_CELL, "explain", "Specialisation",
            "Link specialisation to efficiency in large organisms.",
            "Differentiation produces cells with specific structures for particular jobs, such as muscle cells for contraction or red blood cells for oxygen transport. This division of labour is more efficient than every cell performing every function, allowing complex tissues and organs to form.",
            ["Differentiation defined or implied.", "Example of specialised cell.", "Division of labour idea.", "Efficiency or complexity benefit."],
            ["Confusing with evolution.", "No example given."],
            "Give one named specialised cell as evidence.",
        ),
        _q6(
            "Describe how you would prepare a microscope slide of onion epidermis and use it to estimate cell size. Include calibration, repeat measurements and how you would improve reliability.",
            T_CELL, "describe", "Microscopy",
            "Full microscopy method with size calculation and evaluation.",
            "Peel a thin layer of epidermis from an onion, place on a slide with a drop of iodine stain and a coverslip, avoiding air bubbles. View under low then high power, focusing with fine adjustment. Calibrate an eyepiece graticule against a stage micrometer to measure cell length. Repeat measurements on ten cells and calculate a mean. To improve reliability, repeat with a second onion bulb and use the same magnification each time.",
            ["Valid slide preparation.", "Microscope use including focusing.", "Graticule or micrometer calibration.", "Repeat measurements and mean.", "Reliability improvement.", "Clear logical sequence."],
            ["No stain or coverslip.", "Skipping calibration.", "No repeat or mean."],
            "Six-mark practical answers need method, measurement and improvement.",
            "Reference eyepiece × objective = total magnification.",
        ),
        calc_q(
            "An electron micrograph shows a mitochondrion 8 mm long. The actual length is 4 µm. Calculate the magnification. Show your working.",
            T_CELL, 3,
            "Use magnification = image size ÷ actual size with consistent units.",
            DEFAULT_STEPS,
            "Magnification = image size ÷ actual size = 8 mm ÷ 0.004 mm = ×2000.",
            ["Correct formula stated.", "Unit conversion (4 µm = 0.004 mm).", "Correct final magnification."],
            ["Not converting µm to mm.", "Dividing actual by image."],
            "Convert both measurements to the same unit before dividing.",
        ),
        _q4(
            "During a required practical on osmosis in potato cylinders, describe how you would identify the independent, dependent and control variables, and one source of random error.",
            T_CELL, "describe", "Required practical — osmosis",
            "Apply variables framework to osmosis investigation.",
            "Independent variable: concentration of sugar solution. Dependent variable: change in mass or length of potato cylinders. Control variables: same potato, same cylinder dimensions, same immersion time and temperature. A random error is slight variation in initial mass due to different water content in different parts of the potato.",
            ["Correct independent variable.", "Correct dependent variable.", "One control variable.", "Valid random error."],
            ["Swapping independent and dependent.", "Calling temperature independent when it should be controlled."],
            "What you change → independent; what you measure → dependent.",
        ),
    ]



def _organisation() -> list[dict]:
    return [
        _q1(
            "Name the organ that produces bile.",
            T_ORG, "state", "Digestive system",
            "Recall the source of bile.",
            "The liver.",
            ["Pancreas.", "Stomach."],
            "Bile is made in the liver and stored in the gall bladder.",
        ),
        _q1(
            "State the function of the alveoli in the lungs.",
            T_ORG, "state", "Gas exchange",
            "State what alveoli do.",
            "Gas exchange (oxygen into blood and carbon dioxide out).",
            ["Breathing only.", "Making mucus."],
            "Link alveoli to diffusion of gases.",
        ),
        _q1(
            "Give the name of the blood vessel that carries blood away from the heart.",
            T_ORG, "give", "Circulatory system",
            "Name the vessel type leaving the heart.",
            "Artery.",
            ["Vein.", "Capillary."],
            "Arteries carry blood away; veins carry blood towards the heart.",
        ),
        _q2(
            "Describe the function of xylem in a plant.",
            T_ORG, "describe", "Plant transport",
            "Explain water and mineral transport role.",
            "Xylem transports water and mineral ions from roots to leaves. It is made of dead hollow cells strengthened with lignin.",
            ["Transports water and minerals upward.", "Dead hollow cells or lignin mentioned."],
            ["Saying xylem carries sugars.", "Confusing with phloem."],
            "Xylem = water up; phloem = sugars both ways.",
        ),
        _q2(
            "Explain why the small intestine has a large surface area.",
            T_ORG, "explain", "Digestion",
            "Link villi and microvilli to absorption rate.",
            "A large surface area increases the rate of absorption of digested food molecules into the blood by diffusion and active transport.",
            ["Large surface area stated.", "Link to faster absorption or more diffusion."],
            ["Saying digestion happens faster only.", "No link to absorption."],
            "Surface area always links to rate of exchange.",
        ),
        _q2(
            "Compare arteries and veins.",
            T_ORG, "compare", "Circulatory system",
            "State one similarity and one difference.",
            "Both carry blood and have a lumen. Arteries have thick muscular walls and carry blood at high pressure away from the heart; veins have thinner walls, valves, and carry blood at lower pressure towards the heart.",
            ["Valid similarity.", "Valid difference in wall, pressure or direction."],
            ["Only describing arteries.", "Saying veins carry oxygenated blood only."],
            "Mention wall thickness or valves for a strong difference mark.",
        ),
        _q3(
            "Explain how the structure of a red blood cell is adapted to its function.",
            T_ORG, "explain", "Blood",
            "Link biconcave shape, haemoglobin and no nucleus to oxygen transport.",
            "Red blood cells have no nucleus to leave more room for haemoglobin, which binds oxygen. The biconcave shape increases surface area for faster diffusion of oxygen. They are small and flexible to pass through capillaries.",
            ["No nucleus or more haemoglobin.", "Haemoglobin binds oxygen.", "Biconcave shape increases surface area."],
            ["Saying they have a nucleus.", "Missing haemoglobin."],
            "Structure–function answers need named feature plus reason.",
        ),
        _q3(
            "Describe how enzymes work in digestion.",
            T_ORG, "describe", "Enzymes",
            "Outline lock-and-key and where enzymes act.",
            "Enzymes are biological catalysts with active sites shaped for specific substrates. Amylase in the mouth and small intestine breaks starch to sugars; proteases break proteins to amino acids; lipase breaks lipids to fatty acids and glycerol.",
            ["Enzyme–substrase specificity or active site.", "Named digestive enzyme and substrate.", "Products of digestion stated."],
            ["Saying enzymes are used up.", "No named enzyme."],
            "Name at least one enzyme, substrate and product.",
        ),
        _q4(
            "A patient has narrowed coronary arteries. Explain how this could affect the body.",
            T_ORG, "explain", "Disease",
            "Link reduced blood flow to heart muscle oxygen and respiration.",
            "Narrowed coronary arteries reduce blood flow to heart muscle. Less oxygen and glucose reach cardiac muscle cells, so aerobic respiration decreases and less ATP is available for contraction. This can cause chest pain or heart attack.",
            ["Reduced blood flow to heart muscle.", "Less oxygen or glucose.", "Less aerobic respiration or ATP.", "Effect on contraction or health."],
            ["Confusing with lung disease.", "No link to respiration."],
            "Follow the chain: artery → oxygen → respiration → muscle function.",
        ),
        _q4(
            "Describe how translocation occurs in plants.",
            T_ORG, "describe", "Plant transport",
            "Explain movement of sugars in phloem.",
            "Dissolved sugars are loaded into phloem sieve tubes in sources such as leaves. Water follows by osmosis, creating pressure that moves sap to sinks such as roots or fruits, where sugars are unloaded for storage or use.",
            ["Sugars in phloem.", "Source to sink direction.", "Osmosis or pressure flow idea.", "Unload at sink."],
            ["Saying xylem transports sugar.", "No source/sink idea."],
            "Phloem moves sugars; xylem moves water.",
        ),
        _q6(
            "Describe how you would investigate the effect of light intensity on the rate of transpiration using a potometer. Include variables, measurements and how to improve accuracy.",
            T_ORG, "describe", "Transpiration practical",
            "Full method for potometer investigation with evaluation.",
            "Cut a leafy shoot under water and attach to a filled potometer with no air bubbles. Measure distance the water meniscus moves in a set time at low light. Repeat at higher light intensity, keeping temperature and humidity constant. Calculate rate from distance ÷ time. Repeat entire setup and calculate mean. Improve accuracy by using a longer capillary tube for larger readings or a data logger.",
            ["Potometer set up without air bubbles.", "Light intensity changed.", "Rate calculated from distance and time.", "Control variables named.", "Repeat and mean.", "Accuracy improvement."],
            ["No time measurement.", "Changing temperature and light together."],
            "State what you measure and how you calculate rate.",
            "Link increased transpiration to faster water uptake at higher light.",
        ),
        calc_q(
            "A student calculates the mean length of five potato cylinders as 4.2 cm. The lengths are 4.0, 4.1, 4.3, 4.5 and 4.1 cm. Calculate the range.",
            T_ORG, 3,
            "Range = highest value − lowest value.",
            DEFAULT_STEPS,
            "Range = 4.5 − 4.0 = 0.5 cm.",
            ["Correct formula or method stated.", "Identifies highest and lowest.", "Range = 0.5 cm."],
            ["Using mean in the calculation.", "Wrong min or max."],
            "Range shows spread; it is not the mean.",
        ),
        _q4(
            "Describe how you would test a food sample for starch and for protein using standard reagents.",
            T_ORG, "describe", "Required practical — food tests",
            "Outline iodine and Biuret tests with positive results.",
            "Add a few drops of iodine solution to the sample; a blue-black colour indicates starch. For protein, add Biuret reagent and mix; a purple/lilac colour indicates protein. Use fresh samples and record colours against controls with no starch or protein.",
            ["Iodine test with blue-black for starch.", "Biuret test with purple for protein.", "Control or comparison mentioned.", "Clear method order."],
            ["Wrong colours.", "Using Benedict's for protein."],
            "Learn colour changes: iodine blue-black, Biuret purple.",
        ),
    ]


def _infection_and_response() -> list[dict]:
    return [
        _q1(
            "State what is meant by a pathogen.",
            T_INFECTION, "state", "Pathogens",
            "Define disease-causing organism.",
            "A microorganism that causes disease.",
            ["Any microbe regardless of harm.", "A toxin only."],
            "Pathogens cause infectious disease.",
        ),
        _q1(
            "Give one example of a bacterial disease.",
            T_INFECTION, "give", "Disease",
            "Name a disease caused by bacteria.",
            "Salmonella food poisoning (or tuberculosis, or gonorrhoea).",
            ["Naming a viral disease.", "Vague 'infection' without disease name."],
            "Have one bacterial and one viral example ready.",
        ),
        _q1(
            "Name the type of cell that engulfs pathogens as part of the immune response.",
            T_INFECTION, "state", "Immune system",
            "Identify phagocytes.",
            "White blood cell (phagocyte).",
            ["Red blood cell.", "Nerve cell."],
            "Phagocytes engulf and digest pathogens.",
        ),
        _q2(
            "Describe how the body prevents pathogens entering through the breathing system.",
            T_INFECTION, "describe", "Defences",
            "Mention mucus, cilia and nose hairs.",
            "Sticky mucus traps pathogens in the airways. Cilia beat to move mucus to the throat to be swallowed or coughed out. Hairs in the nose filter larger particles.",
            ["Mucus traps pathogens.", "Cilia move mucus away."],
            ["Only mentioning skin.", "Saying mucus kills all pathogens."],
            "First-line defences are non-specific barriers.",
        ),
        _q2(
            "Explain why antibiotics do not work against viral infections.",
            T_INFECTION, "explain", "Medicines",
            "Antibiotics target bacterial structures not found in viruses.",
            "Antibiotics work by interfering with bacterial cell walls or protein synthesis. Viruses reproduce inside host cells using host machinery and have no bacterial cell wall, so antibiotics cannot target them effectively.",
            ["Antibiotics target bacterial structures/processes.", "Viruses use host cells / lack bacterial targets."],
            ["Saying viruses are stronger.", "Claiming all medicines kill viruses."],
            "Antibiotics are for bacteria, not viruses.",
        ),
        _q2(
            "Compare active and passive immunity.",
            T_INFECTION, "compare", "Immunity",
            "State how each is acquired and duration.",
            "Active immunity is produced by the body after infection or vaccination and is often long-lasting. Passive immunity is provided by antibodies from another organism (e.g. breast milk or antiserum) and is short-term.",
            ["Active: body makes own antibodies.", "Passive: receives antibodies; short-term."],
            ["Saying passive immunity is permanent.", "No comparison of duration."],
            "Active = own antibodies; passive = borrowed antibodies.",
        ),
        _q3(
            "Explain how vaccination helps protect individuals and communities against disease.",
            T_INFECTION, "explain", "Vaccination",
            "Link memory cells and herd immunity.",
            "Vaccines contain harmless forms of antigens that stimulate white blood cells to produce antibodies and memory cells. On real infection, a faster secondary response prevents illness. High vaccination rates reduce pathogen spread, protecting those who cannot be vaccinated.",
            ["Vaccine stimulates antibodies and memory cells.", "Faster secondary response.", "Reduced spread or herd immunity."],
            ["Saying vaccines contain live pathogens always.", "No community benefit."],
            "Include both individual and population protection.",
        ),
        _q3(
            "Describe how monoclonal antibodies can be used in pregnancy tests.",
            T_INFECTION, "describe", "Biotechnology",
            "Explain antigen–antibody binding on test strip.",
            "Monoclonal antibodies on the test strip bind to hCG hormone in urine. When hCG is present, coloured beads bound to mobile antibodies accumulate at the test line, producing a visible coloured band.",
            ["hCG detected by antibodies.", "Binding at test line.", "Visible colour change."],
            ["Saying antibodies are produced in the test.", "No mention of hCG."],
            "Monoclonal antibodies bind to one specific antigen.",
        ),
        _q4(
            "A new strain of bacterium is resistant to penicillin. Explain how natural selection has led to this.",
            T_INFECTION, "explain", "Antibiotic resistance",
            "Variation, selection pressure, reproduction of resistant bacteria.",
            "Random mutations produce some bacteria resistant to penicillin. When penicillin is used, susceptible bacteria die but resistant ones survive and reproduce. Over time the proportion of resistant bacteria increases in the population.",
            ["Variation or mutation gives resistance.", "Antibiotic selects survivors.", "Resistant bacteria reproduce.", "Increase in resistant proportion."],
            ["Saying bacteria evolve to need antibiotics.", "Lamarckian 'trying to survive'."],
            "Selection acts on existing variation — bacteria do not 'try' to become resistant.",
        ),
        _q4(
            "Evaluate the use of antibiotics to treat mild throat infections.",
            T_INFECTION, "evaluate", "Medicine",
            "Weigh symptom relief against resistance and side effects.",
            "Antibiotics may shorten bacterial throat infections but many sore throats are viral and will not respond. Overuse selects resistant bacteria and can cause side effects. Rest and fluids may be sufficient for mild cases. Reserve antibiotics for confirmed bacterial infection.",
            ["May help if bacterial.", "Ineffective if viral.", "Overuse drives resistance.", "Balanced judgement on mild cases."],
            ["Always using antibiotics.", "Ignoring resistance."],
            "Evaluation needs advantage, limitation and conclusion.",
        ),
        _q6(
            "Describe how you would prepare and observe a bacterial culture on agar using aseptic technique. Include safety and how to reduce contamination.",
            T_INFECTION, "describe", "Microbiology practical",
            "Full aseptic technique method with evaluation.",
            "Sterilise inoculating loop by flaming until red hot and cooling. Lift lid of Petri dish slightly and streak sample on agar. Seal dish with tape (not airtight). Incubate upside down at 25 °C in school labs. Work near a Bunsen flame to create updraft. Disinfect bench before and after. Do not open plates after incubation; seal and dispose safely.",
            ["Loop sterilised by flaming.", "Minimal lid opening.", "Correct incubation temperature for school.", "Flame or disinfection used.", "Sealed disposal.", "Logical safe sequence."],
            ["Incubating at 37 °C in open plates.", "No sterilisation of loop."],
            "School labs use 25 °C to reduce pathogen risk.",
            "Link aseptic technique to preventing unwanted microbes.",
        ),
        calc_q(
            "The area of a Petri dish colony doubles every 3 hours. After 3 hours the colony area is 12 mm². Calculate the area after 9 hours if growth continues at the same rate.",
            T_INFECTION, 3,
            "Three doubling periods occur in 9 hours.",
            DEFAULT_STEPS,
            "9 hours = three doubling periods. Area = 12 × 2 × 2 × 2 = 12 × 8 = 96 mm².",
            ["Recognises three doublings.", "Multiplies by 2 three times.", "96 mm²."],
            ["Adding instead of multiplying.", "Only one doubling."],
            "Exponential growth multiplies; do not add the increase each time.",
        ),
        _q4(
            "Describe how you would investigate the effect of an antibiotic on bacterial growth using pre-poured agar plates.",
            T_INFECTION, "describe", "Required practical — antimicrobial discs",
            "Method for antibiotic disc diffusion test.",
            "Use aseptic technique to streak bacteria evenly on agar. Place antibiotic discs on the surface with sterile forceps. Incubate at 25 °C for 48 hours. Measure the clear zone (zone of inhibition) around each disc. Larger zones indicate greater effectiveness.",
            ["Even bacterial lawn.", "Antibiotic discs placed aseptically.", "Zone of inhibition measured.", "Link zone size to effectiveness."],
            ["Measuring colony count only.", "Opening plates during incubation."],
            "Clear zone = bacteria killed by antibiotic diffusing from disc.",
        ),
    ]


def _bioenergetics() -> list[dict]:
    return [
        _q1(
            "State the word equation for aerobic respiration.",
            T_BIOENER, "state", "Respiration",
            "Recall reactants and products.",
            "Glucose + oxygen → carbon dioxide + water",
            ["Including light.", "Lactic acid as product."],
            "Aerobic respiration needs oxygen and releases CO₂.",
        ),
        _q1(
            "Give the name of the green pigment that absorbs light in photosynthesis.",
            T_BIOENER, "give", "Photosynthesis",
            "Name the pigment in chloroplasts.",
            "Chlorophyll.",
            ["Carotene only without chlorophyll.", "Haemoglobin."],
            "Chlorophyll is in chloroplasts.",
        ),
        _q1(
            "State where aerobic respiration occurs in a cell.",
            T_BIOENER, "state", "Respiration",
            "Identify the organelle.",
            "Mitochondria.",
            ["Chloroplasts.", "Nucleus."],
            "Mitochondria are the site of aerobic respiration.",
        ),
        _q2(
            "Describe the effect of increasing light intensity on the rate of photosynthesis at low light levels.",
            T_BIOENER, "describe", "Limiting factors",
            "Rate increases then may plateau.",
            "As light intensity increases, the rate of photosynthesis increases because more light energy is available for the light-dependent reactions. At low light, light intensity is the limiting factor.",
            ["Rate increases with light.", "Light is limiting factor at low intensity."],
            ["Saying rate always increases without limit.", "Confusing with respiration only."],
            "Limiting factor = factor restricting rate.",
        ),
        _q3(
            "Explain why plants respire all the time.",
            T_BIOENER, "explain", "Respiration",
            "ATP needed for life processes day and night.",
            "Respiration releases ATP needed for active transport, protein synthesis, cell division and movement. These processes continue day and night, so respiration must continue even when photosynthesis stops in the dark.",
            ["ATP needed for life processes.", "Named process requiring ATP.", "Continues in dark / not only in light."],
            ["Saying respiration only happens at night.", "Confusing with breathing."],
            "Respiration ≠ breathing; it happens in all living cells.",
        ),
        _q2(
            "Compare aerobic and anaerobic respiration in yeast.",
            T_BIOENER, "compare", "Respiration",
            "Products and energy yield.",
            "Both release energy. Aerobic respiration in yeast produces carbon dioxide and water with a high ATP yield. Anaerobic respiration produces ethanol and carbon dioxide with a lower ATP yield.",
            ["Both release energy.", "Different products or ATP yield stated."],
            ["Saying anaerobic produces lactic acid in yeast.", "Equal ATP yield."],
            "Yeast anaerobic = ethanol fermentation.",
        ),
        _q3(
            "Explain how the rate of photosynthesis is limited by carbon dioxide concentration.",
            T_BIOENER, "explain", "Limiting factors",
            "CO₂ needed for Calvin cycle; plateau when other factor limits.",
            "Carbon dioxide is a reactant in photosynthesis. Increasing CO₂ increases the rate until another factor such as light or temperature becomes limiting, after which the rate plateaus.",
            ["CO₂ is a reactant.", "Rate increases then plateaus.", "Another factor becomes limiting."],
            ["Saying CO₂ is a product.", "No plateau mentioned."],
            "Only one factor limits at a time at steady state.",
        ),
        _q2(
            "Describe an experiment to investigate the effect of temperature on the rate of photosynthesis using pondweed.",
            T_BIOENER, "describe", "Investigations",
            "Count bubbles at different temperatures with controlled light and CO₂.",
            "Place pondweed in water with sodium hydrogencarbonate (CO₂ source) under a lamp at fixed distance. Count bubbles per minute at different water temperatures in a water bath. Keep light intensity and CO₂ concentration constant.",
            ["Bubble counting as rate measure.", "Temperature changed with light and CO₂ controlled."],
            ["Changing light and temperature together.", "No CO₂ source."],
            "Count bubbles for the same time at each temperature.",
        ),
        _q4(
            "A farmer grows tomatoes in a greenhouse. Explain how adjusting light, CO₂ and temperature can increase crop yield.",
            T_BIOENER, "explain", "Applications",
            "Optimise photosynthesis without excessive respiration cost.",
            "Extra lighting extends photosynthesis time. Enriched CO₂ increases carbon fixation when light is sufficient. Optimum warmth increases enzyme activity in photosynthesis. Together they raise sugar production for growth, but excessive heat may increase respiration losses.",
            ["Light increases photosynthesis time/rate.", "CO₂ increases rate.", "Temperature affects enzymes.", "Link to yield or growth."],
            ["Only mentioning one factor.", "Ignoring respiration at high temperature."],
            "Commercial growers balance photosynthesis gain against cost.",
        ),
        _q4(
            "Explain why anaerobic respiration in muscles during vigorous exercise causes fatigue.",
            T_BIOENER, "explain", "Exercise",
            "Lactic acid and oxygen debt.",
            "When oxygen supply is insufficient, muscles respire anaerobically producing lactic acid. Lactic acid accumulation causes muscle fatigue and oxygen debt must be repaid after exercise to oxidise it.",
            ["Anaerobic in muscles.", "Lactic acid produced.", "Fatigue or oxygen debt.", "Recovery need."],
            ["Ethanol in muscles.", "No oxygen debt."],
            "Muscle anaerobic → lactic acid, not ethanol.",
        ),
        _q6(
            "Describe how you would investigate the effect of light colour on the rate of photosynthesis using Elodea and a lamp with coloured filters. Include fair test details and expected results.",
            T_BIOENER, "describe", "Photosynthesis practical",
            "Full investigation with variables and prediction.",
            "Place Elodea in sodium hydrogencarbonate solution at fixed temperature. Position lamp at constant distance with red, green and blue filters in turn. Count bubbles per minute for each colour, repeating and calculating mean. Keep plant piece size and volume of water constant. Expect highest rate under red/blue as chlorophyll absorbs these best; green lowest as it is reflected.",
            ["Same distance and temperature.", "Filters change light colour only.", "Bubble rate measured with repeats.", "Prediction linked to chlorophyll absorption.", "Fair test variables listed.", "Logical sequence."],
            ["Changing lamp distance for each colour.", "No repeats."],
            "Chlorophyll absorbs red and blue most; reflects green.",
            "Relate results to absorption spectrum of chlorophyll.",
        ),
        calc_q(
            "A plant produces 0.48 g of biomass in 2 hours. Calculate the rate of biomass production in g/h.",
            T_BIOENER, 3,
            "Rate = amount ÷ time.",
            DEFAULT_STEPS,
            "Rate = 0.48 ÷ 2 = 0.24 g/h.",
            ["Correct formula rate = amount ÷ time.", "Correct division.", "0.24 g/h with unit."],
            ["Multiplying by 2.", "Missing unit."],
            "Rate always includes 'per unit time'.",
        ),
        _q4(
            "Describe how you would investigate the effect of sugar concentration on yeast respiration by measuring carbon dioxide production.",
            T_BIOENER, "describe", "Required practical — yeast",
            "Use yeast in sugar solutions with gas collection.",
            "Mix equal masses of yeast with different sugar concentrations in warm water. Attach boiling tubes to gas syringes or inverted measuring cylinders in a water bath at 35 °C. Measure volume of CO₂ collected in five minutes. Keep yeast mass, volume and temperature constant.",
            ["Different sugar concentrations.", "CO₂ volume measured.", "Temperature and yeast mass controlled.", "Same time interval."],
            ["Measuring temperature change only.", "No control of yeast amount."],
            "Warm water activates yeast; too hot kills it.",
        ),
    ]


def _homeostasis_and_response() -> list[dict]:
    return [
        _q1(
            "State the name of the gland that produces insulin.",
            T_HOME, "state", "Hormones",
            "Recall endocrine source of insulin.",
            "Pancreas.",
            ["Pituitary.", "Adrenal gland."],
            "Insulin is produced by β cells in the pancreas.",
        ),
        _q1(
            "Give the name of the type of neurone that carries impulses from receptors to the central nervous system.",
            T_HOME, "give", "Nervous system",
            "Name sensory neurones.",
            "Sensory neurone.",
            ["Motor neurone.", "Relay neurone only."],
            "Sensory → CNS → motor pathway.",
        ),
        _q1(
            "State what is meant by homeostasis.",
            T_HOME, "state", "Homeostasis",
            "Define maintenance of internal conditions.",
            "Homeostasis is the regulation of internal conditions to maintain optimum conditions for cell function.",
            ["Keeping the body warm only.", "Controlling movement."],
            "Homeostasis covers water, temperature, blood glucose and more.",
        ),
        _q2(
            "Describe the function of the skin in thermoregulation when body temperature rises.",
            T_HOME, "describe", "Temperature control",
            "Vasodilation and sweating.",
            "Blood vessels near the skin surface dilate (vasodilation) so more blood flows near the surface, transferring heat to the environment. Sweat glands release sweat which evaporates, removing heat energy.",
            ["Vasodilation or more blood near surface.", "Sweating and evaporation removes heat."],
            ["Vasoconstriction when hot.", "Saying hair stands up for cooling."],
            "Hot → vasodilation + sweat; cold → vasoconstriction + shivering.",
        ),
        _q2(
            "Explain why type 1 diabetes patients need insulin injections.",
            T_HOME, "explain", "Diabetes",
            "No insulin production leads to high blood glucose.",
            "In type 1 diabetes the pancreas produces little or no insulin, so glucose is not taken up by cells effectively and blood glucose stays dangerously high. Insulin injections lower blood glucose to a safe level.",
            ["Little or no insulin produced.", "Blood glucose stays high without treatment.", "Insulin lowers blood glucose."],
            ["Confusing type 1 and type 2.", "Saying insulin raises glucose."],
            "Type 1 = no insulin; type 2 = cells resist insulin.",
        ),
        _q2(
            "Compare the nervous and hormonal systems.",
            T_HOME, "compare", "Coordination",
            "Speed, duration and pathway differences.",
            "The nervous system uses electrical impulses along neurones for fast, short-lived, targeted responses. The hormonal system uses hormones in the blood for slower, longer-lasting, widespread responses.",
            ["Nervous: fast/electrical.", "Hormonal: slower/chemical in blood."],
            ["Saying hormones are faster.", "No duration difference."],
            "Nervous = quick and local; hormones = slow and widespread.",
        ),
        _q3(
            "Explain how a reflex arc protects the body from harm.",
            T_HOME, "explain", "Reflexes",
            "Receptor to effector via spinal cord without conscious brain.",
            "A stimulus is detected by receptors and an impulse passes along a sensory neurone to the spinal cord. A relay neurone connects to a motor neurone, which stimulates an effector (muscle or gland) to remove the body part from danger before the brain processes the sensation.",
            ["Receptor detects stimulus.", "Spinal cord relay.", "Motor neurone to effector for rapid response."],
            ["Impulse goes to brain first.", "No effector mentioned."],
            "Reflexes are automatic and faster than conscious responses.",
        ),
        _q3(
            "Describe how the kidneys respond when blood water potential is too low.",
            T_HOME, "describe", "Water balance",
            "More ADH, more water reabsorption.",
            "The brain detects low water potential and releases more ADH. ADH makes kidney tubules more permeable so more water is reabsorbed into the blood, producing a smaller volume of concentrated urine.",
            ["ADH increases.", "More water reabsorbed in kidneys.", "Concentrated urine produced."],
            ["Less reabsorption when dehydrated.", "ADH from kidneys."],
            "Low water → more ADH → save water.",
        ),
        _q4(
            "A student eats a large sugary meal. Explain how the body returns blood glucose to normal.",
            T_HOME, "explain", "Blood glucose control",
            "Insulin from pancreas, uptake and storage as glycogen.",
            "Blood glucose rises after the meal. The pancreas secretes insulin, which causes liver and muscle cells to take up glucose and convert it to glycogen for storage. Blood glucose falls back to normal. If it drops too low, glucagon is released.",
            ["Glucose rises after meal.", "Insulin secreted.", "Glucose taken up or stored as glycogen.", "Returns to normal."],
            ["Only glucagon after eating.", "Insulin raises glucose."],
            "After eating → insulin; when low → glucagon.",
        ),
        _q4(
            "Evaluate the use of plant hormones such as auxin in agriculture.",
            T_HOME, "evaluate", "Plant hormones",
            "Weigh benefits in rooting and weed control against cost and ethics.",
            "Auxin rooting powder helps cuttings develop roots quickly, saving time. Selective weedkillers based on auxin mimicry kill broad-leaved weeds in grass crops. However, overuse may affect non-target plants and consumers may prefer reduced chemical use. Overall useful when applied carefully.",
            ["Benefit: rooting or weed control.", "Selective action explained.", "Limitation or environmental concern.", "Supported conclusion."],
            ["Only advantages.", "Saying auxin kills all plants equally."],
            "Selective weedkillers exploit different auxin sensitivity.",
        ),
        _q6(
            "Describe an investigation to show phototropism in plant seedlings. Include how you would measure the response and control variables.",
            T_HOME, "describe", "Plant responses practical",
            "Compare light from one side with controls.",
            "Grow identical seedlings in moist cotton wool. Place one group with unidirectional light from one side, another in a cardboard box with a single hole, and a control under uniform light. After several days, measure angle of shoot curvature from vertical. Keep temperature and water constant. Repeat with ten seedlings per group and calculate mean angle.",
            ["Unidirectional light setup.", "Control under uniform light.", "Angle or curvature measured.", "Variables controlled.", "Repeats and mean.", "Clear time period."],
            ["No control group.", "Measuring root length only."],
            "Auxin redistributes to shaded side causing unequal growth.",
            "Link curvature to auxin and differential elongation.",
        ),
        calc_q(
            "A person has body mass 72 kg and height 1.80 m. Calculate their BMI using BMI = mass (kg) ÷ [height (m)]².",
            T_HOME, 3,
            "Square height before dividing mass.",
            DEFAULT_STEPS,
            "Height² = 1.80² = 3.24 m². BMI = 72 ÷ 3.24 = 22.2 kg/m² (3 s.f.).",
            ["Height squared correctly.", "Division set up.", "BMI ≈ 22.2 with unit."],
            ["Not squaring height.", "Using cm without converting."],
            "Always convert height to metres before squaring.",
        ),
        _q4(
            "Describe how you would investigate the effect of caffeine on reaction time using a ruler-drop test.",
            T_HOME, "describe", "Required practical — reaction time",
            "Fair test comparing reaction times with and without caffeine.",
            "Measure baseline reaction time: partner drops ruler, subject catches and record distance fallen. Convert to time. Repeat after controlled caffeine dose at same time of day, with same sleep. Use at least ten catches per condition and calculate mean. Exclude anomalous drops. Keep same hand and ruler width.",
            ["Ruler-drop method described.", "Before/after caffeine comparison.", "Repeats and mean.", "Control variables named."],
            ["No repeats.", "Changing multiple variables at once."],
            "Lower distance = faster reaction; convert using d = ½gt² if needed.",
        ),
    ]


def _inheritance_variation_evolution() -> list[dict]:
    return [
        _q1(
            "State the name of the molecule that carries genetic information in the nucleus.",
            T_INHERIT, "state", "Genetics",
            "Identify genetic material.",
            "DNA (deoxyribonucleic acid).",
            ["Protein.", "Glucose."],
            "DNA is the genetic material in chromosomes.",
        ),
        _q1(
            "Give the term for different versions of the same gene.",
            T_INHERIT, "give", "Genetics",
            "Name alleles.",
            "Alleles.",
            ["Chromosomes.", "Nucleotides only."],
            "Alleles are versions of a gene.",
        ),
        _q1(
            "State what is meant by a dominant allele.",
            T_INHERIT, "state", "Inheritance",
            "Define dominance.",
            "An allele that is always expressed in the phenotype when present.",
            ["The most common allele.", "An allele on the X chromosome only."],
            "Dominant shows with one copy; recessive needs two.",
        ),
        _q2(
            "Describe the structure of DNA including the complementary base pairs.",
            T_INHERIT, "describe", "DNA structure",
            "Double helix, bases A-T and C-G.",
            "DNA is a double helix made of two strands. Bases pair specifically: adenine with thymine and cytosine with guanine, held by hydrogen bonds.",
            ["Double helix or two strands.", "A-T and C-G pairing."],
            ["A pairs with G.", "Single strand only."],
            "Chargaff's rules: A=T, C=G.",
        ),
        _q3(
            "Explain why siblings inherit different combinations of alleles from the same parents.",
            T_INHERIT, "explain", "Meiosis",
            "Independent assortment and fertilisation randomness.",
            "During meiosis, gametes receive one chromosome from each homologous pair at random. Fertilisation combines gametes randomly, so each offspring gets a unique allele combination unless identical twins.",
            ["Gametes genetically different due to meiosis.", "Random fertilisation.", "Unique combination in offspring."],
            ["Mitosis in gametes.", "Identical gametes from parents."],
            "Meiosis produces variation; fertilisation shuffles it.",
        ),
        _q2(
            "Compare genetic and environmental variation.",
            T_INHERIT, "compare", "Variation",
            "Origin and examples.",
            "Genetic variation is inherited from parents via alleles, e.g. blood group. Environmental variation is caused by lifestyle or surroundings, e.g. language spoken or scars. Most characteristics are influenced by both.",
            ["Genetic: inherited alleles.", "Environmental: caused by surroundings."],
            ["Saying all variation is genetic.", "No example."],
            "Give one example of each type.",
        ),
        _q3(
            "Explain how natural selection can lead to evolution of antibiotic resistance in bacteria.",
            T_INHERIT, "explain", "Evolution",
            "Variation, selection, inheritance over generations.",
            "Random mutations create resistant bacteria. Antibiotics kill non-resistant forms, leaving resistant ones to reproduce. Alleles for resistance become more common over generations, changing the population — evolution.",
            ["Mutation gives variation.", "Selection by antibiotic.", "Survivors reproduce; allele frequency changes."],
            ["Bacteria change to resist.", "All bacteria mutate at once."],
            "Evolution = change in allele frequency in a population.",
        ),
        _q2(
            "Describe how to interpret a pedigree diagram showing inheritance of a recessive disorder.",
            T_INHERIT, "describe", "Pedigree analysis",
            "Identify carriers and affected individuals.",
            "Affected individuals have two recessive alleles and may skip generations if parents are carriers. Carriers are unaffected heterozygotes. If two carriers have children, about one quarter may be affected in each pregnancy.",
            ["Recessive can skip generations.", "Carriers heterozygous unaffected or offspring ratio stated."],
            ["Dominant pattern described.", "All children of carriers affected."],
            "Recessive disorders often appear in siblings with unaffected parents.",
        ),
        _q4(
            "In pea plants, allele T for tall is dominant to t for short. Cross two heterozygous tall plants. Explain the expected phenotype ratio in offspring.",
            T_INHERIT, "explain", "Genetic crosses",
            "Punnett square Tt × Tt gives 3:1.",
            "Parents are Tt × Tt. Gametes T and t from each. Offspring genotypes TT, Tt, Tt, tt — phenotypically three tall to one short because T is dominant.",
            ["Parents Tt identified.", "Gametes T and t.", "Ratio 3 tall : 1 short.", "tt is short phenotype."],
            ["1:1 ratio.", "tt tall phenotype."],
            "Draw Punnett square for four genotype outcomes.",
        ),
        _q4(
            "Explain how the fossil record provides evidence for evolution.",
            T_INHERIT, "explain", "Evidence for evolution",
            "Gradual change, transitional forms, extinction.",
            "Fossils show organisms that lived in the past and how species change over geological time. Transitional fossils link groups, and some species in fossils no longer exist, supporting change and extinction over millions of years.",
            ["Fossils show past life.", "Change over time.", "Transitional or extinct forms.", "Link to evolution."],
            ["All fossils identical to today.", "Fossils prove creation in one day."],
            "Older rocks generally contain simpler or different forms.",
        ),
        _q6(
            "Describe how selective breeding is used to improve crop plants. In your answer, explain steps taken, benefits and one ethical or biological limitation.",
            T_INHERIT, "describe", "Selective breeding",
            "Choose parents, breed, repeat over generations.",
            "Farmers select plants with desired traits such as high yield or disease resistance and breed them together. Offspring showing the trait are selected and bred again over many generations to increase allele frequency. Benefits include higher food production without GM. Limitations: reduced gene pool may increase disease vulnerability or it takes many generations.",
            ["Selection of desired trait.", "Breed selected offspring.", "Repeat over generations.", "Benefit stated.", "Limitation stated.", "Coherent account."],
            ["One generation only.", "Same as genetic modification."],
            "Selective breeding uses natural variation; GM inserts genes directly.",
            "Compare with cloning and GM for top grades.",
        ),
        calc_q(
            "In a population of 200 plants, 18 show a recessive phenotype. Calculate the percentage of plants homozygous recessive.",
            T_INHERIT, 3,
            "Percentage = (number ÷ total) × 100.",
            DEFAULT_STEPS,
            "Percentage = (18 ÷ 200) × 100 = 9%.",
            ["Correct formula.", "Correct fraction 18/200.", "9%."],
            ["Using 18/100.", "Forgetting to multiply by 100."],
            "Percentage must relate part to whole population.",
        ),
        _q4(
            "Describe how you would extract DNA from fruit such as strawberries using classroom reagents.",
            T_INHERIT, "describe", "Required practical — DNA extraction",
            "Crush, detergent, heat, cold ethanol precipitation.",
            "Crush fruit with extraction buffer containing detergent and salt to break membranes and release DNA. Filter to remove solids. Add ice-cold ethanol to filtrate; white strands precipitate at the interface. Spool DNA on a glass rod.",
            ["Mechanical breakdown of cells.", "Detergent breaks membranes.", "Cold ethanol precipitates DNA.", "Observable white strands."],
            ["Using hot ethanol.", "No filtration step."],
            "Cold ethanol makes DNA insoluble so it visible.",
        ),
    ]


def _ecology() -> list[dict]:
    return [
        _q1(
            "State what is meant by a community in ecology.",
            T_ECOLOGY, "state", "Ecosystems",
            "Define community.",
            "All the populations of different species living in the same habitat.",
            ["All organisms in the world.", "One species only."],
            "Community = all species in a habitat.",
        ),
        _q1(
            "Give one abiotic factor that affects ecosystems.",
            T_ECOLOGY, "give", "Abiotic factors",
            "Name a non-living factor.",
            "Light intensity (or temperature, water availability, soil pH, wind).",
            ["Predation.", "Competition between animals only."],
            "Abiotic = non-living physical factor.",
        ),
        _q1(
            "Name the process that converts atmospheric nitrogen into usable compounds by bacteria.",
            T_ECOLOGY, "state", "Cycles",
            "Nitrogen fixation.",
            "Nitrogen fixation.",
            ["Denitrification.", "Photosynthesis."],
            "Rhizobia in root nodules fix nitrogen.",
        ),
        _q2(
            "Describe the role of decomposers in the carbon cycle.",
            T_ECOLOGY, "describe", "Carbon cycle",
            "Break down dead material releasing CO₂.",
            "Decomposers such as bacteria and fungi break down dead organisms and waste, respiring and returning carbon dioxide to the atmosphere.",
            ["Break down dead material.", "Release CO₂ by respiration."],
            ["Saying decomposers photosynthesise.", "Locking carbon forever."],
            "Decomposers complete the cycle back to CO₂.",
        ),
        _q3(
            "Explain why bioaccumulation of pesticides is a problem for top predators.",
            T_ECOLOGY, "explain", "Pollution",
            "Toxins not excreted accumulate up food chain.",
            "Pesticides are not easily broken down and accumulate in fat. Each trophic level eats many organisms from the level below, so concentration increases towards top predators, causing population decline.",
            ["Persistent chemicals accumulate.", "Increase up food chain.", "Harm to top predators."],
            ["Toxins dilute at top.", "Only affects plants."],
            "Biomagnification = increasing concentration up levels.",
        ),
        _q2(
            "Compare intraspecific and interspecific competition.",
            T_ECOLOGY, "compare", "Competition",
            "Same vs different species.",
            "Intraspecific competition is between individuals of the same species for mates, food or territory. Interspecific competition is between different species for shared resources such as food or space.",
            ["Intraspecific: same species.", "Interspecific: different species."],
            ["Same definition for both.", "No resource mentioned."],
            "Intra = within species; inter = between species.",
        ),
        _q3(
            "Explain how deforestation can contribute to climate change.",
            T_ECOLOGY, "explain", "Human impact",
            "Less CO₂ uptake, combustion releases CO₂, fewer trees.",
            "Trees remove CO₂ by photosynthesis. Cutting forests reduces uptake. Burning or decay of wood releases stored carbon as CO₂, a greenhouse gas that enhances global warming.",
            ["Less photosynthesis / CO₂ removal.", "CO₂ released by burning or decay.", "Link to greenhouse effect."],
            ["Oxygen depletion main cause.", "No link to CO₂."],
            "Deforestation both releases carbon and reduces the sink.",
        ),
        _q2(
            "Describe how to use a quadrat and random sampling to estimate plant species frequency in a field.",
            T_ECOLOGY, "describe", "Sampling",
            "Random coordinates, count hits, repeat.",
            "Divide field into a grid using tape measures. Use random numbers to place quadrats. Record species touching or within each quadrat. Repeat at least ten times and calculate mean frequency or percentage cover.",
            ["Random placement of quadrats.", "Species recorded with repeats or mean calculated."],
            ["Quadrats placed only where plants visible.", "Single sample."],
            "Random avoids bias towards rich patches.",
        ),
        _q4(
            "Evaluate the introduction of a non-native predator to control an invasive prey species.",
            T_ECOLOGY, "evaluate", "Conservation",
            "May control prey but risk to native species.",
            "The predator may reduce invasive prey protecting native plants. However, the predator might also hunt native species, lack natural enemies and become invasive itself. Monitoring and risk assessment are essential before release.",
            ["Possible benefit to ecosystem.", "Risk to native species.", "Predator may become invasive.", "Judgement on caution."],
            ["Only benefits listed.", "No evaluation conclusion."],
            "Biological control can backfire — evaluate both sides.",
        ),
        _q4(
            "Explain how maintaining biodiversity can help ensure food security.",
            T_ECOLOGY, "explain", "Biodiversity",
            "Gene pool for crops, pest control, resilience.",
            "Wild relatives of crops provide alleles for disease resistance or drought tolerance in breeding. Diverse ecosystems support pollinators and natural pest control. Monocultures with low diversity are vulnerable to crop failure.",
            ["Wild relatives for breeding.", "Pollinators or pest control.", "Resilience against disease or famine."],
            ["Biodiversity only for tourism.", "No link to food."],
            "Food security needs genetic resources and ecosystem services.",
        ),
        _q6(
            "Describe a field investigation to compare biodiversity in two habitats using sweep netting and identification keys. Include how to calculate a simple biodiversity index and improve reliability.",
            T_ECOLOGY, "describe", "Fieldwork",
            "Systematic sampling, species count, Simpson or species richness.",
            "In each habitat, perform ten sweep net samples along transects of equal length at the same time of day. Identify and count species using keys. Record numbers in a table. Calculate species richness or Simpson's index for each habitat. Repeat on another day and compare means. Control weather and sampler skill.",
            ["Sweep netting method.", "Identification using keys.", "Biodiversity index calculated.", "Fair comparison between habitats.", "Reliability improvement.", "Logical sequence."],
            ["No identification method.", "Different transect lengths."],
            "Species richness = number of different species present.",
            "Higher index generally means higher biodiversity.",
        ),
        calc_q(
            "In a food chain, grass transfers 10 000 kJ to rabbits. Only 10% passes to foxes. Calculate the energy available to foxes.",
            T_ECOLOGY, 3,
            "Multiply energy by efficiency as decimal.",
            DEFAULT_STEPS,
            "Energy to foxes = 10 000 × 0.10 = 1000 kJ.",
            ["Uses 10% or 0.10.", "Correct multiplication set up.", "1000 kJ."],
            ["Subtracting 10%.", "Using 90%."],
            "Energy transfer between trophic levels is roughly 10%.",
        ),
        _q4(
            "Describe how you would investigate the effect of a pollutant such as acid rain on seed germination using cress seeds on filter paper.",
            T_ECOLOGY, "describe", "Required practical — pollution",
            "Different pH solutions, count germination over time.",
            "Place equal numbers of cress seeds on damp filter paper in Petri dishes. Add equal volumes of solutions at different pH values. Keep at same temperature and light. Count germinated seeds daily for seven days. Calculate percentage germination. Repeat with fresh seeds.",
            ["pH as independent variable.", "Germination counted.", "Percentage calculated.", "Controls named."],
            ["Changing temperature each day.", "No repeat."],
            "Use sulfuric acid diluted carefully with safety goggles.",
        ),
    ]


def _required_practical_skills() -> list[dict]:
    return [
        _q1(
            "State what is meant by the independent variable in an investigation.",
            T_PRACTICAL, "state", "Variables",
            "Define the variable changed deliberately.",
            "The variable that is changed or selected by the investigator.",
            ["The variable measured.", "A variable kept constant."],
            "Independent = what you change.",
        ),
        _q1(
            "Give one hazard symbol meaning in a school laboratory.",
            T_PRACTICAL, "give", "Safety",
            "Name a hazard and meaning.",
            "Flammable — catches fire easily (or toxic, corrosive, irritant).",
            ["Wrong symbol meaning.", "Vague 'danger'."],
            "Link symbol to specific risk and control.",
        ),
        _q1(
            "State why repeats are used in experiments.",
            T_PRACTICAL, "state", "Reliability",
            "Improve reliability and identify anomalies.",
            "To improve reliability and calculate a mean, and to identify anomalous results.",
            ["To make results different.", "To use more equipment."],
            "Repeats → mean → more reliable data.",
        ),
        _q2(
            "Describe how to identify an anomalous result in a data set.",
            T_PRACTICAL, "describe", "Data handling",
            "Compare to other repeats; exclude from mean.",
            "An anomalous result is very different from other repeats when conditions were the same. It should be excluded from the mean but recorded, and the experiment repeated if possible.",
            ["Very different from other values.", "Excluded from mean but recorded."],
            ["Deleting without recording.", "Calling any highest value anomalous."],
            "Do not include anomalies in mean calculations.",
        ),
        _q2(
            "Explain why a control experiment is used.",
            T_PRACTICAL, "explain", "Experimental design",
            "Comparison to show effect of independent variable.",
            "A control provides a baseline where the independent variable is absent or standard, so any change in the dependent variable can be attributed to the factor being tested.",
            ["Baseline for comparison.", "Shows effect of changed variable."],
            ["Control is the variable you change.", "No purpose stated."],
            "Without a control you cannot prove cause.",
        ),
        _q2(
            "Compare accuracy and precision in measurements.",
            T_PRACTICAL, "compare", "Measurement",
            "True value vs repeat closeness.",
            "Accuracy is how close a measurement is to the true value. Precision is how close repeated measurements are to each other, regardless of whether they are correct.",
            ["Accuracy: closeness to true value.", "Precision: repeat closeness."],
            ["Using as synonyms.", "No contrast."],
            "Precise but inaccurate = consistent wrong answers.",
        ),
        _q3(
            "Describe how to draw a line graph from experimental data including axes, units and line of best fit.",
            T_PRACTICAL, "describe", "Graph skills",
            "IV on x, DV on y, scale, points, smooth curve or line.",
            "Plot the independent variable on the x-axis and dependent on the y-axis with labels and units. Use a sensible scale. Plot points as crosses. Draw a smooth curve or straight line of best fit through the trend, not dot-to-dot.",
            ["Correct axes and labels.", "Units on axes.", "Line of best fit not dot-to-dot."],
            ["Swapped axes.", "Joining every point regardless of trend."],
            "Line of best fit shows overall trend.",
        ),
        _q3(
            "Explain how to convert units from millimetres to micrometres.",
            T_PRACTICAL, "explain", "Units",
            "Multiply by 1000 for smaller unit.",
            "There are 1000 µm in 1 mm, so multiply the measurement in mm by 1000 to convert to µm. For example, 0.05 mm = 50 µm.",
            ["1000 µm in 1 mm.", "Multiply mm by 1000.", "Example conversion."],
            ["Divide instead of multiply.", "Using 100 factor."],
            "Going to smaller units → multiply.",
        ),
        _q4(
            "A student’s graph shows a straight line through the origin with gradient 2. Determine what this tells you about the relationship between the variables.",
            T_PRACTICAL, "determine", "Graph interpretation",
            "Direct proportionality; DV = 2 × IV.",
            "The dependent variable is directly proportional to the independent variable. When IV doubles, DV doubles. The relationship can be written as DV = 2 × IV.",
            ["Direct proportion identified.", "Gradient meaning explained.", "Example doubling relationship.", "Equation or clear statement."],
            ["Inverse proportion.", "Gradient ignored."],
            "Through origin + straight line = direct proportion.",
        ),
        _q4(
            "Evaluate using mean alone without range or repeat data when reporting an investigation.",
            T_PRACTICAL, "evaluate", "Data analysis",
            "Mean hides spread and reliability issues.",
            "The mean summarises central tendency but hides how spread out repeats are. Without range or standard deviation, an unreliable mean from widely different repeats may mislead. Reporting range and number of repeats strengthens conclusions.",
            ["Mean alone insufficient.", "Range or spread matters.", "Reliability concern.", "Better reporting suggested."],
            ["Mean always enough.", "No limitation given."],
            "Always pair mean with spread when possible.",
        ),
        _q6(
            "Describe how you would plan, carry out and evaluate an investigation to test whether pH affects amylase activity using starch and iodine. Include risk assessment and improvements.",
            T_PRACTICAL, "describe", "Enzyme practical planning",
            "Full plan with variables, method, safety and evaluation.",
            "Set up starch solution with amylase at different pH buffers in a water bath at 37 °C. Start timer and sample mixture every 30 s, add to iodine on a spotting tile. Record time until iodine stays orange-brown (starch gone). Control enzyme mass, starch volume and temperature. Risk: allergies or glass — goggles and care with iodine. Improve by triplicate repeats and colorimeter for colour change endpoint.",
            ["pH as independent variable.", "Iodine test for starch breakdown.", "Temperature controlled.", "Risk and control.", "Evaluation improvement.", "Coherent plan."],
            ["No endpoint described.", "Changing temperature with pH."],
            "Orange-brown iodine = no starch = reaction complete.",
            "Optimum pH for amylase is around neutral pH 7.",
        ),
        calc_q(
            "Five repeat measurements of mass are 2.4, 2.6, 2.5, 2.5 and 2.0 g. Calculate the mean mass excluding the anomalous result.",
            T_PRACTICAL, 3,
            "Exclude 2.0 g, sum others and divide by 4.",
            DEFAULT_STEPS,
            "Anomaly = 2.0 g. Mean = (2.4 + 2.6 + 2.5 + 2.5) ÷ 4 = 10.0 ÷ 4 = 2.5 g.",
            ["Anomalous value identified.", "Sum of four values.", "Mean = 2.5 g."],
            ["Including 2.0 g.", "Dividing by 5 after exclusion."],
            "State which value you excluded and why.",
        ),
        _q4(
            "Describe how you would calibrate an eyepiece graticule using a stage micrometer before measuring cell size.",
            T_PRACTICAL, "describe", "Required practical — microscopy",
            "Align scales, calculate µm per graticule unit.",
            "Place stage micrometer on microscope stage. Count how many eyepiece graticule divisions match a known distance on the micrometer scale (e.g. 0.1 mm). Divide known real distance by graticule divisions to find µm per graticule unit. Use this factor to convert cell graticule measurements to real size.",
            ["Both scales viewed at same magnification.", "Known real distance used.", "Conversion factor calculated.", "Apply to cell measurement."],
            ["Measuring without calibration.", "Changing magnification after calibration."],
            "Calibration valid only at the magnification used.",
        ),
    ]

def _calculations() -> list[dict]:
    return [
        {
            "title": "Magnification",
            "question": "A chloroplast is 5 mm long on a micrograph. The real length is 2.5 µm. Calculate the magnification.",
            "formula": "Magnification = image size ÷ actual size",
            "rearrange": "Same formula; convert units first",
            "substitution": "5 mm = 5000 µm; Magnification = 5000 ÷ 2.5",
            "working": "Magnification = ×2000",
            "answer": "×2000 (no units)",
            "note": "Magnification has no units. Convert both measurements to the same unit before dividing.",
        },
        {
            "title": "Percentage change in mass (osmosis)",
            "question": "A potato cylinder had mass 1.20 g before soaking and 1.32 g after. Calculate the percentage change in mass.",
            "formula": "Percentage change = (change ÷ original) × 100",
            "rearrange": "Change = final − original",
            "substitution": "Change = 1.32 − 1.20 = 0.12 g; (0.12 ÷ 1.20) × 100",
            "working": "Percentage change = 10%",
            "answer": "+10%",
            "note": "Use original mass as denominator. Positive value = mass gain.",
        },
        {
            "title": "Rate of reaction",
            "question": "In an enzyme experiment, 24 cm³ of gas was collected in 2 minutes. Calculate the rate in cm³/min.",
            "formula": "Rate = amount ÷ time",
            "rearrange": "Rate is subject",
            "substitution": "Rate = 24 ÷ 2",
            "working": "Rate = 12 cm³/min",
            "answer": "12 cm³/min",
            "note": "Rate always includes per unit time.",
        },
        {
            "title": "Body mass index (BMI)",
            "question": "Calculate the BMI of a person with mass 64 kg and height 1.65 m.",
            "formula": "BMI = mass (kg) ÷ [height (m)]²",
            "rearrange": "Square height first",
            "substitution": "BMI = 64 ÷ (1.65²) = 64 ÷ 2.7225",
            "working": "BMI = 23.5 kg/m² (3 s.f.)",
            "answer": "23.5 kg/m²",
            "note": "Height must be in metres before squaring.",
        },
        {
            "title": "Surface area to volume ratio",
            "question": "A cube-shaped organism has side length 2 mm. Calculate its surface area to volume ratio.",
            "formula": "SA = 6s², V = s³, ratio = SA ÷ V",
            "rearrange": "Calculate SA and V separately",
            "substitution": "SA = 6 × 2² = 24 mm²; V = 2³ = 8 mm³; ratio = 24 ÷ 8",
            "working": "SA:V ratio = 3:1 or 3 mm⁻¹",
            "answer": "3:1 (or 3 per mm)",
            "note": "Smaller organisms have higher SA:V, aiding exchange.",
        },
        {
            "title": "Mean and range",
            "question": "Five counts of daisy plants in quadrats are 4, 6, 5, 5 and 10. Calculate the mean and range.",
            "formula": "Mean = sum ÷ n; Range = highest − lowest",
            "rearrange": "Exclude anomaly if instructed",
            "substitution": "Mean = (4+6+5+5+10) ÷ 5 = 30 ÷ 5; Range = 10 − 4",
            "working": "Mean = 6; Range = 6",
            "answer": "Mean = 6 plants; Range = 6 plants",
            "note": "10 may be anomalous — discuss excluding for refined mean in evaluation.",
        },
        {
            "title": "Graph interpretation — rate from gradient",
            "question": "A graph of distance moved (cm) against time (min) is a straight line through the origin from 0 to 4 min and 20 cm. Determine the rate of movement.",
            "formula": "Rate = gradient = Δy ÷ Δx",
            "rearrange": "Pick two points on the line",
            "substitution": "Rate = 20 cm ÷ 4 min",
            "working": "Rate = 5 cm/min",
            "answer": "5 cm/min",
            "note": "Straight line through origin indicates constant rate / direct proportion.",
        },
        {
            "title": "Percentage of population",
            "question": "In a sample of 150 students, 27 are colour-blind recessive homozygotes. Calculate the percentage of the sample with this phenotype.",
            "formula": "Percentage = (part ÷ whole) × 100",
            "rearrange": "Percentage is subject",
            "substitution": "(27 ÷ 150) × 100",
            "working": "Percentage = 18%",
            "answer": "18%",
            "note": "Useful in genetic and epidemiological contexts.",
        },
    ]


def _practicals() -> list[dict]:
    return [
        {
            "title": "Microscopy: observing and measuring cells",
            "aim": "To prepare a slide of plant epidermis, observe cells under a microscope and estimate their size using a calibrated graticule.",
            "variables": "Independent: specimen (e.g. onion epidermis). Dependent: cell dimensions in µm. Control: same magnification, same staining method.",
            "method": "Peel thin epidermis, mount on slide with iodine stain and coverslip. View under low power then high power. Calibrate eyepiece graticule with stage micrometer at same magnification. Measure width of five cells in graticule units, convert to µm, calculate mean.",
            "risk": "Iodine stains skin — wear goggles and avoid contact. Handle glass slides and coverslips carefully to prevent cuts. Do not use cracked slides.",
            "results": "Table: cell number, graticule units, real width/µm. Include repeats and mean ± optional range.",
            "graph": "Optional bar chart of mean cell width with error bars from range of repeats.",
            "conclusion": "Onion epidermis cells are rectangular with cell wall, cytoplasm, nucleus and often vacuole visible. Mean width should be consistent at same magnification.",
            "evaluation": "Random error from measuring different cells; systematic error if calibration magnification changes. Improve by measuring more cells and using median if one cell differs greatly.",
            "exam_questions": [
                "Why is iodine used?",
                "Why calibrate the graticule?",
                "How do you calculate real size from graticule units?",
            ],
            "model_answers": [
                "Iodine stains starch and nuclei, making structures more visible.",
                "Graticule units are arbitrary; calibration converts them to real µm at that magnification.",
                "Real size = graticule reading × µm per graticule unit from calibration.",
            ],
        },
        {
            "title": "Osmosis in potato cylinders",
            "aim": "To investigate how sugar solution concentration affects water movement into or out of potato tissue.",
            "variables": "Independent: molarity of sugar solution. Dependent: percentage change in mass of potato cylinders. Control: same potato, same dimensions, same time, same temperature.",
            "method": "Cut equal-sized potato cylinders. Blot dry and record initial mass. Place one cylinder in each concentration of sugar solution for 30 minutes. Remove, blot dry, record final mass. Calculate percentage change in mass for each concentration.",
            "risk": "Low risk — wash hands after handling food. Mop spills to prevent slips. Scalpel cuts — cut away from body on tile.",
            "results": "Table: concentration/mol dm⁻³, initial mass/g, final mass/g, % change. Expect mass loss in concentrated solutions, gain in pure water.",
            "graph": "Plot percentage change in mass (y) against sugar concentration (x). Draw smooth curve crossing 0% change at approximate cell sap concentration.",
            "conclusion": "Water moves by osmosis from higher water potential to lower. Potato loses mass in hypertonic solutions and gains in hypotonic water.",
            "evaluation": "Surface drying affects mass — blot consistently. Improve by using borer for equal diameter and repeating entire experiment on another day.",
            "exam_questions": [
                "Why blot cylinders before weighing?",
                "What does zero percentage change indicate?",
                "Which solution is hypertonic to potato cells if mass decreases?",
            ],
            "model_answers": [
                "Removes surface water so measured mass change is due to osmosis in tissue, not surface moisture.",
                "No net osmosis — solution is isotonic to cell sap at that concentration.",
                "The more concentrated sugar solution where mass decreased — lower water potential than cell sap.",
            ],
        },
        {
            "title": "Investigating the effect of pH on amylase activity",
            "aim": "To find how pH affects the time taken for amylase to break down starch.",
            "variables": "Independent: pH (using buffer solutions). Dependent: time for starch to disappear (iodine test). Control: temperature 37 °C, same enzyme and starch concentrations.",
            "method": "Mix amylase with starch in test tube in water bath at 37 °C with buffer at set pH. Every 30 s remove a drop, mix with iodine on tile. Record time when iodine stays orange-brown. Repeat at different pH values.",
            "risk": "Iodine irritant — goggles and avoid skin contact. Water bath — check electrical safety. Hot water burn risk — use tongs.",
            "results": "Table: pH, time/s for starch breakdown. Fastest time at optimum pH (~7 for amylase).",
            "graph": "Bar chart or line graph of time (y) against pH (x). Lower time = faster activity.",
            "conclusion": "Enzyme activity depends on pH because extreme pH denatures active site shape. Amylase works fastest near neutral pH.",
            "evaluation": "Colour judgement subjective — use colorimeter or triplicate drops. Improve by fresh enzyme each run and precise buffer pH meter check.",
            "exam_questions": [
                "Why use a water bath at 37 °C?",
                "How do you know starch is gone?",
                "Why does very low pH slow the reaction?",
            ],
            "model_answers": [
                "Maintains constant optimum temperature for enzyme activity.",
                "Iodine no longer turns blue-black — starch absent.",
                "Low pH changes active site shape — enzyme denatured or less effective.",
            ],
        },
    ]


def _mini_mock() -> dict:
    questions = [
        {"text": "State the function of the nucleus.", "marks": 1},
        {"text": "Give one difference between xylem and phloem.", "marks": 2},
        {"text": "Describe how white blood cells defend against pathogens.", "marks": 3},
        {"text": "Explain why enzymes are denatured at high temperatures.", "marks": 3},
        {"text": "An image is 12 mm long and the real object is 6 µm long. Calculate the magnification.", "marks": 3},
        {"text": "Compare the hormonal and nervous systems.", "marks": 3},
        {"text": "Describe how natural selection can lead to antibiotic resistance.", "marks": 4},
        {"text": "Explain how deforestation affects biodiversity and climate.", "marks": 3},
        {"text": "A person has BMI calculated as 31. Suggest what this indicates and one health implication.", "marks": 3},
        {"text": "Describe how you would investigate osmosis in potato tissue.", "marks": 3},
        {"text": "Explain the role of insulin and glucagon in controlling blood glucose.", "marks": 4},
        {"text": "Evaluate the use of vaccination programmes in controlling disease.", "marks": 6},
        {"text": "In a species the allele for dark fur (D) is dominant to light fur (d). Cross Dd × dd and explain expected offspring phenotypes.", "marks": 3},
        {"text": "A quadrat survey gives daisy counts: 3, 4, 4, 5, 14. Calculate mean excluding anomaly and the range of the remaining data.", "marks": 3},
        {"text": "Describe how you would use a microscope to estimate the size of cheek epithelial cells.", "marks": 6},
    ]
    answers = [
        {"walkthrough": "The nucleus controls cell activities and contains genetic material (DNA).", "marks_breakdown": ["Controls activities or contains DNA."]},
        {"walkthrough": "Xylem transports water and minerals upward; phloem transports sugars both up and down. Xylem cells are dead with lignin; phloem contains living sieve tubes.", "marks_breakdown": ["Transport difference.", "Structural or directional difference."]},
        {"walkthrough": "Phagocytes engulf pathogens and digest them. Lymphocytes produce antibodies that bind to antigens on pathogens, causing clumping or marking for destruction. Some form memory cells.", "marks_breakdown": ["Phagocytosis described.", "Antibody production.", "Memory or antigen binding."]},
        {"walkthrough": "Enzymes have an active site with a specific shape. High temperature breaks bonds holding the tertiary structure, changing active site shape so the substrate no longer fits. The enzyme is denatured and cannot catalyse the reaction.", "marks_breakdown": ["Active site shape specific.", "High temperature changes shape.", "Substrate no longer fits / enzyme denatured."]},
        {"walkthrough": "Convert: 12 mm = 12 000 µm. Magnification = 12 000 ÷ 6 = ×2000.", "marks_breakdown": ["Unit conversion.", "Correct formula.", "×2000."]},
        {"walkthrough": "Nervous: electrical impulses, fast, short-lived, via neurones. Hormonal: chemical hormones in blood, slower, longer-lasting, widespread. Nervous good for rapid reflexes; hormones for gradual changes like menstruation.", "marks_breakdown": ["Nervous features.", "Hormonal features.", "Clear comparison."]},
        {"walkthrough": "Random mutations produce resistant bacteria. Antibiotics kill susceptible bacteria, leaving resistant ones to reproduce. Over generations allele frequency for resistance increases — evolution.", "marks_breakdown": ["Variation/mutation.", "Selection by antibiotic.", "Survivors reproduce.", "Population change over time."]},
        {"walkthrough": "Removing forests destroys habitats, reducing species diversity and food webs. Less photosynthesis means less CO₂ removed. Burning or decay releases CO₂, contributing to greenhouse effect and climate change.", "marks_breakdown": ["Habitat loss reduces biodiversity.", "Less CO₂ uptake.", "Climate link."]},
        {"walkthrough": "BMI above 30 indicates obesity. Health implications include increased risk of type 2 diabetes, cardiovascular disease or joint problems.", "marks_breakdown": ["Obesity identified.", "Valid health implication.", "Linked explanation."]},
        {"walkthrough": "Cut equal potato cylinders, record mass, place in different sugar concentrations for fixed time at same temperature. Blot and reweigh. Calculate percentage change. Plot mass change against concentration.", "marks_breakdown": ["Method with cylinders and solutions.", "Mass change measured.", "Controls named."]},
        {"walkthrough": "After a meal glucose rises; pancreas releases insulin causing cells to take up glucose and store as glycogen, lowering blood glucose. If glucose falls too low, glucagon is released, converting glycogen to glucose in the liver.", "marks_breakdown": ["Insulin lowers glucose.", "Glucagon raises glucose.", "Glycogen storage/release.", "Pancreas source."]},
        {"walkthrough": "Vaccination stimulates memory cells without severe disease, protecting individuals. Herd immunity reduces spread, protecting vulnerable people. Limitations: not 100% effective, some cannot vaccinate, booster needed, rare side effects. Overall public health benefit outweighs risks for most programmes.", "marks_breakdown": ["Individual protection.", "Herd immunity.", "Limitation stated.", "Side effects or access issues.", "Balanced judgement.", "Coherent evaluation."]},
        {"walkthrough": "Gametes: D or d from Dd parent; d from dd parent. Offspring: Dd or dd in 1:1 ratio — half dark fur (Dd), half light fur (dd).", "marks_breakdown": ["Gametes identified.", "1:1 phenotype ratio.", "Link to dominant/recessive."]},
        {"walkthrough": "14 is anomalous. Mean of 3,4,4,5 = 16÷4 = 4. Range = 5 − 3 = 2.", "marks_breakdown": ["Anomaly excluded.", "Mean = 4.", "Range = 2."]},
        {"walkthrough": "Scrape cheek lining gently with cotton bud, smear on slide, add methylene blue stain and coverslip. Calibrate graticule with micrometer at high power. Measure cell length in graticule units for ten cells, convert to µm, calculate mean. Repeat for reliability.", "marks_breakdown": ["Safe sampling and staining.", "Calibration at set magnification.", "Multiple measurements and mean.", "Reliability or safety.", "Units in µm.", "Logical sequence."]},
    ]
    total = sum(q["marks"] for q in questions)
    return {"total_marks": total, "questions": questions, "answers": answers}


def build_pack() -> dict:
    """Return the complete GCSE Biology walkthrough pack content."""
    return {
        "subject": "Biology",
        "slug": "biology",
        "topics": [
            topic_pack(T_CELL, _cell_biology()),
            topic_pack(T_ORG, _organisation()),
            topic_pack(T_INFECTION, _infection_and_response()),
            topic_pack(T_BIOENER, _bioenergetics()),
            topic_pack(T_HOME, _homeostasis_and_response()),
            topic_pack(T_INHERIT, _inheritance_variation_evolution()),
            topic_pack(T_ECOLOGY, _ecology()),
            topic_pack(T_PRACTICAL, _required_practical_skills()),
        ],
        "calculations": _calculations(),
        "practicals": _practicals(),
        "mini_mock": _mini_mock(),
    }
