import { shortQ, partsQ, calcQ } from "./exam.mjs";

export function buildAlevelMaths(topicId, ctx) {
  const builders = {
    "pure-algebra-functions": algebraFunctions,
    "pure-coordinate-trigonometry": coordTrig,
    "pure-calculus": calculus,
    "pure-sequences-exponentials": seqExp,
    statistics: statistics,
    mechanics: mechanics,
  };
  const build = builders[topicId];
  if (!build) throw new Error(`Unknown A-Level Maths topic ${topicId}`);
  const questions = build(ctx);
  if (questions.length < 30) throw new Error(`A-Level Maths ${topicId} has ${questions.length}`);
  return questions.slice(0, 32);
}

function algebraFunctions(ctx) {
  const a = ctx.n(2, 1);
  return [
    calcQ(`Solve x² − ${ctx.n(5, 1)}x − 6 = 0.`, 3, "Use quadratic formula / factorise if possible", ["Show both roots"]),
    calcQ(`Express 2x² + 8x + 3 in the form 2(x + p)² + q.`, 3, "2(x + 2)² − 5", ["Complete the square"]),
    calcQ(`Solve |3x − 1| = 5.`, 3, "x = 2 or x = −4/3", ["Two cases"]),
    calcQ(`Solve the inequality x² − 5x + 6 > 0.`, 3, "x < 2 or x > 3", ["Critical values 2 and 3, sketch"]),
    calcQ(`f(x) = ${a}x − 3, g(x) = x². Find fg(x) and gf(x).`, 3, `fg(x) = ${a}x² − 3; gf(x) = (${a}x − 3)²`, ["Order of composition"]),
    calcQ(`Find the inverse of f(x) = (x − 1)/(x + 2), x ≠ −2.`, 4, "f⁻¹(x) = (1 + 2x)/(1 − x), x ≠ 1", ["Swap x and y, rearrange"]),
    calcQ(`The remainder when x³ + ax² − 4x + 1 is divided by (x − 1) is 3. Find a.`, 3, "a = 5", ["f(1) = 3"]),
    calcQ(`(x − 2) is a factor of x³ − 3x² + kx − 4. Find k and fully factorise.`, 4, "k = 2; (x − 2)²(x + 1) wait check", ["f(2)=0 → 8 − 12 + 2k − 4 = 0 → 2k = 8 → k = 4", "Then factorise"]),
    shortQ("State the factor theorem.", 2, ["If f(a) = 0 then (x − a) is a factor"]),
    calcQ(`Simplify (x³ − 8)/(x − 2).`, 2, "x² + 2x + 4", ["Difference of cubes"]),
    calcQ(`Solve 2 ln x = ln 9.`, 2, "x = 3 (x > 0)", ["ln x² = ln 9"]),
    calcQ(`Solve log₁₀(x + 1) + log₁₀(x − 1) = 1.`, 4, "x = √11", ["log((x²−1))=1 so x²−1=10"]),
    shortQ("Sketch y = |x − 2| + 1, showing the vertex and intercepts.", 3, ["Vertex (2, 1)", "V shape", "y-intercept 3"]),
    calcQ(`The function f(x) = x³ − 3x + 1 has a turning point. Find dy/dx and the stationary points.`, 4, "dy/dx = 3x² − 3; x = ±1", ["Set derivative = 0"]),
    calcQ(`Partial fractions: express (5x + 3)/((x + 1)(x − 2)) in partial fractions.`, 4, "A=2/3? Let's compute: 5x+3 = A(x−2)+B(x+1). x=2: 13=3B, B=13/3; x=−1: −2=−3A, A=2/3", ["A/(x+1) + B/(x−2) = (2/3)/(x+1) + (13/3)/(x−2)"]),
    calcQ(`Binomial expansion of (1 + 2x)⁵ up to the term in x³.`, 3, "1 + 10x + 40x² + 80x³", ["C(5,k)(2x)^k"]),
    calcQ(`Find the term independent of x in (x + 2/x)⁶.`, 3, "C(6,3)×1³×2³ = 160", ["(6 choose r) x^{6−r} 2^r x^{−r}"]),
    shortQ("State the conditions for the binomial expansion of (1 + x)^n when n is not a positive integer.", 2, ["|x| < 1"]),
    calcQ(`Solve 3^{2x} − 12 × 3^x + 27 = 0.`, 4, "3^x = 3 or 9 so x = 1 or 2", ["Quadratic in 3^x"]),
    calcQ(`The modulus of a complex number is not required at this spec for all boards — instead solve 2^{x+1} = 5.`, 3, "x = log₂(5/2) or ln5/ln2 − 1", ["Take logs"]),
    partsQ(`f(x) = 2x + 1, domain x ≥ 0.`, [
      { label: "a", marks: 1, text: "Find the range of f.", points: ["f(x) ≥ 1"] },
      { label: "b", marks: 2, text: "Find f⁻¹(x) and its domain.", points: ["(x − 1)/2", "x ≥ 1"] },
    ]),
    calcQ(`Solve simultaneously y = x + 1 and x² + y² = 25.`, 4, "x = 3, y = 4 or x = −4, y = −3", ["Substitute"]),
    shortQ("Describe the transformation that maps y = f(x) to y = 2f(x − 3) + 1.", 3, ["Translation 3 right", "Stretch ×2 parallel to y-axis", "Translation 1 up"]),
    calcQ(`Prove that (1 + sin x)/(cos x) + (cos x)/(1 + sin x) = 2/cos x.`, 4, "Combine over a common denominator and use 1 − sin²x = cos²x", ["Identity proof — each step must be justified"]),
    calcQ(`Find the set of values of k for which kx² + 4x + k = 0 has real roots.`, 4, "k ≤ −2 or k ≥ 2, and k ≠ 0 if needed for quadratic", ["Discriminant 16 − 4k² ≥ 0"]),
    shortQ("Explain why a function must be one-to-one to have an inverse, and how a domain restriction can fix y = x².", 3, ["Each output from one input", "Restrict x ≥ 0 so it is one-to-one"]),
    calcQ(`Expand (2 − 3x)⁴.`, 3, "16 − 96x + 216x² − 216x³ + 81x⁴", ["Binomial"]),
    calcQ(`Solve x + 4/x = 5, x ≠ 0.`, 3, "x = 1 or x = 4", ["Multiply through by x"]),
    shortQ(`A ${ctx.board} Pure paper often awards method marks for a correct first line. Write the first line you should write when using the factor theorem to test (x + 3).`, 2, ["f(−3) = …"]),
    calcQ(`Given f(x) = x³ − 4x, find f(2 + h) − f(2) and hence the derivative from first principles at x = 2.`, 4, "f'(2) = 8", ["Limit as h→0 of [12h + 6h² + h³]/h"]),
    calcQ(`The roots of 2x² − 5x − 3 = 0 are α and β. Find α + β and αβ.`, 2, "5/2 and −3/2", ["−b/a and c/a"]),
    shortQ("State two common mistakes on a 4-mark algebra rearrangement and how to avoid them.", 2, ["Not changing the sign when crossing the equals", "Dividing only one term"]),
  ];
}

function coordTrig(ctx) {
  return [
    calcQ("Find the gradient of the line through (1, 2) and (5, 14).", 2, "3", ["(14−2)/(5−1)"]),
    calcQ("Find the equation of the line perpendicular to y = 3x − 1 that passes through (3, 4).", 3, "y − 4 = −(1/3)(x − 3)", ["m = −1/3"]),
    calcQ("Find the distance between (2, −1) and (6, 2).", 2, "5", ["√(16+9)"]),
    calcQ("Find the midpoint of (2, −1) and (6, 2).", 1, "(4, 0.5)", []),
    calcQ("A circle has equation (x − 3)² + (y + 1)² = 25. State the centre and radius.", 2, "Centre (3, −1), radius 5", []),
    calcQ("Find the equation of the circle with centre (1, 2) passing through (4, 6).", 3, "(x−1)²+(y−2)² = 25", ["Radius 5"]),
    calcQ("Show that the line y = 2x + 1 intersects the circle x² + y² = 5 and find the points.", 4, "Substitute; solve the quadratic", ["Show two intersection points or a repeated root for tangent"]),
    shortQ("State the condition for a line to be a tangent to a circle in terms of the discriminant.", 2, ["Repeated root / discriminant zero"]),
    calcQ("Convert 30° to radians and 2π/3 to degrees.", 2, "π/6 ; 120°", []),
    calcQ("Find the exact value of sin 150° and cos 210°.", 2, "1/2 ; −√3/2", ["CAST"]),
    calcQ("Solve sin θ = 0.5 for 0 ≤ θ ≤ 360°.", 3, "30° and 150°", ["Sine is positive in 1st and 2nd"]),
    calcQ("Solve 2 cos θ = −1 for 0 ≤ θ ≤ 2π.", 3, "2π/3 and 4π/3", []),
    calcQ("Prove sin²θ + cos²θ = 1 using a right triangle or the unit circle.", 3, "By definition on the unit circle x²+y²=1", []),
    calcQ("Express 2 sin θ cos θ as a single sine.", 1, "sin 2θ", ["Double angle"]),
    calcQ("Use cos 2θ = 2cos²θ − 1 to find the exact value of cos 15° if needed, or find cos 2θ when cos θ = 0.6.", 3, "2(0.36)−1 = −0.28", []),
    calcQ("Find the area of a triangle with sides 7 cm and 10 cm and included angle 30°.", 3, "17.5 cm²", ["½ab sin C"]),
    calcQ("Use the cosine rule to find the third side when a = 5, b = 8, C = 60°.", 3, "√49 = 7", ["c² = 25+64−80cos60 = 49"]),
    calcQ("Use the sine rule: a/sin A = b/sin B. A = 40°, a = 10, B = 60°. Find b.", 3, "b = 10 sin60 / sin40", ["Leave exact or 3 s.f."]),
    shortQ("Sketch y = 2 sin(x − 30°) for 0 ≤ x ≤ 360°, stating amplitude, period and shift.", 4, ["Amplitude 2", "Period 360°", "Shift 30° right"]),
    calcQ("Find the period of y = 3 cos(2x).", 2, "π or 180°", ["2π/2"]),
    calcQ("The line l1: x = 1 + 2t, y = −1 + t. Find a Cartesian equation.", 3, "y + 1 = (1/2)(x − 1)", ["Eliminate t"]),
    calcQ("Find the angle between the lines y = x and y = 2x.", 3, "tan⁻¹(2) − 45°", ["m1=1, m2=2, tanθ = |(m2−m1)/(1+m1m2)|"]),
    shortQ("State the small-angle approximations for sin θ, cos θ and tan θ when θ is in radians.", 3, ["sin θ ≈ θ", "cos θ ≈ 1 − θ²/2", "tan θ ≈ θ"]),
    calcQ("A sector of radius 6 cm has angle 0.5 rad. Find the arc length and sector area.", 3, "s=3 cm, A=9 cm²", ["s=rθ, A=½r²θ"]),
    calcQ("Find the equation of the tangent to the circle x² + y² = 25 at (3, 4).", 3, "3x + 4y = 25", ["Radius is perpendicular to tangent"]),
    calcQ("Solve tan 2θ = 1 for 0 ≤ θ ≤ 180°.", 3, "θ = 22.5° and 112.5°", ["2θ = 45°, 225°"]),
    shortQ("Write the identities for sin(A+B) and cos(A−B).", 3, ["sin A cos B + cos A sin B", "cos A cos B + sin A sin B"]),
    calcQ("Find R and α such that 3 sin θ + 4 cos θ = R sin(θ + α).", 4, "R = 5, tan α = 4/3", ["R=√(9+16)"]),
    calcQ("The points A(0,1), B(4,3), C(2,7) form a triangle. Find the area using the determinant / shoelace method.", 3, "10", ["½|0(3−7)+4(7−1)+2(1−3)|"]),
    shortQ(`On ${ctx.board} papers, a 5-mark trig equation needs all solutions in the interval. Write a checklist.`, 3, ["Find the principal value", "Use the correct quadrants", "Do not lose solutions after a double-angle substitution"]),
    calcQ("Find the centre and radius of x² + y² − 6x + 4y − 12 = 0.", 3, "Centre (3, −2), radius 5", ["Complete the square"]),
    calcQ("A triangle has sides 6, 7, 8. Find the largest angle using the cosine rule.", 3, "cos C = (36+49−64)/84 = 21/84 = 0.25", ["Largest angle opposite 8"]),
  ];
}

function calculus(ctx) {
  return [
    calcQ("Differentiate y = 5x⁴ − 3x² + 7.", 2, "20x³ − 6x", []),
    calcQ("Differentiate y = (2x + 1)³.", 3, "6(2x+1)²", ["Chain rule"]),
    calcQ("Differentiate y = x² sin x.", 3, "2x sin x + x² cos x", ["Product rule"]),
    calcQ("Differentiate y = (x² + 1)/(x − 1).", 4, "Quotient rule: [(2x)(x−1) − (x²+1)]/(x−1)²", []),
    calcQ("Find dy/dx if x = 2t + 1, y = t².", 3, "dy/dx = t", ["(dy/dt)/(dx/dt) = 2t / 2"]),
    calcQ("Find the gradient of y = x³ − 3x at x = 2.", 2, "9", ["3x² − 3"]),
    calcQ("Find the equation of the tangent to y = x² at (3, 9).", 3, "y − 9 = 6(x − 3)", ["Gradient 6"]),
    calcQ("Find the equation of the normal to y = x² at (3, 9).", 3, "y − 9 = −(1/6)(x − 3)", []),
    calcQ("Find the stationary points of y = x³ − 12x + 1 and determine their nature.", 5, "(2, −15) min, (−2, 17) max", ["d²y/dx² = 6x"]),
    calcQ("A rectangle has perimeter 20 cm. Show that the area A = 10x − x² and find the maximum area.", 5, "Maximum 25 cm² when x = 5", ["dA/dx = 10 − 2x = 0"]),
    calcQ("Integrate 6x² − 4x + 3.", 2, "2x³ − 2x² + 3x + c", []),
    calcQ("Find ∫ (2x + 1)⁴ dx.", 3, "(1/10)(2x+1)⁵ + c", ["Reverse chain rule"]),
    calcQ("Evaluate ∫₀² (3x² + 1) dx.", 3, "10", ["[x³ + x] from 0 to 2"]),
    calcQ("Find the area between y = x², the x-axis, x = 1 and x = 3.", 3, "26/3", ["∫ x² dx"]),
    calcQ("Find the area between y = x and y = x² from 0 to 1.", 3, "1/6", ["∫(x−x²)dx"]),
    calcQ("Use the trapezium rule with 4 strips to estimate ∫₀⁴ (x²) dx. Comment on whether this is an over- or underestimate.", 4, "h=1; estimate 22; overestimate because the curve is convex", ["(h/2)(y0+2y1+2y2+2y3+y4)"]),
    calcQ("If dy/dx = 6x² and y = 5 when x = 1, find y.", 3, "y = 2x³ + 3", ["Integrate + constant"]),
    calcQ("Differentiate y = e^{3x} and y = ln(5x).", 3, "3e^{3x} ; 1/x", ["ln(5x)=ln5+ln x"]),
    calcQ("Differentiate y = e^{x²}.", 2, "2x e^{x²}", ["Chain rule"]),
    calcQ("Find ∫ 1/(2x) dx, x > 0.", 2, "(1/2) ln|x| + c or (1/2) ln|2x| + c", []),
    calcQ("Implicit differentiation: x² + y² = 25. Find dy/dx at (3, 4).", 3, "−3/4", ["2x + 2y y' = 0"]),
    calcQ("Related rates: a sphere has V = (4/3)πr³. If dr/dt = 2, find dV/dt when r = 3.", 4, "dV/dt = 72π", ["dV/dt = 4πr² dr/dt"]),
    calcQ("Find the second derivative of y = sin 2x.", 2, "−4 sin 2x", []),
    shortQ("Explain how to decide whether a stationary point is a max, min or point of inflection using the second derivative.", 3, ["f'' > 0 min", "f'' < 0 max", "f'' = 0 inconclusive"]),
    calcQ("Integration by substitution: ∫ 2x(x² + 1)³ dx.", 3, "(1/4)(x²+1)⁴ + c", ["u = x²+1"]),
    calcQ("Find the average value of y = 3x² on [0, 2].", 3, "4", ["(1/2)∫ 3x² dx = 4"]),
    calcQ("A curve is y = 1/x. Find the volume generated when the region from x = 1 to x = 2 is rotated about the x-axis. Leave π in the answer if this is on the spec; otherwise find the area under the curve.", 3, "Area = ln 2; volume π∫ x⁻² dx = π(1 − 1/2) = π/2", []),
    shortQ("State the chain, product and quotient rules in Leibniz or function notation.", 3, ["dy/dx = dy/du × du/dx", "uv' + vu'", "(vu' − uv')/v²"]),
    calcQ(`A ${ctx.board} question gives displacement s = t³ − 6t². Find the velocity and acceleration at t = 1.`, 3, "v = −9, a = −6", ["v=3t²−12t, a=6t−12"]),
    calcQ("Solve dy/dx = 2y, y(0) = 3, by separating variables.", 4, "y = 3e^{2x}", ["∫ dy/y = ∫ 2 dx"]),
    shortQ("Why do you add + c for an indefinite integral but not for a definite integral?", 2, ["Family of antiderivatives", "Constants cancel in the evaluation"]),
    calcQ("Find the x-coordinate of the point on y = x² + 1 where the tangent is parallel to y = 4x.", 3, "x = 2", ["2x = 4"]),
  ];
}

function seqExp(ctx) {
  const a = ctx.n(3, 1);
  const d = ctx.n(4, 1);
  const r = 0.5;
  return [
    calcQ(`An AP has first term ${a} and common difference ${d}. Find the 10th term.`, 2, String(a + 9 * d), ["a + (n−1)d"]),
    calcQ("Find the sum of the first 20 terms of that AP.", 3, String((20 / 2) * (2 * a + 19 * d)), ["Sₙ = n/2 (2a + (n−1)d)"]),
    calcQ("How many terms of 5, 9, 13, … are needed to exceed 500?", 4, "Solve n/2 (10 + (n−1)4) > 500", ["Quadratic inequality"]),
    calcQ(`A GP has first term 2 and common ratio ${r}. Find the 6th term.`, 2, String(2 * r ** 5), ["ar^{n−1}"]),
    calcQ("Find the sum of the first 8 terms of that GP.", 3, `S = 2(1 − ${r}⁸)/(1 − ${r})`, []),
    calcQ("Find the sum to infinity of 1 + 1/3 + 1/9 + …", 2, "3/2", ["a/(1−r), |r|<1"]),
    shortQ("State the condition for a GP to have a sum to infinity.", 2, ["|r| < 1"]),
    calcQ("The 3rd term of an AP is 11 and the 7th term is 23. Find a and d.", 3, "d = 3, a = 5", ["a+2d=11, a+6d=23"]),
    calcQ("The first term of a GP is 5 and the 4th term is 40. Find r and the 6th term.", 3, "r = 2, 6th = 160", ["5r³ = 40"]),
    calcQ("Solve 3^{x} = 12. Give your answer as a logarithm.", 2, "x = log₃ 12 or ln12/ln3", []),
    calcQ("Simplify log₂ 8 + log₂ 4 − log₂ 2.", 2, "3+2−1 = 4", ["Laws of logs"]),
    calcQ("Write 2 log x + 3 log y − log z as a single logarithm.", 2, "log (x² y³ / z)", []),
    calcQ("Solve 2^{2x} − 5 × 2^x + 4 = 0.", 4, "2^x = 1 or 4 so x = 0 or 2", ["Quadratic in 2^x"]),
    calcQ("The nth term of a sequence is 3n − 1. Prove that the sum of the first n terms is n(3n + 1)/2.", 4, "AP with a=2, d=3; S=n/2 (4 + (n−1)3)", ["Algebraic proof"]),
    calcQ("Find ∑_{r=1}^{n} (2r + 1).", 3, "n(n+2) or n² + 2n", ["2∑r + ∑1"]),
    calcQ("A recurrence is u_{n+1} = 0.6 u_n + 4, u₁ = 10. Find u₂ and u₃.", 2, "u₂ = 10, u₃ = 10", ["Fixed point"]),
    calcQ("Find the limit L of u_{n+1} = 0.6 u_n + 4 as n → ∞, assuming it converges.", 3, "L = 10", ["L = 0.6L + 4"]),
    shortQ("Explain the difference between an arithmetic series and a geometric series.", 2, ["Constant difference vs constant ratio"]),
    calcQ("£2000 is invested at 3% compound interest. Find the value after 8 years and the year it first exceeds £2500.", 4, "2000×1.03⁸; solve 2000×1.03ⁿ > 2500", ["Logs for the year"]),
    calcQ("A ball is dropped from 10 m and bounces to 0.6 of its previous height. Find the total distance travelled before it stops.", 4, "10 + 2×10×0.6/(1−0.6) = 40 m", ["Infinite GP after the first drop"]),
    calcQ("Solve ln(x + 1) = 2.", 2, "x = e² − 1", []),
    calcQ("Differentiate y = 3^x. Use y = e^{x ln 3}.", 2, "3^x ln 3", []),
    calcQ("The sum of an AP is 156, n = 12, a = 3. Find d.", 3, "d = 2", ["12/2 (6 + 11d) = 156"]),
    calcQ("Show that 4, 10, 16, … and 3, 6, 12, … are AP and GP respectively, and find the 8th term of each.", 3, "AP 8th = 46; GP 8th = 384", []),
    shortQ("Write the formulae for the nth term of an AP and a GP.", 2, ["a+(n−1)d", "ar^{n−1}"]),
    calcQ("Solve log₃ (x − 1) + log₃ (x + 1) = 1.", 4, "x = 2 (check domain x>1)", ["(x²−1)=3"]),
    calcQ("A geometric series has S∞ = 20 and a = 8. Find r.", 3, "r = 0.6", ["8/(1−r)=20"]),
    calcQ("Find the smallest n such that 1.04^n > 2.", 3, "n = 18 because n > ln2/ln1.04 ≈ 17.67", []),
    shortQ(`A ${ctx.board} logs question often loses a mark for missing the domain. What must you check after solving a log equation?`, 2, ["Arguments positive", "Reject roots that make a log undefined"]),
    calcQ("Expand e^{2x} as a Maclaurin series up to x³ if on your spec; otherwise write the first four terms of the binomial expansion of (1 + 2x)^{1/2}.", 4, "1 + x − (1/2)x² + (1/2)x³ + … for the binomial with |2x|<1", ["Standard expansion"]),
    calcQ("An AP and a GP both have first term 4. The AP has d = 3. The GP has r = 2. Find the first term that appears in both sequences after 4.", 4, "Terms AP: 4,7,10,13,16,19,22,25,28,31,34… GP: 4,8,16,32… common 16", []),
    shortQ("Explain why |r| < 1 is needed for S∞, using a numerical counter-example if |r| ≥ 1.", 2, ["Terms do not tend to 0", "e.g. 2+4+8+… diverges"]),
  ];
}

function statistics(ctx) {
  return [
    shortQ("Explain the difference between a population and a sample, and between a parameter and a statistic.", 3, ["Population: whole group", "Sample: subset", "Parameter from population, statistic from sample"]),
    shortQ("Describe simple random sampling and one advantage and one disadvantage.", 3, ["Every sample of size n equally likely", "Unbiased", "Needs a sampling frame / can be impractical"]),
    shortQ("Describe stratified sampling and when it is better than simple random sampling.", 3, ["Sample in proportion to strata", "More representative when groups differ"]),
    shortQ("Describe opportunity/convenience sampling and why it can be biased.", 2, ["Use who is available", "Not every person has an equal chance"]),
    calcQ("A data set has values 2, 5, 7, 10, 16. Find the mean and the standard deviation (divisor n or n−1 as used on your board).", 4, "Mean 8; variance = 22.4 (n) or 28 (n−1)", ["Show the sum of squared deviations"]),
    calcQ("Coded data: y = (x − 20)/2. The mean of y is 3 and the sd of y is 1.4. Find the mean and sd of x.", 3, "Mean x = 26; sd x = 2.8", ["Reverse the coding"]),
    shortQ("Interpret a positive skew and a negative skew. Which average is pulled the most?", 3, ["Positive: tail to the right, mean > median", "Mean is pulled toward the tail"]),
    calcQ("Two events A and B: P(A)=0.4, P(B)=0.5, P(A∩B)=0.2. Find P(A∪B) and P(A|B).", 3, "0.7 ; 0.4", ["Addition rule; conditional"]),
    shortQ("State the conditions for a binomial distribution B(n, p).", 3, ["Fixed n", "Two outcomes", "Independent trials", "Constant p"]),
    calcQ("X ~ B(10, 0.3). Find P(X = 2). Leave your answer in a calculable form and evaluate to 3 s.f.", 3, "C(10,2)(0.3)²(0.7)⁸ ≈ 0.233", []),
    calcQ("X ~ B(10, 0.3). Find E(X) and Var(X).", 2, "3 and 2.1", ["np, np(1−p)"]),
    calcQ("X ~ B(20, 0.4). Use your calculator to find P(X ≤ 5).", 2, "0.1256 (3 s.f., calculator)", ["Binomial cdf"]),
    shortQ("When can a normal distribution be used as a model? Mention symmetry and the mean/median.", 2, ["Data roughly symmetric / bell-shaped", "Mean ≈ median"]),
    calcQ("X ~ N(50, 16). Find P(X < 46). Standardise and use Φ.", 3, "z = (46−50)/4 = −1; Φ(−1) = 1 − 0.8413 = 0.1587", []),
    calcQ("X ~ N(100, 25). Find the value a such that P(X < a) = 0.975.", 3, "a = 100 + 1.96×5 = 109.8", ["Inverse normal"]),
    shortQ("State the mean and variance of the standard normal Z.", 2, ["0 and 1"]),
    calcQ("A hypothesis test: H₀: p = 0.5, H₁: p > 0.5, n = 20, observed 14 successes, 5% level. Carry out the test using a binomial model.", 5, "P(X≥14 | B(20,0.5)) = 0.0577 > 0.05, not significant, do not reject H₀", ["State conclusion in context"]),
    shortQ("Explain what a Type I error and a Type II error are.", 3, ["Type I: reject H₀ when true", "Type II: fail to reject H₀ when false"]),
    shortQ("Why do we use a continuity correction when approximating a discrete distribution by a normal?", 2, ["Discrete values occupy a unit width", "P(X ≤ 10) ≈ P(Y < 10.5)"]),
    calcQ("PMCC: a scatter graph of revision hours and mark has r = 0.82. Interpret r.", 2, ["Strong positive linear correlation"]),
    shortQ("The least-squares regression line is y = 12 + 4.5x. Interpret the gradient and the intercept in context if x is hours and y is mark.", 3, ["Gradient: extra 4.5 marks per hour", "Intercept: predicted mark with 0 hours — may not be meaningful"]),
    shortQ("Why should you not use a regression line to predict far outside the data range?", 2, ["Extrapolation", "The linear model may not hold"]),
    calcQ("A discrete random variable X has P(X=1)=0.2, P(X=2)=0.5, P(X=3)=0.3. Find E(X) and Var(X).", 4, "E(X)=2.1; E(X²)=4.9; Var=0.49", []),
    calcQ("For that X, find P(X ≥ 2).", 1, "0.8", []),
    shortQ("Describe a histogram versus a box plot: what can you see on each?", 3, ["Histogram: shape, modality, skew", "Box plot: median, IQR, outliers, easy comparison"]),
    calcQ("Large data set style: a sample of 40 daily maxima has mean 18.2°C. Explain why this mean might not estimate the yearly mean temperature well.", 2, ["Only maxima not typical days", "Seasonal bias if the 40 days are not spread through the year"]),
    shortQ("Write H₀ and H₁ for a two-tailed test that a coin is fair, and state the meaning of the significance level.", 3, ["H₀: p=0.5, H₁: p≠0.5", "Significance level is P(Type I error)"]),
    calcQ("Y ~ N(0, 1). Find P(−1.96 < Y < 1.96).", 2, "0.95", ["Standard result"]),
    shortQ(`On ${ctx.board} Statistics, you must conclude in context. Write a model concluding sentence for a non-significant result about a plant fertiliser.`, 2, ["There is insufficient evidence at the 5% level that the fertiliser increases mean growth"]),
    calcQ("The IQR is 12 and the range is 40. Comment on the presence of possible outliers compared with a data set with IQR 12 and range 16.", 2, ["Much larger range suggests outliers or long tails"]),
    shortQ("Explain mutually exclusive vs independent, with a probability condition for each.", 3, ["ME: P(A∩B)=0", "Independent: P(A∩B)=P(A)P(B)"]),
    calcQ("A Venn diagram: 50 students, 30 do maths, 22 do physics, 12 do both. A student is chosen at random. Find P(physics | maths).", 3, "12/30 = 0.4", []),
  ];
}

function mechanics(ctx) {
  const u = ctx.n(12, 2);
  return [
    calcQ(`A particle has constant acceleration 3 m s⁻². It starts at 4 m s⁻¹. Find its velocity after 5 s.`, 2, "19 m s⁻¹", ["v = u + at"]),
    calcQ(`It travels with u = ${u} m s⁻¹, a = −2 m s⁻² for 4 s. Find the displacement.`, 3, `${u * 4 - 16} m`, ["s = ut + ½at²"]),
    calcQ("A car accelerates from rest to 20 m s⁻¹ in 8 s. Find the acceleration and the distance travelled.", 3, "a = 2.5 m s⁻²; s = 80 m", []),
    calcQ("A ball is thrown vertically upwards at 14 m s⁻¹. Take g = 9.8 m s⁻². Find the time to the top and the greatest height.", 4, "t = 14/9.8 = 1.43 s; h = 10 m", ["v=0 at top"]),
    shortQ("State the difference between distance and displacement, and between speed and velocity.", 3, ["Displacement is a vector", "Velocity is a vector / has direction"]),
    calcQ("A particle moves with v = 3t² − 4. Find the acceleration at t = 2 and the displacement from t = 0 to 2 if s(0)=0.", 4, "a = 12; s = 0", ["a=dv/dt=6t; s=∫v dt = t³ − 4t"]),
    calcQ("Two forces 5 N and 12 N act at right angles. Find the magnitude of the resultant.", 2, "13 N", ["Pythagoras"]),
    calcQ("Resolve a 20 N force at 30° to the horizontal into horizontal and vertical components.", 3, "10√3 N horizontal, 10 N vertical", ["20 cos30, 20 sin30"]),
    calcQ("A 3 kg particle is on a smooth horizontal surface. A 6 N force acts. Find the acceleration.", 2, "2 m s⁻²", ["F=ma"]),
    calcQ("The same 3 kg particle is on a rough surface, μ = 0.2, g = 10. A horizontal 9 N force acts. Find the acceleration.", 4, "Friction = 6 N; a = 1 m s⁻²", ["R=30 N"]),
    shortQ("State the modelling assumptions for a particle and for a smooth surface.", 2, ["Particle: mass concentrated at a point, no size/air resistance unless stated", "Smooth: no friction"]),
    calcQ("A 4 kg block is on a plane inclined at 30°. The plane is smooth. Find the acceleration down the plane. g = 10.", 3, "5 m s⁻²", ["g sin30"]),
    calcQ("If that plane is rough with μ = 1/√3, show that the block is in limiting equilibrium or find the acceleration.", 4, "F = μR = (1/√3)(4g cos30) = 4g/2 = 2g; component down = 2g, so limiting equilibrium if g=10: check numbers", ["Compare mg sinθ with μ mg cosθ"]),
    calcQ("Connected particles: A (2 kg) on a table, B (3 kg) hanging, string smooth, pulley light. Find the acceleration. g=10.", 4, "a = 6 m s⁻²; T = 12 N", ["3g − T = 3a, T = 2a"]),
    shortQ("Why is the tension the same throughout a light inextensible string that passes over a smooth pulley?", 2, ["Light: no mass so net force on a string element is zero", "Smooth pulley: no friction"]),
    calcQ("A projectile is launched at 20 m s⁻¹ at 30° to the horizontal. g = 10. Find the time of flight on level ground and the range.", 5, "T = 2 s; R = 20√3 m", ["uy=10, T=2uy/g"]),
    calcQ("For that projectile, find the greatest height.", 3, "5 m", ["uy²/2g"]),
    calcQ("Find the speed of that projectile after 1 s.", 3, "√( (10√3)² + 0² ) = 10√3 m s⁻¹ at the top? At 1 s, vy=0, vx=10√3", ["vx constant"]),
    shortQ("Write the suvat equations and state when they may be used.", 3, ["Constant acceleration only", "v=u+at, s=ut+½at², v²=u²+2as, s=(u+v)t/2"]),
    calcQ("Momentum: a 2 kg trolley at 3 m s⁻¹ collides and sticks to a 1 kg trolley at rest. Find the common speed.", 3, "2 m s⁻¹", ["Conservation of momentum"]),
    calcQ("The collision lasts 0.1 s. Find the impulse on the 1 kg trolley and the mean force.", 3, "Impulse 2 N s; mean force 20 N", ["I = Δmv"]),
    shortQ("State the difference between elastic and inelastic collisions in terms of kinetic energy.", 2, ["Elastic: KE conserved", "Inelastic: KE not conserved"]),
    calcQ("A 50 N force does work moving a box 4 m along its line of action. Find the work done. If the force is at 60° to the displacement, find the work done.", 3, "200 J ; 100 J", ["W = Fd cosθ"]),
    calcQ("A 2 kg mass falls 5 m. Find the loss in GPE and the speed if all becomes KE. g=10.", 3, "100 J; v=10 m s⁻¹", ["mgh = ½mv²"]),
    calcQ("Power: a car travels at a constant 15 m s⁻¹ against a 400 N resistance. Find the driving force and the power.", 3, "F=400 N; P=6000 W", ["P=Fv"]),
    calcQ("A moment: a uniform 4 m beam of weight 20 N is supported at each end. A 10 N weight sits 1 m from A. Find the reactions at A and B.", 4, "Take moments about A: 4B = 20×2 + 10×1; B=12.5 N, A=17.5 N", ["Equilibrium"]),
    shortQ("State the two conditions for equilibrium of a rigid body.", 2, ["Net force zero", "Net moment zero"]),
    calcQ("A particle has position r = (3t² − 2)i + (4t)j m. Find the velocity and speed at t = 1.", 3, "v = 6i + 4j; speed = √52 = 2√13 m s⁻¹", []),
    shortQ(`A ${ctx.board} mechanics question usually tells you to take g = 9.8 or 10. Why must you state the value you use?`, 2, ["The numerical answer depends on g", "Method marks may still be awarded if g is shown"]),
    calcQ("A lift of mass 800 kg accelerates upwards at 0.5 m s⁻². Find the tension in the cable. g=10.", 3, "T − 8000 = 400; T = 8400 N", ["N2L"]),
    calcQ("A graph of v against t is a straight line from (0, 0) to (10, 15). Find the distance travelled and the acceleration.", 3, "s = 75 m; a = 1.5 m s⁻²", ["Area under graph; gradient"]),
    shortQ("Explain the difference between mass and weight, including units.", 2, ["Mass in kg is scalar amount of matter", "Weight is mg, a force in N"]),
  ];
}
