/* Official Eduqas GCSE Mathematics past papers and mark schemes.
   Generated from the Eduqas qualification past-papers tab (qualificationId 38449).
   Links use WJEC's public pastpapers.download.wjec.co.uk filestore — exam PDFs are not copied into this repo.
   Regenerate with: node scripts/eduqas-gcse-maths-sync.mjs */

export const EDUQAS_GCSE_MATHEMATICS_RESOURCES = [
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2017",
    file_name: "a17-mathematics13-ms.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-mathematics13-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2017",
    file_name: "a17-mathematics14-ms.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-mathematics14-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2017",
    file_name: "a17-mathematics15-ms.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-mathematics15-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2017",
    file_name: "a17-mathematics16-ms.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-mathematics16-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2017",
    file_name: "a17-5300-01.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2017",
    file_name: "a17-5300-02.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2017",
    file_name: "a17-5300-03.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2017",
    file_name: "a17-5300-04.pdf",
    series_label: "Autumn 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a17-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2018 (Resource Insert)",
    file_name: "a18-mathematics1-ms.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-mathematics1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2018",
    file_name: "a18-mathematics2-ms.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-mathematics2-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2018",
    file_name: "a18-mathematics3-ms.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-mathematics3-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2018",
    file_name: "a18-mathematics4-ms.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-mathematics4-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2018",
    file_name: "a18-5300-01.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2018",
    file_name: "a18-5300-02.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2018",
    file_name: "a18-5300-03.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2018",
    file_name: "a18-5300-04.pdf",
    series_label: "Autumn 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a18-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2019",
    file_name: "A19-C300U10-1-MS.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A19-C300U10-1-MS.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2019",
    file_name: "A19-C300U20-1-MS.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A19-C300U20-1-MS.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2019",
    file_name: "A19-C300UA0-1-MS.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A19-C300UA0-1-MS.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2019",
    file_name: "A19-C300UB0-1-MS.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A19-C300UB0-1-MS.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2019",
    file_name: "a19-5300-01.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a19-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2019",
    file_name: "a19-5300-02.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a19-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2019",
    file_name: "a19-5300-03.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a19-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2019",
    file_name: "a19-5300-04.pdf",
    series_label: "Autumn 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/a19-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2020",
    file_name: "a20-C300U10-1-ms.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2020",
    file_name: "a20-C300U20-1-ms.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2020",
    file_name: "a20-C300UA0-1-ms.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2020",
    file_name: "a20-C300UB0-1-ms.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2020",
    file_name: "a20-5300-01.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2020",
    file_name: "a20-5300-02.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2020",
    file_name: "a20-5300-03.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2020",
    file_name: "a20-5300-04.pdf",
    series_label: "Autumn 2020",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A20/a20-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2021",
    file_name: "a21-C300U10-1-ms.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2021",
    file_name: "a21-C300U20-1-ms.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2021",
    file_name: "a21-C300UA0-1-ms.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2021",
    file_name: "a21-C300UB0-1-ms.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2021",
    file_name: "a21-5300-01.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2021",
    file_name: "a21-5300-02.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2021",
    file_name: "a21-5300-03.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2021",
    file_name: "a21-5300-04.pdf",
    series_label: "Autumn 2021",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A21/a21-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2022",
    file_name: "a22-C300U10-1-ms.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2022",
    file_name: "a22-C300U20-1-ms.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2022",
    file_name: "a22-C300UA0-1-ms.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2022",
    file_name: "a22-C300UB0-1-ms.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2022",
    file_name: "a22-c300u10-1.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-c300u10-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2022",
    file_name: "a22-c300u20-1.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-c300u20-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2022",
    file_name: "a22-c300ua0-1.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-c300ua0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2022",
    file_name: "a22-c300ub0-1.pdf",
    series_label: "Autumn 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A22/a22-c300ub0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2023",
    file_name: "a23-C300U10-1-ms.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2023",
    file_name: "a23-C300U20-1-ms.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2023",
    file_name: "a23-C300UA0-1-ms.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2023",
    file_name: "a23-C300UB0-1-ms.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2023",
    file_name: "a23-C300U10-1.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300U10-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2023 (Resource Insert)",
    file_name: "a23-C300U10-1A.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300U10-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2023",
    file_name: "a23-C300U20-1.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300U20-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2023 (Resource Insert)",
    file_name: "a23-C300U20-1A.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300U20-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2023",
    file_name: "a23-C300UA0-1.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300UA0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2023 (Resource Insert)",
    file_name: "a23-C300UA0-1A.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300UA0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2023",
    file_name: "a23-C300UB0-1.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300UB0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2023 (Resource Insert)",
    file_name: "a23-C300UB0-1A.pdf",
    series_label: "Autumn 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A23/a23-C300UB0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2024",
    file_name: "A24-C300U10-1-ms.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2024",
    file_name: "A24-C300U20-1-ms.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2024",
    file_name: "A24-C300UA0-1-ms.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2024",
    file_name: "A24-C300UB0-1-ms.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2024",
    file_name: "A24-C300U10-1.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300U10-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2024 (Resource Insert)",
    file_name: "A24-C300U10-1A.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300U10-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2024",
    file_name: "A24-C300U20-1.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300U20-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2024 (Resource Insert)",
    file_name: "A24-C300U20-1A.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300U20-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2024",
    file_name: "A24-C300UA0-1.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300UA0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2024 (Resource Insert)",
    file_name: "A24-C300UA0-1A.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300UA0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2024",
    file_name: "A24-C300UB0-1.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300UB0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2024 (Resource Insert)",
    file_name: "A24-C300UB0-1A.pdf",
    series_label: "Autumn 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/A24/A24-C300UB0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2017",
    file_name: "s17-mathematics17-ms.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-mathematics17-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2017",
    file_name: "s17-mathematics18-ms.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-mathematics18-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2017",
    file_name: "s17-mathematics19-ms.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-mathematics19-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2017",
    file_name: "s17-mathematics20-ms.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-mathematics20-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2017",
    file_name: "s17-5300-01.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2017",
    file_name: "s17-5300-02.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2017",
    file_name: "s17-5300-03.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2017",
    file_name: "s17-5300-04.pdf",
    series_label: "Summer 2017",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s17-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2018",
    file_name: "s18-mathematics---c300u10-1-eduqas-gcse-maths-1-ms.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-mathematics---c300u10-1-eduqas-gcse-maths-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2018",
    file_name: "s18-mathematics---c300u20-1-eduqas-gcse-maths-1-ms.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-mathematics---c300u20-1-eduqas-gcse-maths-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2018",
    file_name: "s18-mathematics---c300ua0-1-eduqas-gcse-maths-1-ms.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-mathematics---c300ua0-1-eduqas-gcse-maths-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2018",
    file_name: "s18-mathematics---c300ub0-1-eduqas-gcse-maths-1-ms.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-mathematics---c300ub0-1-eduqas-gcse-maths-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2018",
    file_name: "s18-5300-01.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2018",
    file_name: "s18-5300-02.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2018",
    file_name: "s18-5300-03.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2018",
    file_name: "s18-5300-04.pdf",
    series_label: "Summer 2018",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s18-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2019",
    file_name: "s19-C300U10-1 EDUQAS GCSE Maths - Comp 1 FT MS S19.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-C300U10-1%20EDUQAS%20GCSE%20Maths%20-%20Comp%201%20FT%20MS%20S19.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2019",
    file_name: "s19-C300U20-1 EDUQAS GCSE Maths - Comp 2 FT MS S19.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-C300U20-1%20EDUQAS%20GCSE%20Maths%20-%20Comp%202%20FT%20MS%20S19.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2019",
    file_name: "s19-C300UA0-1 EDUQAS GCSE Maths - Comp 1 HT MS S19.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-C300UA0-1%20EDUQAS%20GCSE%20Maths%20-%20Comp%201%20HT%20MS%20S19.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2019",
    file_name: "s19-C300UB0-1 EDUQAS GCSE Maths - Comp 2 HT MS S19.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-C300UB0-1%20EDUQAS%20GCSE%20Maths%20-%20Comp%202%20HT%20MS%20S19.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2019",
    file_name: "s19-5300-01.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2019",
    file_name: "s19-5300-02.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2019",
    file_name: "s19-5300-03.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2019",
    file_name: "s19-5300-04.pdf",
    series_label: "Summer 2019",
    file_url_override: "https://pastpapers.download.wjec.co.uk/s19-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2022",
    file_name: "s22-C300U10-1-ms.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S22/s22-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2022",
    file_name: "s22-C300U20-1-ms.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S22/s22-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2022",
    file_name: "s22-C300UA0-1-ms.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S22/s22-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2022",
    file_name: "s22-C300UB0-1-ms.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S22/s22-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2022",
    file_name: "z22-5300-01.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/Z22/z22-5300-01.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2022",
    file_name: "z22-5300-02.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/Z22/z22-5300-02.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2022",
    file_name: "z22-5300-03.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/Z22/z22-5300-03.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2022",
    file_name: "z22-5300-04.pdf",
    series_label: "Summer 2022",
    file_url_override: "https://pastpapers.download.wjec.co.uk/Z22/z22-5300-04.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2023",
    file_name: "s23-c300u10-1-ms.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300u10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2023",
    file_name: "s23-c300u20-1-ms.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300u20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2023",
    file_name: "s23-c300ua0-1-ms.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300ua0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2023",
    file_name: "s23-c300ub0-1-ms.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300ub0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2023",
    file_name: "s23-c300u10-1.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300u10-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2023",
    file_name: "s23-c300u20-1.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300u20-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2023",
    file_name: "s23-c300ua0-1.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300ua0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2023",
    file_name: "s23-c300ub0-1.pdf",
    series_label: "Summer 2023",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S23/s23-c300ub0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2024",
    file_name: "S24-C300U10-1-ms.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2024",
    file_name: "S24-C300U20-1-ms.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2024",
    file_name: "S24-C300UA0-1-ms.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2024",
    file_name: "S24-C300UB0-1-ms.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2024",
    file_name: "S24-C300U10-1.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300U10-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2024 (Resource Insert)",
    file_name: "S24-C300U10-1A.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300U10-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2024",
    file_name: "S24-C300U20-1.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300U20-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2024 (Resource Insert)",
    file_name: "S24-C300U20-1A.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300U20-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2024",
    file_name: "S24-C300UA0-1.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300UA0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2024 (Resource Insert)",
    file_name: "S24-C300UA0-1A.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300UA0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2024",
    file_name: "S24-C300UB0-1.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300UB0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2024 (Resource Insert)",
    file_name: "S24-C300UB0-1A.pdf",
    series_label: "Summer 2024",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S24/S24-C300UB0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Mark Scheme — 2025",
    file_name: "S25-C300U10-1-ms.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300U10-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Mark Scheme — 2025",
    file_name: "S25-C300U20-1-ms.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300U20-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 1 Mark Scheme — 2025",
    file_name: "S25-C300UA0-1-ms.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300UA0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Mark Schemes",
    title: "Eduqas GCSE Mathematics Higher Component 2 Mark Scheme — 2025",
    file_name: "S25-C300UB0-1-ms.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300UB0-1-ms.pdf",
    description: "Official Eduqas/WJEC mark scheme. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2025",
    file_name: "S25-C300U10-1.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300U10-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 1 Past Paper — 2025 (Resource Insert)",
    file_name: "S25-C300U10-1A.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300U10-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2025",
    file_name: "S25-C300U20-1.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300U20-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Foundation Component 2 Past Paper — 2025 (Resource Insert)",
    file_name: "S25-C300U20-1A.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300U20-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2025",
    file_name: "S25-C300UA0-1.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300UA0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 1 Past Paper — 2025 (Resource Insert)",
    file_name: "S25-C300UA0-1A.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300UA0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2025",
    file_name: "S25-C300UB0-1.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300UB0-1.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  },
  {
    level: "GCSE/IGCSE",
    subject: "Maths",
    exam_board: "Eduqas",
    resource_category: "Past Questions",
    title: "Eduqas GCSE Mathematics Higher Component 2 Past Paper — 2025 (Resource Insert)",
    file_name: "S25-C300UB0-1A.pdf",
    series_label: "Summer 2025",
    file_url_override: "https://pastpapers.download.wjec.co.uk/S25/S25-C300UB0-1A.pdf",
    description: "Official Eduqas/WJEC past paper. External link opens Eduqas/WJEC resource.",
    source_attribution: "Official Eduqas/WJEC"
  }
];
