export const ELEVEN_PLUS_SECTIONS = [
  { id: "maths", title: "Maths", path: "/resources/11-plus/maths/" },
  { id: "english", title: "English", path: "/resources/11-plus/english/" },
  { id: "verbal-reasoning", title: "Verbal Reasoning", path: "/resources/11-plus/verbal-reasoning/" },
  { id: "non-verbal-reasoning", title: "Non-Verbal Reasoning", path: "/resources/11-plus/non-verbal-reasoning/" },
  { id: "mixed-practice", title: "Mixed Practice", path: "/resources/11-plus/mixed-practice/" },
  { id: "parent-guide", title: "Parent Guide", path: "/resources/11-plus/parent-guide/" },
];

export const ELEVEN_PLUS_RESOURCES = [
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Maths: Arithmetic Practice",
    skill_area: "Arithmetic and number",
    description: "Original JDScience practice on the four operations, BIDMAS, factors, primes, negatives, squares and rounding.",
    file_name: "JDScience_11Plus_Maths_Arithmetic_Practice.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_Maths_Arithmetic_Practice.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Maths: Word Problems",
    skill_area: "Problem solving",
    description: "Original JDScience word problems on money, time, ratio, age, distance and everyday number stories.",
    file_name: "JDScience_11Plus_Maths_Word_Problems.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_Maths_Word_Problems.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Maths: Fractions, Decimals and Percentages",
    skill_area: "Fractions, decimals and percentages",
    description: "Original JDScience practice converting, comparing and calculating with fractions, decimals and percentages.",
    file_name: "JDScience_11Plus_Maths_Fractions_Decimals_Percentages.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_Maths_Fractions_Decimals_Percentages.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Maths: Geometry and Measures",
    skill_area: "Shape, space and measures",
    description: "Original JDScience practice on perimeter, area, angles, conversions, time, coordinates and 3D shape.",
    file_name: "JDScience_11Plus_Maths_Geometry_and_Measures.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_Maths_Geometry_and_Measures.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Maths: Data Handling",
    skill_area: "Statistics and probability",
    description: "Original JDScience practice on tables, averages, charts, range and simple probability.",
    file_name: "JDScience_11Plus_Maths_Data_Handling.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_Maths_Data_Handling.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "English",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ English: Comprehension Practice",
    skill_area: "Reading comprehension",
    description: "An original JDScience fiction extract with retrieval, inference, vocabulary and language questions.",
    file_name: "JDScience_11Plus_English_Comprehension_Practice.pdf",
    file_url_override: "/resources/11-plus/english/JDScience_11Plus_English_Comprehension_Practice.pdf",
    series_label: "JDScience 11+ originals",
    section: "english",
  },
  {
    level: "11+",
    subject: "English",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ English: Grammar and Punctuation",
    skill_area: "Grammar and punctuation",
    description: "Original JDScience questions on apostrophes, commas, clauses, tenses, sentence types and homophones.",
    file_name: "JDScience_11Plus_English_Grammar_Punctuation.pdf",
    file_url_override: "/resources/11-plus/english/JDScience_11Plus_English_Grammar_Punctuation.pdf",
    series_label: "JDScience 11+ originals",
    section: "english",
  },
  {
    level: "11+",
    subject: "English",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ English: Vocabulary and Spelling",
    skill_area: "Vocabulary and spelling",
    description: "Original JDScience synonyms, antonyms, word meanings, prefixes, suffixes and common 11+ spellings.",
    file_name: "JDScience_11Plus_English_Vocabulary_and_Spelling.pdf",
    file_url_override: "/resources/11-plus/english/JDScience_11Plus_English_Vocabulary_and_Spelling.pdf",
    series_label: "JDScience 11+ originals",
    section: "english",
  },
  {
    level: "11+",
    subject: "English",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ English: Creative Writing Prompts",
    skill_area: "Creative writing",
    description: "Original JDScience story and description prompts with planning frames, success criteria and sample openings.",
    file_name: "JDScience_11Plus_English_Creative_Writing_Prompts.pdf",
    file_url_override: "/resources/11-plus/english/JDScience_11Plus_English_Creative_Writing_Prompts.pdf",
    series_label: "JDScience 11+ originals",
    section: "english",
  },
  {
    level: "11+",
    subject: "Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Verbal Reasoning: Practice 1",
    skill_area: "Codes, sequences and word relationships",
    description: "Original JDScience VR practice: letter sequences, analogies, codes, hidden words and odd-one-out.",
    file_name: "JDScience_11Plus_Verbal_Reasoning_Practice_1.pdf",
    file_url_override: "/resources/11-plus/verbal-reasoning/JDScience_11Plus_Verbal_Reasoning_Practice_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Verbal Reasoning: Practice 2",
    skill_area: "Logic, anagrams, codes and word puzzles",
    description: "A second original JDScience VR paper: compound words, letter moves, number patterns, analogies and codes.",
    file_name: "JDScience_11Plus_Verbal_Reasoning_Practice_2.pdf",
    file_url_override: "/resources/11-plus/verbal-reasoning/JDScience_11Plus_Verbal_Reasoning_Practice_2.pdf",
    series_label: "JDScience 11+ originals",
    section: "verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Non-Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Non-Verbal Reasoning: Practice 1",
    skill_area: "Series, odd one out, analogies and matrices",
    description: "Original JDScience NVR figures: which comes next, odd one out, analogies and 2×2 matrices.",
    file_name: "JDScience_11Plus_Non_Verbal_Reasoning_Practice_1.pdf",
    file_url_override: "/resources/11-plus/non-verbal-reasoning/JDScience_11Plus_Non_Verbal_Reasoning_Practice_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "non-verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Non-Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Non-Verbal Reasoning: Practice 2",
    skill_area: "Rotation, counting, codes and pattern completion",
    description: "A second original JDScience NVR paper with new figures: rotations, counting, shading and missing squares.",
    file_name: "JDScience_11Plus_Non_Verbal_Reasoning_Practice_2.pdf",
    file_url_override: "/resources/11-plus/non-verbal-reasoning/JDScience_11Plus_Non_Verbal_Reasoning_Practice_2.pdf",
    series_label: "JDScience 11+ originals",
    section: "non-verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Mixed Practice",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Mixed Practice Paper 1",
    skill_area: "Mixed 11+ practice",
    description: "An original JDScience mini mock mixing Maths, English, Verbal Reasoning and Non-Verbal Reasoning.",
    file_name: "JDScience_11Plus_Mixed_Practice_Paper_1.pdf",
    file_url_override: "/resources/11-plus/mixed-practice/JDScience_11Plus_Mixed_Practice_Paper_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "mixed-practice",
  },
  {
    level: "11+",
    subject: "Mixed Practice",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Mixed Practice Paper 2",
    skill_area: "Mixed 11+ practice",
    description: "A second original JDScience mini mock with a fresh mix of Maths, English, VR and NVR.",
    file_name: "JDScience_11Plus_Mixed_Practice_Paper_2.pdf",
    file_url_override: "/resources/11-plus/mixed-practice/JDScience_11Plus_Mixed_Practice_Paper_2.pdf",
    series_label: "JDScience 11+ originals",
    section: "mixed-practice",
  },
  {
    level: "11+",
    subject: "Parent Guide",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Revision Notes",
    title: "11+ Parent Guide",
    skill_area: "How to use JDScience 11+ papers",
    description: "A short original JDScience guide for families: what the 11+ covers, how to use these papers, timing, marking and wellbeing.",
    file_name: "JDScience_11Plus_Parent_Guide.pdf",
    file_url_override: "/resources/11-plus/mixed-practice/JDScience_11Plus_Parent_Guide.pdf",
    series_label: "JDScience 11+ originals",
    section: "parent-guide",
  },
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ GL-Style Maths Practice Paper 1",
    skill_area: "GL-style mixed maths",
    description: "Original JDScience timed Maths paper: arithmetic, fractions, decimals, percentages, ratio, word problems, geometry, measures, data and problem solving.",
    file_name: "JDScience_11Plus_GL_Style_Maths_Practice_Paper_1.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_GL_Style_Maths_Practice_Paper_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "Maths",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Mark Schemes",
    title: "11+ GL-Style Maths Practice Paper 1 — Answers",
    skill_area: "GL-style mixed maths answers",
    description: "Answers and short explanations for JDScience GL-Style Maths Practice Paper 1. Use after the timed paper.",
    file_name: "JDScience_11Plus_GL_Style_Maths_Answers_1.pdf",
    file_url_override: "/resources/11-plus/maths/JDScience_11Plus_GL_Style_Maths_Answers_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "maths",
  },
  {
    level: "11+",
    subject: "English",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ GL-Style English Practice Paper 1",
    skill_area: "GL-style reading, SPaG and writing",
    description: "Original JDScience timed English paper: an original reading passage, comprehension, vocabulary, grammar, punctuation, spelling, sentence improvement and a short writing task.",
    file_name: "JDScience_11Plus_GL_Style_English_Practice_Paper_1.pdf",
    file_url_override: "/resources/11-plus/english/JDScience_11Plus_GL_Style_English_Practice_Paper_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "english",
  },
  {
    level: "11+",
    subject: "English",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Mark Schemes",
    title: "11+ GL-Style English Practice Paper 1 — Answers",
    skill_area: "GL-style English answers",
    description: "Answers and short explanations for JDScience GL-Style English Practice Paper 1, including indicative content for the writing task.",
    file_name: "JDScience_11Plus_GL_Style_English_Answers_1.pdf",
    file_url_override: "/resources/11-plus/english/JDScience_11Plus_GL_Style_English_Answers_1.pdf",
    series_label: "JDScience 11+ originals",
    section: "english",
  },
  {
    level: "11+",
    subject: "Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Verbal Reasoning Practice Paper 3",
    skill_area: "Meanings, codes, sequences and word relationships",
    description: "Original JDScience VR Practice Paper 3: word meanings, synonyms and antonyms, letter and number codes, odd one out, word pairs, compound words and alphabet sequences.",
    file_name: "JDScience_11Plus_Verbal_Reasoning_Practice_Paper_3.pdf",
    file_url_override: "/resources/11-plus/verbal-reasoning/JDScience_11Plus_Verbal_Reasoning_Practice_Paper_3.pdf",
    series_label: "JDScience 11+ originals",
    section: "verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Mark Schemes",
    title: "11+ Verbal Reasoning Practice Paper 3 — Answers",
    skill_area: "Verbal reasoning answers",
    description: "Answers and short explanations for JDScience Verbal Reasoning Practice Paper 3.",
    file_name: "JDScience_11Plus_Verbal_Reasoning_Answers_3.pdf",
    file_url_override: "/resources/11-plus/verbal-reasoning/JDScience_11Plus_Verbal_Reasoning_Answers_3.pdf",
    series_label: "JDScience 11+ originals",
    section: "verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Non-Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Non-Verbal Reasoning Practice Paper 3",
    skill_area: "Sequences, rotations, reflections, matrices and spatial nets",
    description: "Original JDScience NVR Practice Paper 3 with code-drawn figures: sequences, rotations, reflections, matrices, odd one out, analogies, pattern completion and nets.",
    file_name: "JDScience_11Plus_Non_Verbal_Reasoning_Practice_Paper_3.pdf",
    file_url_override: "/resources/11-plus/non-verbal-reasoning/JDScience_11Plus_Non_Verbal_Reasoning_Practice_Paper_3.pdf",
    series_label: "JDScience 11+ originals",
    section: "non-verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Non-Verbal Reasoning",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Mark Schemes",
    title: "11+ Non-Verbal Reasoning Practice Paper 3 — Answers",
    skill_area: "Non-verbal reasoning answers",
    description: "Answers and short explanations for JDScience Non-Verbal Reasoning Practice Paper 3.",
    file_name: "JDScience_11Plus_Non_Verbal_Reasoning_Answers_3.pdf",
    file_url_override: "/resources/11-plus/non-verbal-reasoning/JDScience_11Plus_Non_Verbal_Reasoning_Answers_3.pdf",
    series_label: "JDScience 11+ originals",
    section: "non-verbal-reasoning",
  },
  {
    level: "11+",
    subject: "Mixed Practice",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Worksheets",
    title: "11+ Mixed Practice Paper 3",
    skill_area: "Mixed 11+ practice",
    description: "Original JDScience Mixed Practice Paper 3: a balanced mix of Maths, English, Verbal Reasoning and Non-Verbal Reasoning.",
    file_name: "JDScience_11Plus_Mixed_Practice_Paper_3.pdf",
    file_url_override: "/resources/11-plus/mixed-practice/JDScience_11Plus_Mixed_Practice_Paper_3.pdf",
    series_label: "JDScience 11+ originals",
    section: "mixed-practice",
  },
  {
    level: "11+",
    subject: "Mixed Practice",
    exam_board: "Grammar Schools",
    all_boards: true,
    resource_category: "Mark Schemes",
    title: "11+ Mixed Practice Paper 3 — Answers",
    skill_area: "Mixed 11+ practice answers",
    description: "Answers and short explanations for JDScience Mixed Practice Paper 3.",
    file_name: "JDScience_11Plus_Mixed_Practice_Answers_3.pdf",
    file_url_override: "/resources/11-plus/mixed-practice/JDScience_11Plus_Mixed_Practice_Answers_3.pdf",
    series_label: "JDScience 11+ originals",
    section: "mixed-practice",
  },
];
