/* Curated 11+ free resources.
   External items link to publisher-hosted pages/downloads only.
   No third-party PDFs are copied into JDScience storage. */

const CGP = "https://www.cgpbooks.co.uk/getmedia";
const GL_CDN = "https://cdn.shopify.com/s/files/1/0681/5498/2630/files";
const EXAM_COACH = "https://www.theexamcoach.tv";

export const ELEVEN_PLUS_SECTIONS = [
  "English",
  "Mathematics",
  "Verbal Reasoning",
  "Non-Verbal and Spatial Reasoning",
  "Mixed Practice Papers",
  "Answer Booklets",
];

export const ELEVEN_PLUS_ATTRIBUTION_NOTICE =
  "Third-party resources remain the property of their respective publishers. JDScience provides links for educational convenience and does not claim ownership of these materials.";

/** @typedef {{
 *  id: string,
 *  section: string,
 *  title: string,
 *  subject: string,
 *  resourceType: string,
 *  publisher: string,
 *  description: string,
 *  url: string,
 *  external: boolean,
 * }} ElevenPlusResource */

/** @type {ElevenPlusResource[]} */
export const ELEVEN_PLUS_RESOURCES = [
  /* ===================== English ===================== */
  {
    id: "jds-english-paper-1",
    section: "English",
    title: "JDScience 11+ English Practice Paper 1",
    subject: "English",
    resourceType: "Practice paper",
    publisher: "JDScience",
    description: "Original JDScience comprehension and writing practice paper for 11+ preparation. Free to download — no registration required.",
    url: "/resources/11plus/english/practice-papers/jdscience-11plus-english-practice-paper-1.pdf",
    external: false,
  },
  {
    id: "gl-english-familiarisation",
    section: "English",
    title: "GL Assessment English Familiarisation Pack",
    subject: "English",
    resourceType: "Familiarisation pack",
    publisher: "GL Assessment",
    description: "Official free familiarisation materials for GL Assessment 11+ English, including sample multiple-choice layouts.",
    url: `${GL_CDN}/english_1.zip`,
    external: true,
  },
  {
    id: "cgp-gl-english-paper",
    section: "English",
    title: "CGP Free GL English Practice Test",
    subject: "English",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP practice test for GL and other 11+ English providers, hosted on CGP Books.",
    url: `${CGP}/f3297999-dcd7-45d0-9756-94294ef3b324/cgp-11plus-gl-english-free-practice-test-updated`,
    external: true,
  },
  {
    id: "collins-english-samples",
    section: "English",
    title: "Collins 11+ English Free Samples",
    subject: "English",
    resourceType: "Sample worksheets hub",
    publisher: "Collins",
    description: "Free Quick Practice Test samples for GL Assessment English (ages 9–10 and 10–11). Open the Collins free samples page and choose English.",
    url: "https://collins.co.uk/pages/revision-collins-11-free-samples",
    external: true,
  },
  {
    id: "examberry-english",
    section: "English",
    title: "Examberry Free 11+ English Papers",
    subject: "English",
    resourceType: "Practice paper collection",
    publisher: "Examberry",
    description: "Curated list of free 11+ English practice papers and answers in PDF form on Examberry Papers.",
    url: "https://examberrypapers.co.uk/resources/free-11-plus-practice-papers/english/",
    external: true,
  },
  {
    id: "examcoach-english-paper-3",
    section: "English",
    title: "The Exam Coach Independent Style English Paper 3",
    subject: "English",
    resourceType: "Practice paper",
    publisher: "The Exam Coach",
    description: "Free independent-school style 11+ English comprehension and creative writing practice paper.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-Independent-Style-English-Paper-3.pdf`,
    external: true,
  },

  /* ===================== Mathematics ===================== */
  {
    id: "jds-maths-paper-1",
    section: "Mathematics",
    title: "JDScience 11+ Mathematics Practice Paper 1",
    subject: "Mathematics",
    resourceType: "Practice paper",
    publisher: "JDScience",
    description: "Original JDScience mathematics practice paper covering core 11+ topics. Free to download — no registration required.",
    url: "/resources/11plus/maths/practice-papers/jdscience-11plus-mathematics-practice-paper-1.pdf",
    external: false,
  },
  {
    id: "gl-maths-familiarisation",
    section: "Mathematics",
    title: "GL Assessment Maths Familiarisation Pack",
    subject: "Mathematics",
    resourceType: "Familiarisation pack",
    publisher: "GL Assessment",
    description: "Official free familiarisation materials for GL Assessment 11+ Maths.",
    url: `${GL_CDN}/maths.zip`,
    external: true,
  },
  {
    id: "cgp-gl-maths-paper",
    section: "Mathematics",
    title: "CGP Free GL Maths Practice Test",
    subject: "Mathematics",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP practice test for GL and other 11+ Maths providers.",
    url: `${CGP}/cd11a37e-aabd-400c-a03e-0ded5fb75297/cgp-11plus-gl-maths-free-practice-test`,
    external: true,
  },
  {
    id: "cgp-cem-maths-paper",
    section: "Mathematics",
    title: "CGP Free CEM Maths Practice Test",
    subject: "Mathematics",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP practice test written in the CEM 11+ Maths style.",
    url: `${CGP}/71de4382-b77e-4854-bc6c-46e53acb5249/cgp-11plus-cem-maths-free-practice-test`,
    external: true,
  },
  {
    id: "collins-maths-samples",
    section: "Mathematics",
    title: "Collins 11+ Maths Free Samples",
    subject: "Mathematics",
    resourceType: "Sample worksheets hub",
    publisher: "Collins",
    description: "Free Quick Practice Test samples for CEM and GL Assessment Maths. Open the Collins free samples page and choose Maths.",
    url: "https://collins.co.uk/pages/revision-collins-11-free-samples",
    external: true,
  },
  {
    id: "examberry-maths",
    section: "Mathematics",
    title: "Examberry Free 11+ Maths Papers",
    subject: "Mathematics",
    resourceType: "Practice paper collection",
    publisher: "Examberry",
    description: "Curated list of free 11+ Maths practice papers and answers on Examberry Papers.",
    url: "https://examberrypapers.co.uk/resources/free-11-plus-practice-papers/maths/",
    external: true,
  },
  {
    id: "examcoach-cem-maths-8",
    section: "Mathematics",
    title: "The Exam Coach CEM Mathematics Paper 8",
    subject: "Mathematics",
    resourceType: "Practice paper",
    publisher: "The Exam Coach",
    description: "Free CEM-style 11+ mathematics practice paper from The Exam Coach starter set.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-CEM-Mathematics-Paper-8.pdf`,
    external: true,
  },

  /* ===================== Verbal Reasoning ===================== */
  {
    id: "jds-vr-paper-1",
    section: "Verbal Reasoning",
    title: "JDScience 11+ Verbal Reasoning Practice Paper 1",
    subject: "Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "JDScience",
    description: "Original JDScience verbal reasoning practice paper. Free to download — no registration required.",
    url: "/resources/11plus/verbal-reasoning/practice-papers/jdscience-11plus-verbal-reasoning-practice-paper-1.pdf",
    external: false,
  },
  {
    id: "gl-vr-familiarisation",
    section: "Verbal Reasoning",
    title: "GL Assessment Verbal Reasoning Familiarisation Pack",
    subject: "Verbal Reasoning",
    resourceType: "Familiarisation pack",
    publisher: "GL Assessment",
    description: "Official free familiarisation materials for GL Assessment 11+ Verbal Reasoning.",
    url: `${GL_CDN}/verbal-reasoning.zip`,
    external: true,
  },
  {
    id: "gl-verbal-skills",
    section: "Verbal Reasoning",
    title: "GL Assessment Verbal Skills Familiarisation Pack",
    subject: "Verbal Reasoning",
    resourceType: "Familiarisation pack",
    publisher: "GL Assessment",
    description: "Official free verbal skills familiarisation materials from GL Assessment.",
    url: `${GL_CDN}/verbal-skills.zip`,
    external: true,
  },
  {
    id: "cgp-gl-vr-paper",
    section: "Verbal Reasoning",
    title: "CGP Free GL Verbal Reasoning Practice Test",
    subject: "Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP verbal reasoning practice test for GL and other 11+ providers.",
    url: `${CGP}/3a318c3a-62f6-4bec-a94d-f10dfe52a5ab/cgp-11plus-gl-vr-free-practice-test`,
    external: true,
  },
  {
    id: "cgp-cem-vr-paper",
    section: "Verbal Reasoning",
    title: "CGP Free CEM Verbal Reasoning Practice Test",
    subject: "Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP verbal reasoning practice test written in the CEM style.",
    url: `${CGP}/d2ab8a13-4c84-4a60-9821-cb4199df9b75/cgp-11plus-cem-vr-free-practice-test`,
    external: true,
  },
  {
    id: "collins-vr-samples",
    section: "Verbal Reasoning",
    title: "Collins 11+ Verbal Reasoning Free Samples",
    subject: "Verbal Reasoning",
    resourceType: "Sample worksheets hub",
    publisher: "Collins",
    description: "Free Quick Practice Test samples for CEM and GL Assessment Verbal Reasoning on the Collins free samples page.",
    url: "https://collins.co.uk/pages/revision-collins-11-free-samples",
    external: true,
  },
  {
    id: "examberry-vr",
    section: "Verbal Reasoning",
    title: "Examberry Free 11+ Verbal Reasoning Papers",
    subject: "Verbal Reasoning",
    resourceType: "Practice paper collection",
    publisher: "Examberry",
    description: "Curated free verbal reasoning practice papers and answers on Examberry Papers.",
    url: "https://examberrypapers.co.uk/resources/free-11-plus-practice-papers/verbal-reasoning/",
    external: true,
  },
  {
    id: "examcoach-vr-paper-4",
    section: "Verbal Reasoning",
    title: "The Exam Coach ISEB Verbal Reasoning Paper 4",
    subject: "Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "The Exam Coach",
    description: "Free ISEB Common Pre-Test style verbal reasoning practice paper.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-ISEB-Common-Pre-Test-Verbal-Reasoning-Paper-4.pdf`,
    external: true,
  },
  {
    id: "examcoach-vr-paper-1",
    section: "Verbal Reasoning",
    title: "The Exam Coach ISEB Verbal Reasoning Paper 1",
    subject: "Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "The Exam Coach",
    description: "Additional free ISEB Common Pre-Test verbal reasoning practice paper from The Exam Coach.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-ISEB-Common-Pre-Test-Verbal-Reasoning-Paper-1.pdf`,
    external: true,
  },

  /* ===== Non-Verbal and Spatial Reasoning ===== */
  {
    id: "jds-nvr-paper-1",
    section: "Non-Verbal and Spatial Reasoning",
    title: "JDScience 11+ Non-Verbal Reasoning Practice Paper 1",
    subject: "Non-Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "JDScience",
    description: "Original JDScience non-verbal reasoning practice paper. Free to download — no registration required.",
    url: "/resources/11plus/non-verbal-reasoning/practice-papers/jdscience-11plus-non-verbal-reasoning-practice-paper-1.pdf",
    external: false,
  },
  {
    id: "gl-nvr-familiarisation",
    section: "Non-Verbal and Spatial Reasoning",
    title: "GL Assessment Non-Verbal Reasoning Familiarisation Pack",
    subject: "Non-Verbal Reasoning",
    resourceType: "Familiarisation pack",
    publisher: "GL Assessment",
    description: "Official free familiarisation materials for GL Assessment 11+ Non-Verbal Reasoning.",
    url: `${GL_CDN}/non-verbal-reasoning.zip`,
    external: true,
  },
  {
    id: "cgp-gl-nvr-paper",
    section: "Non-Verbal and Spatial Reasoning",
    title: "CGP Free GL Non-Verbal Reasoning Practice Test",
    subject: "Non-Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP non-verbal reasoning practice test for GL and other 11+ providers.",
    url: `${CGP}/ed64ed07-37d0-45d5-8710-2d09e83fc1fa/cgp-11plus-gl-nvr-free-practice-test`,
    external: true,
  },
  {
    id: "cgp-cem-nvr-paper",
    section: "Non-Verbal and Spatial Reasoning",
    title: "CGP Free CEM Non-Verbal Reasoning Practice Test",
    subject: "Non-Verbal Reasoning",
    resourceType: "Practice paper",
    publisher: "CGP",
    description: "Free CGP non-verbal reasoning practice test written in the CEM style.",
    url: `${CGP}/861cbcbd-0330-4128-94a1-5dae8b3876aa/cgp-11plus-cem-nvr-free-practice-test`,
    external: true,
  },
  {
    id: "collins-nvr-spatial-samples",
    section: "Non-Verbal and Spatial Reasoning",
    title: "Collins 11+ Non-Verbal & Spatial Free Samples",
    subject: "Non-Verbal and Spatial Reasoning",
    resourceType: "Sample worksheets hub",
    publisher: "Collins",
    description: "Free Quick Practice Test samples for Non-Verbal Reasoning and Spatial Reasoning (CEM and GL) on the Collins free samples page.",
    url: "https://collins.co.uk/pages/revision-collins-11-free-samples",
    external: true,
  },
  {
    id: "examberry-nvr",
    section: "Non-Verbal and Spatial Reasoning",
    title: "Examberry Free 11+ Non-Verbal Reasoning Papers",
    subject: "Non-Verbal Reasoning",
    resourceType: "Practice paper collection",
    publisher: "Examberry",
    description: "Curated free non-verbal reasoning practice papers and answers on Examberry Papers.",
    url: "https://examberrypapers.co.uk/resources/free-11-plus-practice-papers/non-verbal-reasoning/",
    external: true,
  },

  /* ===================== Mixed Practice Papers ===================== */
  {
    id: "gl-free-materials-hub",
    section: "Mixed Practice Papers",
    title: "GL Assessment Free Familiarisation Materials",
    subject: "Mixed",
    resourceType: "Publisher hub",
    publisher: "GL Assessment",
    description: "Official GL Assessment free familiarisation page covering English, Maths, Verbal Reasoning, Non-Verbal Reasoning and mixed packs.",
    url: "https://11plus.gl-assessment.co.uk/pages/free-materials",
    external: true,
  },
  {
    id: "gl-nvr-maths-mixed",
    section: "Mixed Practice Papers",
    title: "GL Assessment Non-Verbal Reasoning & Maths Pack",
    subject: "Mixed",
    resourceType: "Familiarisation pack",
    publisher: "GL Assessment",
    description: "Combined free familiarisation pack covering Non-Verbal Reasoning and Maths.",
    url: `${GL_CDN}/non-verbal-reasoning-maths.zip`,
    external: true,
  },
  {
    id: "cgp-free-hub",
    section: "Mixed Practice Papers",
    title: "CGP Free 11+ Practice Papers (GL & CEM)",
    subject: "Mixed",
    resourceType: "Publisher hub",
    publisher: "CGP",
    description: "CGP free practice tests hub with separate GL and CEM downloads for English, Maths, Verbal Reasoning and Non-Verbal Reasoning.",
    url: "https://www.cgpbooks.co.uk/info/preparing-for-the-11-plus-with-cgp/free-11-plus-practice-tests",
    external: true,
  },
  {
    id: "collins-free-hub",
    section: "Mixed Practice Papers",
    title: "Collins 11+ Free Samples Hub",
    subject: "Mixed",
    resourceType: "Publisher hub",
    publisher: "Collins",
    description: "Collins free Quick Practice Test samples across English, Maths, Verbal Reasoning, Non-Verbal Reasoning and Spatial Reasoning.",
    url: "https://collins.co.uk/pages/revision-collins-11-free-samples",
    external: true,
  },
  {
    id: "examberry-free-hub",
    section: "Mixed Practice Papers",
    title: "Examberry Free 11+ Practice Papers Index",
    subject: "Mixed",
    resourceType: "Publisher hub",
    publisher: "Examberry",
    description: "Examberry index of free 11+ practice papers organised by subject and school.",
    url: "https://examberrypapers.co.uk/resources/free-11-plus-practice-papers/",
    external: true,
  },
  {
    id: "examberry-gl-mixed",
    section: "Mixed Practice Papers",
    title: "Examberry Free GL Assessment Practice Papers",
    subject: "Mixed",
    resourceType: "Practice paper collection",
    publisher: "Examberry",
    description: "Free GL Assessment-style practice papers gathered by Examberry across multiple subjects.",
    url: "https://examberrypapers.co.uk/resources/free-11-plus-practice-papers/gl-assessment/",
    external: true,
  },
  {
    id: "examcoach-hub",
    section: "Mixed Practice Papers",
    title: "The Exam Coach Free 11+ Practice Papers",
    subject: "Mixed",
    resourceType: "Publisher hub",
    publisher: "The Exam Coach",
    description: "Free starter set and weekly practice papers covering English, Maths and Verbal Reasoning, plus school-by-school past paper links.",
    url: `${EXAM_COACH}/11-plus-practice-papers`,
    external: true,
  },

  /* ===================== Answer Booklets ===================== */
  {
    id: "jds-english-answers",
    section: "Answer Booklets",
    title: "JDScience 11+ English Practice Paper 1 — Answers",
    subject: "English",
    resourceType: "Answer booklet",
    publisher: "JDScience",
    description: "Answers and explanations for JDScience English Practice Paper 1.",
    url: "/resources/11plus/english/answers/jdscience-11plus-english-practice-paper-1-answers.pdf",
    external: false,
  },
  {
    id: "jds-maths-answers",
    section: "Answer Booklets",
    title: "JDScience 11+ Mathematics Practice Paper 1 — Answers",
    subject: "Mathematics",
    resourceType: "Answer booklet",
    publisher: "JDScience",
    description: "Answers and explanations for JDScience Mathematics Practice Paper 1.",
    url: "/resources/11plus/maths/answers/jdscience-11plus-mathematics-practice-paper-1-answers.pdf",
    external: false,
  },
  {
    id: "jds-vr-answers",
    section: "Answer Booklets",
    title: "JDScience 11+ Verbal Reasoning Practice Paper 1 — Answers",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "JDScience",
    description: "Answers and explanations for JDScience Verbal Reasoning Practice Paper 1.",
    url: "/resources/11plus/verbal-reasoning/answers/jdscience-11plus-verbal-reasoning-practice-paper-1-answers.pdf",
    external: false,
  },
  {
    id: "jds-nvr-answers",
    section: "Answer Booklets",
    title: "JDScience 11+ Non-Verbal Reasoning Practice Paper 1 — Answers",
    subject: "Non-Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "JDScience",
    description: "Answers and explanations for JDScience Non-Verbal Reasoning Practice Paper 1.",
    url: "/resources/11plus/non-verbal-reasoning/answers/jdscience-11plus-non-verbal-reasoning-practice-paper-1-answers.pdf",
    external: false,
  },
  {
    id: "cgp-gl-english-answers",
    section: "Answer Booklets",
    title: "CGP GL English Practice Test — Answers",
    subject: "English",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP GL English practice test.",
    url: `${CGP}/ed610d7c-06b3-47c4-8c1d-10a843f466ee/cgp-11plus-gl-english-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-gl-english-answer-sheet",
    section: "Answer Booklets",
    title: "CGP GL English Practice Test — Answer Sheet",
    subject: "English",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable multiple-choice answer sheet for the CGP GL English free practice test.",
    url: `${CGP}/f1d0ecaa-a271-46c2-b4d0-af007cd196fc/cgp-11plus-gl-english-free-practice-test-answer-sheet`,
    external: true,
  },
  {
    id: "cgp-gl-maths-answers",
    section: "Answer Booklets",
    title: "CGP GL Maths Practice Test — Answers",
    subject: "Mathematics",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP GL Maths practice test.",
    url: `${CGP}/d46397ff-fa84-46a4-8002-db6e115f437f/cgp-11plus-gl-maths-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-gl-maths-answer-sheet",
    section: "Answer Booklets",
    title: "CGP GL Maths Practice Test — Answer Sheet",
    subject: "Mathematics",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable answer sheet for the CGP GL Maths free practice test.",
    url: `${CGP}/917a3e1b-042d-4339-b875-50bcfd39e04c/cgp-11plus-gl-maths-free-practice-test-answer-sheet`,
    external: true,
  },
  {
    id: "cgp-cem-maths-answers",
    section: "Answer Booklets",
    title: "CGP CEM Maths Practice Test — Answers",
    subject: "Mathematics",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP CEM Maths practice test.",
    url: `${CGP}/235a034f-9c8d-4058-9813-658f5063ce89/cgp-11plus-cem-maths-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-cem-maths-answer-sheet",
    section: "Answer Booklets",
    title: "CGP CEM Maths Practice Test — Answer Sheet",
    subject: "Mathematics",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable answer sheet for the CGP CEM Maths free practice test.",
    url: `${CGP}/efa6fcc0-1273-42e2-ba0a-2ebe381ce572/cgp-11plus-cem-maths-free-practice-test-answer-sheet`,
    external: true,
  },
  {
    id: "cgp-gl-vr-answers",
    section: "Answer Booklets",
    title: "CGP GL Verbal Reasoning Practice Test — Answers",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP GL Verbal Reasoning practice test.",
    url: `${CGP}/5aeaee65-6fbe-4ab0-ad97-134abcf56b49/cgp-11plus-gl-vr-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-gl-vr-answer-sheet",
    section: "Answer Booklets",
    title: "CGP GL Verbal Reasoning Practice Test — Answer Sheet",
    subject: "Verbal Reasoning",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable answer sheet for the CGP GL Verbal Reasoning free practice test.",
    url: `${CGP}/97d74063-278b-4717-9bf7-93370fe5508d/cgp-11plus-gl-vr-free-practice-test-answer-sheet`,
    external: true,
  },
  {
    id: "cgp-cem-vr-answers",
    section: "Answer Booklets",
    title: "CGP CEM Verbal Reasoning Practice Test — Answers",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP CEM Verbal Reasoning practice test.",
    url: `${CGP}/725f3806-f15f-47a2-b688-23138e652971/cgp-11plus-cem-vr-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-cem-vr-answer-sheets",
    section: "Answer Booklets",
    title: "CGP CEM Verbal Reasoning Practice Test — Answer Sheets",
    subject: "Verbal Reasoning",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable answer sheets for the CGP CEM Verbal Reasoning free practice test.",
    url: `${CGP}/b7d3b2a9-a078-4926-b956-2f3e9a5411e5/cgp-11plus-cem-vr-free-practice-test-answer-sheets`,
    external: true,
  },
  {
    id: "cgp-gl-nvr-answers",
    section: "Answer Booklets",
    title: "CGP GL Non-Verbal Reasoning Practice Test — Answers",
    subject: "Non-Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP GL Non-Verbal Reasoning practice test.",
    url: `${CGP}/f39b4aeb-3a66-4423-a76a-6a879ff4867c/cgp-11plus-gl-nvr-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-gl-nvr-answer-sheet",
    section: "Answer Booklets",
    title: "CGP GL Non-Verbal Reasoning Practice Test — Answer Sheet",
    subject: "Non-Verbal Reasoning",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable answer sheet for the CGP GL Non-Verbal Reasoning free practice test.",
    url: `${CGP}/78010d87-0916-473a-891e-1c8399202950/cgp-11plus-gl-nvr-free-practice-test-answer-sheet`,
    external: true,
  },
  {
    id: "cgp-cem-nvr-answers",
    section: "Answer Booklets",
    title: "CGP CEM Non-Verbal Reasoning Practice Test — Answers",
    subject: "Non-Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "CGP",
    description: "Official free answers for the CGP CEM Non-Verbal Reasoning practice test.",
    url: `${CGP}/ac58d249-13dd-4b76-a102-c138fbf101c0/cgp-11plus-cem-nvr-free-practice-test-answers`,
    external: true,
  },
  {
    id: "cgp-cem-nvr-answer-sheet",
    section: "Answer Booklets",
    title: "CGP CEM Non-Verbal Reasoning Practice Test — Answer Sheet",
    subject: "Non-Verbal Reasoning",
    resourceType: "Answer sheet",
    publisher: "CGP",
    description: "Printable answer sheet for the CGP CEM Non-Verbal Reasoning free practice test.",
    url: `${CGP}/d811c70e-4beb-49f7-87af-69b83ad8702a/cgp-11plus-cem-nvr-free-practice-test-answer-sheet`,
    external: true,
  },
  {
    id: "examcoach-english-model-answers",
    section: "Answer Booklets",
    title: "The Exam Coach English Paper 3 — Model Answers",
    subject: "English",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Model answers for Independent Style English Paper 3.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-Independent-Style-English-Paper-3-Model-Answers.pdf`,
    external: true,
  },
  {
    id: "examcoach-english-mark-scheme",
    section: "Answer Booklets",
    title: "The Exam Coach English Paper 3 — Mark Scheme",
    subject: "English",
    resourceType: "Mark scheme",
    publisher: "The Exam Coach",
    description: "Mark scheme for Independent Style English Paper 3.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-Independent-Style-English-Paper-3-Mark-Scheme.pdf`,
    external: true,
  },
  {
    id: "examcoach-vr4-answering-booklet",
    section: "Answer Booklets",
    title: "The Exam Coach VR Paper 4 — Answering Booklet",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Answering booklet for ISEB Common Pre-Test Verbal Reasoning Paper 4.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-ISEB-Common-Pre-Test-Verbal-Reasoning-Paper-4-Answering-Booklet.pdf`,
    external: true,
  },
  {
    id: "examcoach-vr4-answers",
    section: "Answer Booklets",
    title: "The Exam Coach VR Paper 4 — Answers",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Answers for ISEB Common Pre-Test Verbal Reasoning Paper 4.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-ISEB-Common-Pre-Test-Verbal-Reasoning-Paper-4-Answers.pdf`,
    external: true,
  },
  {
    id: "examcoach-vr1-answering-booklet",
    section: "Answer Booklets",
    title: "The Exam Coach VR Paper 1 — Answering Booklet",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Answering booklet for ISEB Common Pre-Test Verbal Reasoning Paper 1.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-ISEB-Common-Pre-Test-Verbal-Reasoning-Paper-1-Answering-Booklet.pdf`,
    external: true,
  },
  {
    id: "examcoach-vr1-answers",
    section: "Answer Booklets",
    title: "The Exam Coach VR Paper 1 — Answers",
    subject: "Verbal Reasoning",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Answers for ISEB Common Pre-Test Verbal Reasoning Paper 1.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-ISEB-Common-Pre-Test-Verbal-Reasoning-Paper-1-Answers.pdf`,
    external: true,
  },
  {
    id: "examcoach-maths8-answering-booklet",
    section: "Answer Booklets",
    title: "The Exam Coach CEM Maths Paper 8 — Answering Booklet",
    subject: "Mathematics",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Answering booklet for CEM Mathematics Paper 8.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-CEM-Mathematics-Paper-8-Answering-Booklet.pdf`,
    external: true,
  },
  {
    id: "examcoach-maths8-answers",
    section: "Answer Booklets",
    title: "The Exam Coach CEM Maths Paper 8 — Answers",
    subject: "Mathematics",
    resourceType: "Answer booklet",
    publisher: "The Exam Coach",
    description: "Answers for CEM Mathematics Paper 8.",
    url: `${EXAM_COACH}/s/The-Exam-Coach-11-CEM-Mathematics-Paper-8-Answers.pdf`,
    external: true,
  },
];

export function sectionSlug(section) {
  return String(section || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export function resourcesForSection(section) {
  return ELEVEN_PLUS_RESOURCES.filter((item) => item.section === section);
}
