export const RESOURCE_TYPES = [
  "Specifications",
  "Revision Notes",
  "Worksheets",
  "Past Questions",
  "Mark Schemes",
  "Examiner Reports",
  "Videos",
];

export const JOSEPH_TEACHING_SUBJECTS = ["Chemistry", "Physics", "Biology", "Applied Science", "Science"];

export const FEATURED_RESOURCE_LANDINGS = [
  {
    path: "/resources/gcse/chemistry/",
    level: "GCSE/IGCSE",
    levelSlug: "gcse",
    levelLabel: "GCSE",
    subject: "Chemistry",
    subjectSlug: "chemistry",
    boards: ["AQA", "Edexcel", "OCR", "Eduqas", "WJEC"],
    heading: "GCSE Chemistry Resources",
    title: "GCSE Chemistry Resources | Revision Notes, Worksheets & Past Papers | JDScience",
    description: "Explore JDScience GCSE Chemistry revision notes, worksheets, past-paper links and exam-focused resources for AQA, Edexcel, OCR and other exam boards.",
    intro: "This GCSE Chemistry page gathers revision notes, original worksheets and exam practice in one place, then opens the same JD Science resource library used on the past papers screen. Students can move from topic notes to exam-style questions without hunting through a generic file list. IGCSE Chemistry learners following a similar specification will also find useful practice here. Official past papers and mark schemes are linked by exam board, including AQA, Edexcel and OCR, with Eduqas and WJEC available where those routes apply. Each section below keeps the existing resource categories: specifications, worksheets, past questions, examiner reports and videos. Use the board links to open the live resource browser already filtered for GCSE Chemistry, then continue switching type or board there. If you want tutoring on atomic structure, quantitative chemistry or organic topics, Joseph Danso’s science profile explains how 1-to-1 support works.",
    related: [
      { href: "/resources/gcse/physics/", text: "GCSE Physics resources" },
      { href: "/resources/gcse/biology/", text: "GCSE Biology resources" },
      { href: "/resources/a-level/chemistry/", text: "A-Level Chemistry resources" },
      { href: "/papers?level=GCSE%2FIGCSE&subject=Chemistry", text: "GCSE Chemistry past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/gcse/physics/",
    level: "GCSE/IGCSE",
    levelSlug: "gcse",
    levelLabel: "GCSE",
    subject: "Physics",
    subjectSlug: "physics",
    boards: ["AQA", "Edexcel", "OCR", "Eduqas", "WJEC"],
    heading: "GCSE Physics Resources",
    title: "GCSE Physics Resources | Revision Notes & Exam Practice | JDScience",
    description: "Browse JDScience GCSE Physics worksheets, revision notes, past-paper links and mark schemes for AQA, Edexcel, OCR and other UK exam boards today.",
    intro: "Use this GCSE Physics landing page to reach energy, forces, electricity, waves and space topics through the existing JD Science resource system. Revision notes and worksheets sit alongside past questions so exam practice can follow the same idea you have just revised. IGCSE Physics students can use the same page where the content overlaps. Specifications, mark schemes and examiner reports stay in their usual categories rather than being copied into a second library. Choose AQA, Edexcel or OCR below to open the live past papers browser already set to GCSE Physics, then add Eduqas or WJEC if that is your course. Videos appear when a clip has been published for the topic. For tutoring on working, units and required practicals, the Find a Tutor page and Joseph Danso’s profile explain the next step.",
    related: [
      { href: "/resources/gcse/chemistry/", text: "GCSE Chemistry resources" },
      { href: "/resources/gcse/biology/", text: "GCSE Biology resources" },
      { href: "/resources/a-level/physics/", text: "A-Level Physics resources" },
      { href: "/papers?level=GCSE%2FIGCSE&subject=Physics", text: "GCSE Physics past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/gcse/biology/",
    level: "GCSE/IGCSE",
    levelSlug: "gcse",
    levelLabel: "GCSE",
    subject: "Biology",
    subjectSlug: "biology",
    boards: ["AQA", "Edexcel", "OCR", "Eduqas", "WJEC"],
    heading: "GCSE Biology Resources",
    title: "GCSE Biology Resources | Worksheets, Notes & Past Papers | JDScience",
    description: "Find JDScience GCSE Biology worksheets, revision notes, past questions and mark schemes for AQA, Edexcel, OCR and other UK exam boards here.",
    intro: "This GCSE Biology page is the public entry point for cells, organisation, infection, bioenergetics, homeostasis, inheritance and ecology. It does not duplicate files. It points into the same worksheets, revision notes and past-paper links already used on the JD Science papers screen. IGCSE Biology students can follow the same route where topics match. Resource types stay familiar: specifications, worksheets, past questions, mark schemes, examiner reports and videos. Board filters cover AQA, Edexcel and OCR, with Eduqas and WJEC included where those courses are listed. Open a category or board link to load the live browser with GCSE Biology already selected, then keep using the existing filters. Joseph Danso’s profile is here for students who want 1-to-1 science tutoring after independent practice.",
    related: [
      { href: "/resources/gcse/chemistry/", text: "GCSE Chemistry resources" },
      { href: "/resources/gcse/physics/", text: "GCSE Physics resources" },
      { href: "/resources/a-level/biology/", text: "A-Level Biology resources" },
      { href: "/papers?level=GCSE%2FIGCSE&subject=Biology", text: "GCSE Biology past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/a-level/chemistry/",
    level: "A-Level",
    levelSlug: "a-level",
    levelLabel: "A-Level",
    subject: "Chemistry",
    subjectSlug: "chemistry",
    boards: ["AQA", "Edexcel", "OCR", "Eduqas", "WJEC"],
    heading: "A-Level Chemistry Resources",
    title: "A-Level Chemistry Resources | Revision Notes, Worksheets & Past Papers | JDScience",
    description: "Study JDScience A-Level Chemistry worksheets, revision notes, past-paper links and mark schemes for AQA, Edexcel, OCR and related UK boards.",
    intro: "A-Level Chemistry needs more than a single mixed resources list. This page opens physical, inorganic and organic chemistry through the same JD Science library that powers the past papers tool. Use worksheets for structured practice, then move to past questions and mark schemes when you want exam timing and command-word accuracy. Specifications and examiner reports stay in their own sections so you can see how papers are set. AQA, Edexcel and OCR are the usual board routes; Eduqas and WJEC remain available in the live browser where those entries exist. Nothing here replaces an uploaded file or a Supabase record. It is a crawlable doorway into that existing set. Students who want tutoring after independent work can continue to Find a Tutor or read Joseph Danso’s science lecturer profile.",
    related: [
      { href: "/resources/gcse/chemistry/", text: "GCSE Chemistry resources" },
      { href: "/resources/a-level/physics/", text: "A-Level Physics resources" },
      { href: "/resources/a-level/biology/", text: "A-Level Biology resources" },
      { href: "/papers?level=A-Level&subject=Chemistry", text: "A-Level Chemistry past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/a-level/physics/",
    level: "A-Level",
    levelSlug: "a-level",
    levelLabel: "A-Level",
    subject: "Physics",
    subjectSlug: "physics",
    boards: ["AQA", "Edexcel", "OCR", "Eduqas", "WJEC"],
    heading: "A-Level Physics Resources",
    title: "A-Level Physics Resources | Revision Notes & Exam Practice | JDScience",
    description: "Access JDScience A-Level Physics revision notes, worksheets, past papers and examiner reports for AQA, Edexcel, OCR and other UK exam boards.",
    intro: "This A-Level Physics page is for mechanics, materials, electricity, waves, fields and nuclear topics. It sends you into the existing JD Science resource browser rather than creating a second copy of each paper or worksheet. Start with revision notes or worksheets, then use past questions and mark schemes to check method and significant figures. Examiner reports help you see the mistakes that cost marks. Specifications remain listed so you can confirm practicals and mathematical requirements. Filter by AQA, Edexcel or OCR, and keep Eduqas or WJEC in the live tool if that is your board. Related pages for A-Level Chemistry, A-Level Biology and GCSE Physics sit below so you can move between courses without returning to a generic menu. Tutoring requests go through Find a Tutor or Joseph Danso’s profile.",
    related: [
      { href: "/resources/gcse/physics/", text: "GCSE Physics resources" },
      { href: "/resources/a-level/chemistry/", text: "A-Level Chemistry resources" },
      { href: "/resources/a-level/biology/", text: "A-Level Biology resources" },
      { href: "/papers?level=A-Level&subject=Physics", text: "A-Level Physics past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/a-level/biology/",
    level: "A-Level",
    levelSlug: "a-level",
    levelLabel: "A-Level",
    subject: "Biology",
    subjectSlug: "biology",
    boards: ["AQA", "Edexcel", "OCR", "Eduqas", "WJEC"],
    heading: "A-Level Biology Resources",
    title: "A-Level Biology Resources | Worksheets, Notes & Exam Practice | JDScience",
    description: "Use JDScience A-Level Biology worksheets, revision notes, past questions and mark schemes for AQA, Edexcel, OCR and other UK exam boards here.",
    intro: "A-Level Biology covers biological molecules, cells, exchange, genetics, energy transfers and ecosystems. This landing page keeps those topics attached to the live JD Science resource set, so a worksheet or official paper is not stored twice. Revision notes and worksheets support first teaching and independent study. Past questions, mark schemes and examiner reports then show how application and analysis are marked. Specifications stay available for practical endorsement and core content checks. AQA, Edexcel and OCR are linked directly; Eduqas and WJEC remain in the board list on the papers screen. From here you can also open GCSE Biology or A-Level Chemistry if you are moving between levels or sciences. Joseph Danso’s profile is linked for students who want science tutoring after using the free materials.",
    related: [
      { href: "/resources/gcse/biology/", text: "GCSE Biology resources" },
      { href: "/resources/a-level/chemistry/", text: "A-Level Chemistry resources" },
      { href: "/resources/a-level/physics/", text: "A-Level Physics resources" },
      { href: "/papers?level=A-Level&subject=Biology", text: "A-Level Biology past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/btec/applied-science/",
    level: "BTEC",
    levelSlug: "btec",
    levelLabel: "BTEC",
    subject: "Applied Science",
    subjectSlug: "applied-science",
    boards: ["Pearson"],
    heading: "BTEC Applied Science Resources",
    title: "BTEC Applied Science Resources | Worksheets & Exam Practice | JDScience",
    description: "Explore JDScience BTEC Applied Science worksheets, revision support and exam-style practice linked from the existing Pearson resource library.",
    intro: "BTEC Applied Science is a vocational route, so this page focuses on practical scientific knowledge rather than a school GCSE layout. It opens the same JD Science resource browser used for other levels, already pointed at BTEC Applied Science. Use it for specifications, worksheets, exam-style questions and any videos that have been published for the course. Pearson is the board listed in the current catalogue. Related science pages for T-Level Science and GCSE Chemistry are included because many learners move between vocational and GCSE content. Files are not copied onto this page. When you choose a category, you continue in the live library, including any later admin uploads. Students who want tutoring in Applied Science can use Find a Tutor or Joseph Danso’s science lecturer profile.",
    related: [
      { href: "/resources/btec/health-and-social-care/", text: "BTEC Health and Social Care resources" },
      { href: "/resources/t-level/science/", text: "T-Level Science resources" },
      { href: "/resources/gcse/chemistry/", text: "GCSE Chemistry resources" },
      { href: "/resources/gcse/biology/", text: "GCSE Biology resources" },
      { href: "/papers?level=BTEC&subject=Applied%20Science", text: "BTEC Applied Science past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/btec/health-and-social-care/",
    level: "BTEC",
    levelSlug: "btec",
    levelLabel: "BTEC",
    subject: "Health and Social Care",
    subjectSlug: "health-and-social-care",
    boards: ["Pearson"],
    heading: "BTEC Health and Social Care Resources",
    title: "BTEC Health and Social Care Resources | Past Papers & Mark Schemes | JDScience",
    description: "Open official Pearson BTEC Health and Social Care past questions, mark schemes and examiner reports from the JDScience resource library.",
    intro: "This BTEC Health and Social Care page opens public Pearson files for Unit 1 Human Lifespan Development and Unit 2 Working in Health and Social Care. Click Open PDF on a paper or specification to view it in a new tab. Mark schemes and examiner reports stay on Pearson’s own library. Recent locked papers remain available only to registered centres. Related pages for BTEC Applied Science and T-Level Healthcare Science sit below if you are moving between vocational courses.",
    related: [
      { href: "/resources/btec/applied-science/", text: "BTEC Applied Science resources" },
      { href: "/papers?level=T-Level&subject=Healthcare%20Science", text: "T-Level Healthcare Science papers" },
      { href: "/papers?level=BTEC&subject=Health%20and%20Social%20Care", text: "BTEC Health and Social Care past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
  {
    path: "/resources/t-level/science/",
    level: "T-Level",
    levelSlug: "t-level",
    levelLabel: "T-Level",
    subject: "Science",
    subjectSlug: "science",
    boards: ["NCFE", "Pearson", "City & Guilds"],
    heading: "T-Level Science Resources",
    title: "T-Level Science Resources | Core Science Worksheets & Revision | JDScience",
    description: "Browse JDScience T-Level Science worksheets, core-science revision and exam practice for NCFE, Pearson and City & Guilds course routes here.",
    intro: "T-Level Science combines core scientific knowledge with occupational practice. This page is the public doorway into JD Science materials for that course, including original topic worksheets and any specifications, notes or videos already stored in the shared library. It does not create a second set of files. Choose Worksheets or Past Questions to open the live browser on T-Level Science, then pick NCFE, Pearson or City & Guilds. Related pages for BTEC Applied Science and GCSE Chemistry help if you are bridging from a previous course. Examiner reports and mark schemes appear in the usual categories when those items exist. For tutoring on core biology, chemistry or physics within the T-Level, use Find a Tutor or Joseph Danso’s profile.",
    related: [
      { href: "/papers?level=T-Level&subject=Laboratory%20Sciences", text: "T-Level Laboratory Sciences papers" },
      { href: "/papers?level=T-Level&subject=Healthcare%20Science", text: "T-Level Healthcare Science papers" },
      { href: "/papers?level=T-Level&subject=Food%20Sciences", text: "T-Level Food Sciences papers" },
      { href: "/resources/btec/applied-science/", text: "BTEC Applied Science resources" },
      { href: "/papers?level=T-Level&subject=Science", text: "T-Level Science past papers" },
      { href: "/tutors", text: "Find a science tutor" },
      { href: "/tutors/joseph-danso/", text: "Joseph Danso science lecturer profile" },
    ],
  },
];
