-- BTEC Level 3 Health and Social Care Unit 2 exam walkthroughs (£10 each).
-- Upload matching PDFs to the private shop-products bucket at each download_path
-- via Admin → Shop or scripts/publish-btec-hsc-unit2-walkthroughs.mjs before customers can download.
-- Do not call the publisher from /api/shop-products, Shop Admin list, npm run build, or Vercel deploy.

insert into public.shop_products (
  slug,
  title,
  short_description,
  description,
  price_pence,
  product_type,
  level,
  subject,
  exam_board,
  product_kind,
  is_published,
  published,
  download_path,
  image_path,
  preview_path,
  keywords,
  sort_order,
  is_featured
) values
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2017',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2017',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2017 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2017 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2017.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2017-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2017-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2017', 'Exam Walkthrough', 'Pearson']::text[],
    210,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2018',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2018',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2018 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2018 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2018.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2018-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2018-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2018', 'Exam Walkthrough', 'Pearson']::text[],
    211,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2019',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2019',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2019 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2019 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2019.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2019-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2019-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2019', 'Exam Walkthrough', 'Pearson']::text[],
    212,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2022',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2022',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2022 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2022 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2022.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2022-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2022-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2022', 'Exam Walkthrough', 'Pearson']::text[],
    213,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2023',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2023',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2023 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2023 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2023.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2023-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2023-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2023', 'Exam Walkthrough', 'Pearson']::text[],
    214,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2024',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2024',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2024 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2024 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2024.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2024-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2024-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2024', 'Exam Walkthrough', 'Pearson']::text[],
    215,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-june-2025',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — June 2025',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, June 2025 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the June 2025 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-june-2025.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2025-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-june-2025-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2025', 'Exam Walkthrough', 'Pearson']::text[],
    216,
    true
  ),
  (
    'btec-hsc-unit-2-mark-scheme-june-2025',
    'BTEC Health and Social Care Unit 2 Mark Scheme — June 2025',
    'JDScience model-answer mark scheme for BTEC Level 3 Health and Social Care Unit 2, June 2025 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Model-answer mark scheme for the June 2025 series, written to the BTEC Unit 2 command-word structure. These are original JDScience model answers, not the official Pearson mark scheme. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'practice_questions',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-mark-scheme-june-2025.pdf',
    'images/btec-hsc-unit-2-mark-scheme-june-2025-cover.png',
    'images/btec-hsc-unit-2-mark-scheme-june-2025-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'June 2025', 'Mark Scheme', 'Pearson']::text[],
    217,
    true
  ),
  (
    'btec-hsc-unit-2-exam-walkthrough-january-2026',
    'BTEC Health and Social Care Unit 2 Exam Walkthrough — January 2026',
    'Step-by-step JDScience walkthrough for BTEC Level 3 Health and Social Care Unit 2, January 2026 (paper 31491H).',
    'JDScience BTEC Level 3 Health and Social Care Unit 2 (Working in Health and Social Care, paper 31491H) resource. Exam walkthrough for the January 2026 series. Step-by-step command-word guidance, model answers and examiner-style tips for every question. This is an original JDScience teaching resource and does not reproduce the official Pearson question paper or mark scheme.',
    1000,
    'exam_walkthrough',
    'BTEC Level 3',
    'Health and Social Care',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-hsc-unit-2-exam-walkthrough-january-2026.pdf',
    'images/btec-hsc-unit-2-exam-walkthrough-january-2026-cover.png',
    'images/btec-hsc-unit-2-exam-walkthrough-january-2026-cover.png',
    ARRAY['BTEC', 'Level 3', 'Health and Social Care', 'Unit 2', 'Working in Health and Social Care', '31491H', 'January 2026', 'Exam Walkthrough', 'Pearson']::text[],
    218,
    true
  )
on conflict (slug) do update set
  title = excluded.title,
  short_description = excluded.short_description,
  description = excluded.description,
  price_pence = excluded.price_pence,
  product_type = excluded.product_type,
  level = excluded.level,
  subject = excluded.subject,
  exam_board = excluded.exam_board,
  product_kind = excluded.product_kind,
  is_published = excluded.is_published,
  published = excluded.published,
  download_path = coalesce(public.shop_products.download_path, excluded.download_path),
  image_path = coalesce(public.shop_products.image_path, excluded.image_path),
  preview_path = coalesce(public.shop_products.preview_path, excluded.preview_path),
  keywords = excluded.keywords,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  updated_at = now();
