-- BTEC Level 3 Applied Science Unit 1 teaching PowerPoints (£5 each).
-- Upload matching .pptx files to the private shop-products bucket at each download_path
-- via Admin → Shop before customers can download after purchase.

insert into public.shop_products (
  slug,
  title,
  short_description,
  description,
  price_pence,
  product_type,
  level,
  subject,
  exam_board,
  product_kind,
  is_published,
  published,
  download_path,
  keywords,
  sort_order
) values
  (
    'btec-level-3-cell-ultrastructure-powerpoint',
    'JDScience BTEC Level 3 Cell Ultrastructure Teaching PowerPoint',
    'Editable teaching slides for BTEC Level 3 Applied Science Unit 1 — cell ultrastructure.',
    'JDScience teaching PowerPoint for BTEC Level 3 Applied Science Unit 1 (Principles and Applications of Science I): cell ultrastructure. Digital download — upload the .pptx to shop-products/downloads/ via Admin → Shop if not already attached.',
    500,
    'powerpoint',
    'BTEC',
    'Applied Science',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-level-3-cell-ultrastructure-powerpoint.pptx',
    'BTEC Level 3 Applied Science Unit 1 cell ultrastructure PowerPoint Pearson',
    110
  ),
  (
    'btec-level-3-chemical-calculations-powerpoint',
    'JDScience BTEC Level 3 Chemical Calculations Teaching PowerPoint',
    'Editable teaching slides for BTEC Level 3 Applied Science Unit 1 — chemical calculations.',
    'JDScience teaching PowerPoint for BTEC Level 3 Applied Science Unit 1 (Principles and Applications of Science I): chemical calculations. Pairs with the free worksheet and answer sheet on the BTEC resources page.',
    500,
    'powerpoint',
    'BTEC',
    'Applied Science',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-level-3-chemical-calculations-powerpoint.pptx',
    'BTEC Level 3 Applied Science Unit 1 chemical calculations PowerPoint Pearson',
    111
  ),
  (
    'btec-level-3-structure-and-bonding-powerpoint',
    'JDScience BTEC Level 3 Structure and Bonding Teaching PowerPoint',
    'Editable teaching slides for BTEC Level 3 Applied Science Unit 1 — structure and bonding.',
    'JDScience teaching PowerPoint for BTEC Level 3 Applied Science Unit 1 (Principles and Applications of Science I): structure and bonding. Pairs with the free worksheet and answer sheet on the BTEC resources page.',
    500,
    'powerpoint',
    'BTEC',
    'Applied Science',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-level-3-structure-and-bonding-powerpoint.pptx',
    'BTEC Level 3 Applied Science Unit 1 structure bonding PowerPoint Pearson',
    112
  ),
  (
    'btec-level-3-waves-in-communication-powerpoint',
    'JDScience BTEC Level 3 Waves in Communication Teaching PowerPoint',
    'Editable teaching slides for BTEC Level 3 Applied Science Unit 1 — waves in communication.',
    'JDScience teaching PowerPoint for BTEC Level 3 Applied Science Unit 1 (Principles and Applications of Science I): waves in communication. Pairs with the free worksheet and answer sheet on the BTEC resources page.',
    500,
    'powerpoint',
    'BTEC',
    'Applied Science',
    'Pearson',
    'digital',
    true,
    true,
    'downloads/btec-level-3-waves-in-communication-powerpoint.pptx',
    'BTEC Level 3 Applied Science Unit 1 waves communication PowerPoint Pearson',
    113
  )
on conflict (slug) do update set
  title = excluded.title,
  short_description = excluded.short_description,
  description = excluded.description,
  price_pence = excluded.price_pence,
  product_type = excluded.product_type,
  level = excluded.level,
  subject = excluded.subject,
  exam_board = excluded.exam_board,
  product_kind = excluded.product_kind,
  is_published = excluded.is_published,
  published = excluded.published,
  download_path = coalesce(public.shop_products.download_path, excluded.download_path),
  keywords = excluded.keywords,
  sort_order = excluded.sort_order,
  updated_at = now();
