-- GCSE Science exam walkthrough paid digital products.
-- Upload matching PDFs/zip to the private shop-products bucket at each download_path
-- via Admin → Shop or scripts/publish-gcse-exam-walkthroughs.mjs before customers can download.

insert into public.shop_products (
  slug,
  title,
  short_description,
  description,
  price_pence,
  product_type,
  level,
  subject,
  exam_board,
  product_kind,
  is_published,
  published,
  download_path,
  keywords,
  sort_order,
  is_featured
) values
  (
    'gcse-chemistry-exam-walkthrough-pack',
    'GCSE Chemistry Exam Walkthrough Pack',
    'Step-by-step worked exam-style Chemistry questions with full mark breakdowns and examiner tips.',
    'JDScience GCSE Science exam walkthrough resource. Each question includes step-by-step thinking, model answers, mark breakdowns, common mistakes and examiner-style tips. Covers atomic structure, bonding, quantitative chemistry, chemical changes, energy, rates, organic chemistry, analysis, the atmosphere and resources. This is an original JDScience resource and does not reproduce copyrighted past-paper questions.',
    500,
    'exam_walkthrough',
    'GCSE/IGCSE',
    'Chemistry',
    'N/A',
    'digital',
    true,
    true,
    'downloads/gcse-chemistry-exam-walkthrough-pack.pdf',
    ARRAY['GCSE', 'IGCSE', 'Chemistry', 'Exam Walkthrough', 'Revision', 'Mark scheme']::text[],
    120,
    true
  ),
  (
    'gcse-biology-exam-walkthrough-pack',
    'GCSE Biology Exam Walkthrough Pack',
    'Step-by-step worked exam-style Biology questions with full mark breakdowns and examiner tips.',
    'JDScience GCSE Science exam walkthrough resource. Each question includes step-by-step thinking, model answers, mark breakdowns, common mistakes and examiner-style tips. Covers cell biology, organisation, infection, bioenergetics, homeostasis, inheritance, ecology and required practical skills. This is an original JDScience resource and does not reproduce copyrighted past-paper questions.',
    500,
    'exam_walkthrough',
    'GCSE/IGCSE',
    'Biology',
    'N/A',
    'digital',
    true,
    true,
    'downloads/gcse-biology-exam-walkthrough-pack.pdf',
    ARRAY['GCSE', 'IGCSE', 'Biology', 'Exam Walkthrough', 'Revision', 'Mark scheme']::text[],
    121,
    true
  ),
  (
    'gcse-physics-exam-walkthrough-pack',
    'GCSE Physics Exam Walkthrough Pack',
    'Step-by-step worked exam-style Physics questions with full mark breakdowns and examiner tips.',
    'JDScience GCSE Science exam walkthrough resource. Each question includes step-by-step thinking, model answers, mark breakdowns, common mistakes and examiner-style tips. Covers energy, electricity, particle model, radioactivity, forces, waves, magnetism, space physics and required practical skills. This is an original JDScience resource and does not reproduce copyrighted past-paper questions.',
    500,
    'exam_walkthrough',
    'GCSE/IGCSE',
    'Physics',
    'N/A',
    'digital',
    true,
    true,
    'downloads/gcse-physics-exam-walkthrough-pack.pdf',
    ARRAY['GCSE', 'IGCSE', 'Physics', 'Exam Walkthrough', 'Revision', 'Mark scheme']::text[],
    122,
    true
  ),
  (
    'gcse-science-exam-walkthrough-bundle',
    'GCSE Science Exam Walkthrough Bundle',
    'All three GCSE Science exam walkthrough packs — Chemistry, Biology and Physics — in one download.',
    'JDScience GCSE Science exam walkthrough resource. Includes the full Chemistry, Biology and Physics exam walkthrough packs (PDF and editable DOCX for each subject) in a single zip download. Each question includes step-by-step thinking, model answers, mark breakdowns, common mistakes and examiner-style tips. This is an original JDScience resource and does not reproduce copyrighted past-paper questions.',
    1299,
    'bundle',
    'GCSE/IGCSE',
    'Mixed',
    'N/A',
    'digital',
    true,
    true,
    'downloads/gcse-science-exam-walkthrough-bundle.zip',
    ARRAY['GCSE', 'IGCSE', 'Combined Science', 'Bundle', 'Chemistry', 'Biology', 'Physics', 'Exam Walkthrough']::text[],
    123,
    true
  )
on conflict (slug) do update set
  title = excluded.title,
  short_description = excluded.short_description,
  description = excluded.description,
  price_pence = excluded.price_pence,
  product_type = excluded.product_type,
  level = excluded.level,
  subject = excluded.subject,
  exam_board = excluded.exam_board,
  product_kind = excluded.product_kind,
  is_published = excluded.is_published,
  published = excluded.published,
  download_path = coalesce(public.shop_products.download_path, excluded.download_path),
  keywords = excluded.keywords,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  updated_at = now();
