import {
  arrow,
  bars,
  circle,
  combo,
  diamond,
  dots,
  plus,
  ringDot,
  row,
  square,
  triangle,
  choiceTiles,
} from "./nvr-figures.mjs";

function nvr(stem, figure, options, answer, explanation) {
  return {
    stem,
    figure,
    options: choiceTiles(options),
    answer,
    explanation,
    marks: 1,
  };
}

export const NVR_PAPERS = [
  {
    id: "nvr-1",
    file: "JDScience_11Plus_Non_Verbal_Reasoning_Practice_1.pdf",
    folder: "non-verbal-reasoning",
    title: "11+ Non-Verbal Reasoning: Practice 1",
    subject: "Non-Verbal Reasoning",
    skill_area: "Series, odd one out, analogies and matrices",
    description: "Original JDScience NVR figures: which comes next, odd one out, analogies and 2×2 matrices.",
    time: "20 minutes",
    instructions: "Look at the shapes. Choose the option that best completes the set. These figures were drawn for JDScience and are not copied from GL, CEM or any publisher.",
    questions: [
      nvr("Which figure comes next in the series?", row([dots(1), dots(2), dots(3)], "Series:"), [dots(2), dots(4), circle({ fill: "solid" }), plus()], "B", "The number of dots increases by one: 1, 2, 3, then 4."),
      nvr("Which figure comes next in the series?", row([arrow({ dir: "right" }), arrow({ dir: "down" }), arrow({ dir: "left" })], "Series:"), [arrow({ dir: "left" }), arrow({ dir: "right" }), arrow({ dir: "up" }), plus()], "C", "The arrow turns 90° clockwise: right, down, left, then up."),
      nvr("Which figure is the odd one out?", row([square({ fill: "solid" }), square({ fill: "pale" }), triangle({ fill: "solid" }), square({ fill: "none" })], "Set:"), [square({ fill: "solid" }), triangle({ fill: "solid" }), square({ fill: "pale" }), square({ fill: "none" })], "B", "Three figures are squares. The triangle is the odd one out."),
      nvr("Complete the analogy: small circle is to large circle as small square is to ?", `${row([circle({ r: 12 }), circle({ r: 28 })], "is to")}${row([square({ s: 22 })], "as")}`, [square({ s: 22 }), square({ s: 48 }), circle({ r: 28 }), triangle()], "B", "The second shape is a larger version of the first. A small square becomes a large square."),
      nvr("Which figure comes next?", row([triangle({ dir: "up" }), triangle({ dir: "down" }), triangle({ dir: "up" })], "Series:"), [triangle({ dir: "down" }), triangle({ dir: "left" }), circle(), square()], "A", "The triangle flips up, down, up, so the next is down."),
      nvr("Complete the 2×2 matrix. The bottom-right cell is missing.", `${row([circle({ fill: "pale" }), circle({ fill: "solid" })], "Row 1:")}${row([square({ fill: "pale" })], "Row 2:")}`, [square({ fill: "pale" }), square({ fill: "solid" }), circle({ fill: "solid" }), diamond({ fill: "solid" })], "B", "Each row keeps the same outline; the right-hand cell is solid. A pale square becomes a solid square."),
      nvr("Which figure is the odd one out?", row([bars(1), bars(1), bars(2), bars(1)], "Set:"), [bars(1), bars(2), bars(1), bars(1)], "B", "Three figures have one bar; one figure has two bars."),
      nvr("Which figure comes next?", row([plus({ rot: 0 }), plus({ rot: 45 }), plus({ rot: 90 })], "Series:"), [plus({ rot: 90 }), plus({ rot: 135 }), plus({ rot: 0 }), circle()], "B", "The plus rotates 45° each time: 0°, 45°, 90°, then 135°."),
      nvr("Complete the analogy.", `${row([combo([circle({ r: 26 }), dots(1)]), combo([circle({ r: 26 }), dots(2)])], "is to")}${row([combo([square({ s: 44 }), dots(1)])], "as")}`, [combo([square({ s: 44 }), dots(1)]), combo([square({ s: 44 }), dots(2)]), combo([circle({ r: 26 }), dots(2)]), diamond()], "B", "One extra dot is added. A square with one dot becomes a square with two dots."),
      nvr("Which figure comes next?", row([ringDot({ rot: 0 }), ringDot({ rot: 90 }), ringDot({ rot: 180 })], "Series:"), [ringDot({ rot: 180 }), ringDot({ rot: 270 }), ringDot({ rot: 0 }), plus()], "B", "The inner dot moves 90° clockwise: top, right, bottom, then left."),
      nvr("Which figure is the odd one out?", row([square(), square({ fill: "pale" }), diamond(), square({ fill: "solid" })], "Set:"), [square(), square({ fill: "pale" }), diamond(), square({ fill: "solid" })], "C", "Three figures are upright squares. The diamond is rotated 45°."),
      nvr("Which figure comes next?", row([bars(1), bars(2), bars(3)], "Series:"), [bars(2), bars(4), bars(1), circle({ fill: "solid" })], "B", "The number of bars increases by one: 1, 2, 3, then 4."),
      nvr("Which figure comes next?", row([circle({ r: 12 }), circle({ r: 18 }), circle({ r: 24 })], "Series:"), [circle({ r: 18 }), circle({ r: 30 }), square({ s: 40 }), dots(3)], "B", "The circle grows larger each time. The next radius continues the +6 pattern."),
      nvr("Which figure comes next?", row([arrow({ dir: "up" }), arrow({ dir: "right" }), arrow({ dir: "down" })], "Series:"), [arrow({ dir: "left" }), arrow({ dir: "up" }), arrow({ dir: "down" }), plus()], "A", "The arrow turns 90° clockwise: up, right, down, then left."),
      nvr("Which figure is the odd one out?", row([circle({ fill: "solid" }), circle({ fill: "pale" }), circle({ fill: "amber" }), plus()], "Set:"), [circle({ fill: "solid" }), circle({ fill: "pale" }), plus(), circle({ fill: "amber" })], "C", "Three figures are circles. The plus sign is the odd one out."),
      nvr("Complete the 2×2 matrix.", `${row([circle(), combo([circle(), plus()])], "Row 1:")}${row([square()], "Row 2:")}`, [square(), combo([square(), plus()]), circle(), plus()], "B", "The right-hand cell adds a plus to the left-hand shape. A square becomes a square with a plus."),
      nvr("Which figure comes next?", row([dots(1), dots(2), dots(3)], "Series:"), [dots(5), dots(4), bars(3), triangle()], "B", "Dots increase by one, so the next is four dots. (Same rule as Q1 with different options.)"),
      nvr("Complete the analogy: triangle pointing up is to triangle pointing down as arrow pointing up is to ?", `${row([triangle({ dir: "up" }), triangle({ dir: "down" })], "is to")}${row([arrow({ dir: "up" })], "as")}`, [arrow({ dir: "up" }), arrow({ dir: "down" }), triangle({ dir: "down" }), circle()], "B", "The shape is vertically flipped. An up arrow becomes a down arrow."),
      nvr("Which figure is the odd one out?", row([combo([circle({ r: 26 }), dots(1)]), combo([square({ s: 44 }), dots(1)]), combo([triangle(), dots(1)]), bars(3)], "Set:"), [combo([circle({ r: 26 }), dots(1)]), combo([square({ s: 44 }), dots(1)]), bars(3), combo([triangle(), dots(1)])], "C", "Three figures contain a single dot. The three-bar figure does not."),
      nvr("Which figure comes next?", row([diamond(), combo([diamond(), dots(1)]), combo([diamond(), dots(2)])], "Series:"), [combo([diamond(), dots(1)]), combo([diamond(), dots(3)]), square(), plus()], "B", "A diamond gains one extra dot each time: 0, 1, 2, then 3."),
    ],
  },
  {
    id: "nvr-2",
    file: "JDScience_11Plus_Non_Verbal_Reasoning_Practice_2.pdf",
    folder: "non-verbal-reasoning",
    title: "11+ Non-Verbal Reasoning: Practice 2",
    subject: "Non-Verbal Reasoning",
    skill_area: "Rotation, counting, codes and pattern completion",
    description: "A second original JDScience NVR paper with new figures: rotations, counting, shading and missing squares.",
    time: "20 minutes",
    instructions: "This is a second original paper. Work from the figures on this page only. Choose the best option for each question.",
    questions: [
      nvr("Which figure comes next?", row([triangle({ dir: "right" }), triangle({ dir: "down" }), triangle({ dir: "left" })], "Series:"), [triangle({ dir: "left" }), triangle({ dir: "up" }), triangle({ dir: "right" }), square()], "B", "The triangle turns 90° clockwise: right, down, left, then up."),
      nvr("Which figure is the odd one out?", row([dots(2), dots(2), dots(4), dots(2)], "Set:"), [dots(2), dots(2), dots(4), dots(2)], "C", "Three figures have two dots; one has four."),
      nvr("Complete the analogy: empty square is to shaded square as empty circle is to ?", `${row([square({ fill: "none" }), square({ fill: "solid" })], "is to")}${row([circle({ fill: "none" })], "as")}`, [circle({ fill: "none" }), circle({ fill: "solid" }), square({ fill: "solid" }), plus()], "B", "The outline stays the same and the fill becomes solid."),
      nvr("Which figure comes next?", row([bars(4), bars(3), bars(2)], "Series:"), [bars(1), bars(4), bars(2), circle()], "A", "One bar is removed each time: 4, 3, 2, then 1."),
      nvr("Which figure comes next?", row([ringDot({ rot: 0 }), ringDot({ rot: 45 }), ringDot({ rot: 90 })], "Series:"), [ringDot({ rot: 90 }), ringDot({ rot: 135 }), ringDot({ rot: 0 }), diamond()], "B", "The dot moves 45° clockwise each time: 0°, 45°, 90°, then 135°."),
      nvr("Complete the 2×2 matrix.", `${row([triangle({ dir: "up", fill: "pale" }), triangle({ dir: "up", fill: "solid" })], "Row 1:")}${row([triangle({ dir: "down", fill: "pale" })], "Row 2:")}`, [triangle({ dir: "down", fill: "pale" }), triangle({ dir: "down", fill: "solid" }), triangle({ dir: "up", fill: "solid" }), circle({ fill: "solid" })], "B", "Row 2 keeps the down triangle; the right-hand cell is solid, matching row 1."),
      nvr("Which figure is the odd one out?", row([arrow({ dir: "up" }), arrow({ dir: "down" }), plus(), arrow({ dir: "left" })], "Set:"), [arrow({ dir: "up" }), arrow({ dir: "down" }), plus(), arrow({ dir: "left" })], "C", "Three figures are arrows. The plus is the odd one out."),
      nvr("Which figure comes next?", row([square({ s: 20 }), square({ s: 32 }), square({ s: 44 })], "Series:"), [square({ s: 32 }), square({ s: 56 }), circle({ r: 24 }), dots(1)], "B", "The square grows by 12 units of side each time. The next side length is 56."),
      nvr("Complete the analogy.", `${row([combo([square({ s: 56 }), circle({ r: 14 })]), circle({ r: 22 })], "is to")}${row([combo([square({ s: 56 }), triangle()])], "as")}`, [triangle(), square(), circle(), plus()], "A", "The second figure is the inner shape on its own. The inner triangle is left."),
      nvr("Which figure comes next?", row([plus({ rot: 0 }), plus({ rot: 90 }), plus({ rot: 180 })], "Series:"), [plus({ rot: 180 }), plus({ rot: 270 }), plus({ rot: 45 }), circle()], "B", "The plus rotates 90° each time: 0°, 90°, 180°, then 270°."),
      nvr("Which figure is the odd one out?", row([circle({ fill: "solid" }), square({ fill: "solid" }), triangle({ fill: "solid" }), circle({ fill: "none" })], "Set:"), [circle({ fill: "solid" }), square({ fill: "solid" }), triangle({ fill: "solid" }), circle({ fill: "none" })], "D", "Three shapes are solid-filled. The empty circle is the odd one out."),
      nvr("Which figure comes next?", row([dots(4), dots(3), dots(2)], "Series:"), [dots(4), dots(1), bars(2), diamond()], "B", "One dot is removed each time: 4, 3, 2, then 1."),
      nvr("Complete the 2×2 matrix.", `${row([arrow({ dir: "right" }), arrow({ dir: "left" })], "Row 1:")}${row([arrow({ dir: "up" })], "Row 2:")}`, [arrow({ dir: "up" }), arrow({ dir: "down" }), arrow({ dir: "right" }), plus()], "B", "The right-hand cell is the left-hand arrow flipped. An up arrow becomes a down arrow."),
      nvr("Which figure comes next?", row([combo([circle({ r: 26 }), plus()]), combo([square({ s: 44 }), plus()]), combo([triangle(), plus()])], "Series:"), [combo([diamond(), plus()]), circle(), plus(), bars(1)], "A", "Each figure is a new outline with a plus inside. After circle, square and triangle, a diamond with a plus continues the set of simple outlines."),
      nvr("Which figure is the odd one out?", row([bars(2), bars(2), bars(2), bars(3)], "Set:"), [bars(2), bars(2), bars(3), bars(2)], "C", "Three figures have two bars; one has three."),
      nvr("Which figure comes next?", row([circle({ fill: "none" }), circle({ fill: "pale" }), circle({ fill: "solid" })], "Series:"), [circle({ fill: "pale" }), combo([circle({ r: 28 }), circle({ r: 12, fill: "solid" })]), square({ fill: "solid" }), dots(2)], "B", "Fill gets heavier: empty, pale, solid. The next step adds an inner solid circle as a further ‘stronger’ fill. Accept B as the only option that continues a fill change rather than changing shape."),
      nvr("Complete the analogy: two dots are to four dots as one bar is to ?", `${row([dots(2), dots(4)], "is to")}${row([bars(1)], "as")}`, [bars(1), bars(2), dots(4), plus()], "B", "The number of parts doubles. One bar becomes two bars."),
      nvr("Which figure comes next?", row([arrow({ dir: "left" }), arrow({ dir: "up" }), arrow({ dir: "right" })], "Series:"), [arrow({ dir: "down" }), arrow({ dir: "left" }), arrow({ dir: "right" }), square()], "A", "The arrow turns 90° clockwise: left, up, right, then down."),
      nvr("Which figure is the odd one out?", row([diamond({ fill: "pale" }), diamond({ fill: "solid" }), diamond(), square({ fill: "solid" })], "Set:"), [diamond({ fill: "pale" }), diamond({ fill: "solid" }), diamond(), square({ fill: "solid" })], "D", "Three figures are diamonds. The square is the odd one out."),
      nvr("Complete the 2×2 matrix.", `${row([dots(1), dots(2)], "Row 1:")}${row([dots(2)], "Row 2:")}`, [dots(2), dots(3), dots(1), circle()], "B", "Along each row the number of dots increases by one. Row 2 starts at 2, so the missing cell is 3 dots."),
    ],
  },
];
