function q(stem, answer, explanation, extra = {}) {
  return { stem, answer, explanation, marks: extra.marks || 1, ...extra };
}

export const VERBAL_PAPERS = [
  {
    id: "vr-1",
    file: "JDScience_11Plus_Verbal_Reasoning_Practice_1.pdf",
    folder: "verbal-reasoning",
    title: "11+ Verbal Reasoning: Practice 1",
    subject: "Verbal Reasoning",
    skill_area: "Codes, sequences and word relationships",
    description: "Original JDScience VR practice: letter sequences, analogies, codes, hidden words and odd-one-out.",
    time: "25 minutes",
    instructions: "Work quickly but carefully. Write letters in capitals. These questions are original JDScience items in a familiar 11+ style — not copied from any published paper.",
    questions: [
      q("Find the next letter: B D G K P ?", "V", "Gaps grow by one: +2, +3, +4, +5, then +6. P + 6 letters = V."),
      q("Find the next letter: Z X U Q L ?", "F", "Gaps: −2, −3, −4, −5, then −6. L minus 6 letters is F."),
      q("AC is to DF as HJ is to ?\nA) KM   B) KN   C) LM   D) KO", "A) KM", "Each letter moves three places on: A→D, C→F, so H→K and J→M."),
      q("Tree is to leaf as book is to ?\nA) library   B) page   C) story   D) shelf", "B) page", "A leaf is part of a tree; a page is part of a book."),
      q("Which word does not belong?  flute  violin  trumpet  drum  novel", "novel", "The first four are musical instruments; a novel is a book."),
      q("If the code for LAMP is MBNQ, what is the code for DESK?", "EFTL", "Each letter moves one place forward: D→E, E→F, S→T, K→L."),
      q("A=1, B=2, C=3 and so on. CAT = 3+1+20 = 24. What is the value of DOG?", "26", "D=4, O=15, G=7. 4 + 15 + 7 = 26."),
      q("A four-letter word is hidden in consecutive letters of: SHEPUTTHECARTAWAY\nWhich word is hidden?\nA) they   B) cart   C) heat   D) away", "B) cart", "CART sits inside THECART."),
      q("Move one letter from the first word to the second to make two new real words: BREAD    AND", "BEAD and RAND", "Move the letter R: BREAD without R is BEAD; AND with R is RAND."),
      q("Which pair makes a real compound word?\n1 sun   2 rain   3 bow   4 farm\nA) 1+3   B) 2+4   C) 2+3   D) 1+2", "C", "rain + bow = rainbow."),
      q("Find the next number: 5, 10, 20, 40, ?", "80", "Each term is multiplied by 2."),
      q("Find the next number: 3, 4, 6, 9, 13, ?", "18", "The differences are +1, +2, +3, +4, then +5."),
      q("Night is to dark as day is to ?\nA) moon   B) light   C) clock   D) week", "B) light", "Night is associated with dark; day is associated with light."),
      q("Which word does not belong?  square  circle  triangle  cube  rectangle", "cube", "A cube is 3D; the others are 2D shapes."),
      q("If the code for MIND is NJOE, what is the code for HOLD?", "IPME", "Each letter moves one place forward: H→I, O→P, L→M, D→E."),
      q("Kitten is to cat as foal is to ?\nA) sheep   B) horse   C) farm   D) pony", "B) horse", "A kitten is a young cat; a foal is a young horse."),
      q("Find the next pair: AB  CD  EF  GH  ?", "IJ", "Each pair is the next two letters of the alphabet."),
      q("Insert a letter that finishes the first word and starts the second: COL _ OWN", "T (COLT / TOWN)", "T makes COLT and TOWN."),
      q("Find the next number: 2, 6, 12, 20, 30, ?", "42", "Differences: +4, +6, +8, +10, then +12. 30 + 12 = 42."),
      q("Give an antonym of generous.", "mean / selfish / stingy / greedy (any sensible opposite)", "Generous means giving; the opposite is mean or selfish."),
      q("Finger is to hand as toe is to ?\nA) shoe   B) foot   C) sock   D) nail", "B) foot", "A finger is part of a hand; a toe is part of a foot."),
      q("If B=2, L=1, U=3, E=5, R=6, what is the code for BLUE?", "2135", "B=2, L=1, U=3, E=5, so BLUE = 2135."),
      q("Using the same letter codes as question 22, what is the code for BEER?", "2556", "B=2, E=5, E=5, R=6, so BEER = 2556."),
      q("Which word does not belong?  apple  orange  banana  carrot  grape", "carrot", "Carrot is a vegetable; the others are fruit."),
      q("Find two words that are closest in meaning:  rapid   slow   quick   heavy", "rapid and quick", "Both mean fast."),
      q("Complete the letter series: C F I L ?", "O", "Each letter moves three places on: C to F to I to L to O."),
      q("If the word TRAIN is written backwards, which letter is in the middle?", "A", "NIART has five letters; the middle letter is A."),
      q("Which word can be made from the letters in LISTEN (using each letter at most once)?\nA) tinsel   B) silent   C) both A and B   D) listen only", "C", "TINSEL and SILENT are both anagrams of LISTEN."),
      q("All oak trees are trees. Which statement must be true?\nA) All trees are oaks.   B) Some trees are oaks.   C) No trees are oaks.   D) Oaks are not trees.", "B", "If all oaks are trees, then some trees are oaks. A is not forced."),
      q("Find the missing word: UP is to DOWN as ALWAYS is to ?\nA) often   B) never   C) sometimes   D) usually", "B) never", "UP and DOWN are opposites; ALWAYS and NEVER are opposites."),
    ],
  },
  {
    id: "vr-2",
    file: "JDScience_11Plus_Verbal_Reasoning_Practice_2.pdf",
    folder: "verbal-reasoning",
    title: "11+ Verbal Reasoning: Practice 2",
    subject: "Verbal Reasoning",
    skill_area: "Logic, anagrams, codes and word puzzles",
    description: "A second original JDScience VR paper: compound words, letter moves, number patterns, analogies and codes.",
    time: "25 minutes",
    instructions: "This is a second original paper. Do not look at Practice 1 answers first. Jot brief working beside codes and sequences if it helps you.",
    questions: [
      q("Find the next letter: A C F J O ?", "U", "Gaps: +2, +3, +4, +5, then +6. O + 6 = U."),
      q("Find the next letter: B E H K ?", "N", "Each letter moves three places on."),
      q("Hot is to cold as full is to ?\nA) empty   B) meal   C) heavy   D) plate", "A) empty", "The pairs are opposites."),
      q("Which word does not belong?  robin  sparrow  eagle  trout  wren", "trout", "Trout is a fish; the others are birds."),
      q("If the code for HOPE is IPQF, what is the code for CALM?", "DBMN", "Each letter moves one place forward: C→D, A→B, L→M, M→N."),
      q("If A=1, B=2, C=3 and so on, what is the value of SUM?", "53", "S=19, U=21, M=13. 19 + 21 + 13 = 53."),
      q("A four-letter word is hidden in consecutive letters of: THEGOLDENLANTERN\nWhich word is hidden?\nA) gold   B) then   C) late   D) land", "A) gold", "GOLD sits inside THEGOLDEN."),
      q("Move one letter from the first word to the second to make two new real words: STARE    PIN", "STAR and PINE", "Move E from STARE to PIN."),
      q("Which pair makes a real compound word?\n1 moon   2 light   3 house   4 water\nA) 1+2   B) 2+4   C) 3+1   D) 4+2", "A", "moon + light = moonlight."),
      q("Find the next number: 81, 27, 9, 3, ?", "1", "Each term is divided by 3."),
      q("Find the next number: 1, 1, 2, 3, 5, 8, ?", "13", "Each term is the sum of the two before it: 5 + 8 = 13."),
      q("Doctor is to hospital as teacher is to ?\nA) lesson   B) school   C) book   D) pupil", "B) school", "A doctor works in a hospital; a teacher works in a school."),
      q("Which word does not belong?  pentagon  hexagon  octagon  triangle  kilometre", "kilometre", "Kilometre is a unit of length, not a polygon."),
      q("If the code for BEST is ADRS (each letter one place back), what is the code for COLD?", "BNKC", "C→B, O→N, L→K, D→C."),
      q("A four-letter word is hidden in: MYFRIENDTHESHIPSAILS\nWhich word is hidden?\nA) them   B) ship   C) sail   D) rind", "B) ship", "SHIP sits inside THESHIP."),
      q("Which pair makes a real compound word?\n1 butter   2 snow   3 fly   4 man\nA) 1+4   B) 2+3   C) 1+3   D) 2+1", "C", "butter + fly = butterfly. snow + man would be 2+4, which is not listed."),
      q("Find the next number: 7, 10, 13, 16, ?", "19", "Add 3 each time."),
      q("Painter is to brush as writer is to ?\nA) paper   B) pen   C) desk   D) story", "B) pen", "A painter’s tool is a brush; a writer’s tool is a pen."),
      q("Which word does not belong?  Monday  Tuesday  January  Wednesday  Friday", "January", "January is a month; the others are weekdays."),
      q("Write STOP backwards. Then write TIME backwards.", "POTS and EMIT", "Reverse each word letter by letter."),
      q("Which word is an anagram of HEART?\nA) earth   B) hater   C) both A and B   D) heat", "C", "EARTH and HATER both use H, E, A, R, T once."),
      q("Find the next pair: AZ  BY  CX  DW  ?", "EV", "First letters A,B,C,D,E; second letters Z,Y,X,W,V."),
      q("Some of the children in a club are boys. Which statement cannot be true?\nA) Some children are girls.   B) All children are girls.   C) Some children are boys.   D) Not all children are girls.", "B", "If some children are boys, it cannot be true that all children are girls."),
      q("What is the middle letter of PROBLEM?", "B", "P R O B L E M has seven letters; the fourth is B."),
      q("Find two words closest in meaning:  huge   tiny   vast   quiet", "huge and vast", "Both mean very large."),
      q("What does the prefix un- do in the word unkind?", "It makes the opposite meaning / not kind.", "un- reverses the meaning of the root word."),
      q("Find the next number: 100, 91, 82, 73, ?", "64", "Subtract 9 each time."),
      q("River is to bank as road is to ?\nA) car   B) kerb   C) map   D) bridge", "B) kerb", "A bank is the edge of a river; a kerb is the edge of a road."),
      q("If J=10, A=1 and M=13, what is the value of JAM?", "24", "10 + 1 + 13 = 24."),
      q("Few is to many as whisper is to ?\nA) secret   B) shout   C) quiet   D) mouth", "B) shout", "Few and many are opposites of amount; whisper and shout are opposites of volume."),
    ],
  },
];
